jubilant-funicular: nta::ResourceManager Class Reference
nta::ResourceManager Class Reference
Handles storing and retrieving textures so an image isn't loaded multiple times.
#include <ResourceManager.h>
Static Public Member Functions
static Result< GLTexture > getTexture (crstring imagePath, GLint minFilt=GL_LINEAR_MIPMAP_LINEAR, GLint magFilt=GL_LINEAR, crvec2 dimensions=glm::vec2(0))
static Result< GLTexture > getTexture (crstring imagePath, crvec2 dimensions, GLint minFilt=GL_LINEAR_MIPMAP_LINEAR, GLint magFilt=GL_LINEAR)
static Result< std::string > getFile (GLTexture tex)
static SpriteFont * getSpriteFont (crstring fontPath, int fontSize=32)
static void deleteTexture (crstring imagePath)
removes the resource with the given path from the map and deletes it
static void deleteSpriteFont (crstring fontPath, int fontSize=32)
static void destroy ()
Static Private Attributes
static std::map< std::string, GLTexture > m_textureMap
a map for associating a texture with the name of its file
static std::unordered_map< GLTexture, std::string > m_textureFiles
Inverse map to m_textureMap.
static std::map< std::pair< std::string, int >, SpriteFont * > m_fontMap
Why does this hold pointers?
Detailed Description
Handles storing and retrieving textures so an image isn't loaded multiple times.
Definition at line 12 of file ResourceManager.h.
Member Function Documentation
deleteSpriteFont()
void nta::ResourceManager::deleteSpriteFont (crstring fontPath, int fontSize = 32) static
Definition at line 41 of file ResourceManager.cpp.
Referenced by getTexture().
deleteTexture()
void nta::ResourceManager::deleteTexture (crstring imagePath) static
removes the resource with the given path from the map and deletes it
Definition at line 33 of file ResourceManager.cpp.
Referenced by getTexture().
destroy()
void nta::ResourceManager::destroy () static
Definition at line 51 of file ResourceManager.cpp.
Referenced by nta::cleanup(), and getTexture().
getFile()
Result< std::string > nta::ResourceManager::getFile (GLTexture tex) static
Definition at line 19 of file ResourceManager.cpp.
Referenced by getTexture().
getSpriteFont()
SpriteFont * nta::ResourceManager::getSpriteFont (crstring fontPath, int fontSize = 32) static
Definition at line 26 of file ResourceManager.cpp.
Referenced by getTexture().
getTexture() [1/2]
Result< GLTexture > nta::ResourceManager::getTexture (crstring imagePath, GLint minFilt = GL_LINEAR_MIPMAP_LINEAR, GLint magFilt = GL_LINEAR, crvec2 dimensions = glm::vec2(0)) static
returns the resource with the given path, loading it if need be Why was I returning references before?
Definition at line 8 of file ResourceManager.cpp.
Referenced by getTexture(), nta::Sprite::init(), and nta::SpriteSheet::SpriteSheet().
getTexture() [2/2]
static Result<GLTexture> nta::ResourceManager::getTexture (crstring imagePath, crvec2 dimensions, GLint minFilt = GL_LINEAR_MIPMAP_LINEAR, GLint magFilt = GL_LINEAR) inline static
Definition at line 27 of file ResourceManager.h.
Member Data Documentation
m_fontMap
std::map< std::pair< std::string, int >, SpriteFont * > nta::ResourceManager::m_fontMap static private
Why does this hold pointers?
Definition at line 19 of file ResourceManager.h.
Referenced by deleteSpriteFont(), destroy(), and getSpriteFont().
m_textureFiles
std::unordered_map< GLTexture, std::string > nta::ResourceManager::m_textureFiles static private
Inverse map to m_textureMap.
Definition at line 17 of file ResourceManager.h.
Referenced by destroy(), getFile(), and getTexture().
m_textureMap
std::map< std::string, GLTexture > nta::ResourceManager::m_textureMap static private
a map for associating a texture with the name of its file
Definition at line 15 of file ResourceManager.h.
Referenced by deleteTexture(), destroy(), and getTexture().
The documentation for this class was generated from the following files:
include/nta/ResourceManager.h
src/ResourceManager.cpp