jubilant-funicular: GLM_GTX_optimum_pow
GLM_GTX_optimum_pow
Experimental extensions
Functions
template<typename genType >
GLM_FUNC_DECL genType glm::gtx::pow2 (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::gtx::pow3 (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::gtx::pow4 (genType const &x)
Detailed Description
Include <glm/gtx/optimum_pow.hpp> to use the features of this extension.
Integer exponentiation of power functions.
Function Documentation
pow2()
template<typename genType > GLM_FUNC_DECL genType glm::gtx::pow2 (genType const & x)
#include <deps/glm/gtx/optimum_pow.hpp>
Returns x raised to the power of 2.
See also
GLM_GTX_optimum_pow
Definition at line 7 of file optimum_pow.inl.
Referenced by glm::catmullRom(), glm::hermite(), and glm::radialGradient().
pow3()
template<typename genType > GLM_FUNC_DECL genType glm::gtx::pow3 (genType const & x)
#include <deps/glm/gtx/optimum_pow.hpp>
Returns x raised to the power of 3.
See also
GLM_GTX_optimum_pow
Definition at line 13 of file optimum_pow.inl.
Referenced by glm::catmullRom(), and glm::hermite().
pow4()
template<typename genType > GLM_FUNC_DECL genType glm::gtx::pow4 (genType const & x)
#include <deps/glm/gtx/optimum_pow.hpp>
Returns x raised to the power of 4.
See also
GLM_GTX_optimum_pow
Definition at line 19 of file optimum_pow.inl.