jubilant-funicular: nta::ScreenManager Class Reference
nta::ScreenManager Class Reference
#include <ScreenManager.h>
Public Member Functions
ScreenManager (crstring title, float maxFPS, int width=640, int height=480)
sets the max fps and the window to use
~ScreenManager ()
basic destructor
GLSLProgram * getGLSLProgram (crstring progPath)
GLSLProgram * getGLSLProgram (crstring name, crstring vert, crstring frag)
Screen * getCurrScreen () const
returns the active screen
const Window * getWindow () const
returns the window
const InputManager & getInput () const
return the InputManager
float getFPS () const
returns the current fps
bool owns_event (const SDL_Event &event) const
returns true if this manager is responsible for handling the event
void addScreen (Screen *newScreen, int escIndex=-1, int xIndex=-1, crstring title="")
adds a screen and sets some of its properties
void switchScreen (int newIndex)
switches the to a new screen
void destroy ()
destroys screens
void run (void *initFocusData=nullptr)
Private Member Functions
void update_input ()
Updates the state of m_input.
Private Attributes
std::map< std::string, GLSLProgram > m_glslMap
Collection of GLSLProgram.
std::vector< Screen * > m_screens
the screens
InputManager m_input
Keeps track of all input received in this window.
FPSLimiter m_limiter
used to cap the FPS
Window * m_window
the main window used by the manager
int m_currScreen = -1
the index of the currently active screen
Static Private Attributes
static std::mutex m_window_creation_lock
static std::mutex m_event_lock
Lock for access the event queue.
Detailed Description
Manages a collection of screens
Todo:
(?) Move m_glslMap and m_input to Window?
Definition at line 17 of file ScreenManager.h.
Member Function Documentation
getCurrScreen()
Screen * nta::ScreenManager::getCurrScreen () const
returns the active screen
Todo:
write log error if m_currScreen is out of range
Definition at line 39 of file ScreenManager.cpp.
Referenced by run(), switchScreen(), and update_input().
getGLSLProgram() [1/2]
GLSLProgram * nta::ScreenManager::getGLSLProgram (crstring progPath)
Gets GLSLProgram at specified path
Assumes vertex shader is (progPath + ".vert") and fragment shader is (progPath + ".frag")
Definition at line 27 of file ScreenManager.cpp.
getGLSLProgram() [2/2]
GLSLProgram * nta::ScreenManager::getGLSLProgram (crstring name, crstring vert, crstring frag)
Gets GLSLProgram, specifying explicitly where the vertex and fragment shaders are.
Uses name as the key in the map
Definition at line 33 of file ScreenManager.cpp.
run()
void nta::ScreenManager::run (void * initFocusData = nullptr)
runs screen logic (render, update, handleInput, etc.)
initFocusData is the input to onFocus for the first screen
Definition at line 145 of file ScreenManager.cpp.
Referenced by getInput().
The documentation for this class was generated from the following files:
include/nta/ScreenManager.h
src/ScreenManager.cpp