jubilant-funicular: cimg_library_suffixed::CImgDisplay Struct Reference
cimg_library_suffixed::CImgDisplay Struct Reference
Allow the creation of windows, display images on them and manage user events (keyboard, mouse and windows events).
#include <CImg.h>
Public Member Functions
Overloaded Operators
template<typename t >
CImgDisplay & operator= (const CImg< t > &img)
Display image on associated window.
template<typename t >
CImgDisplay & operator= (const CImgList< t > &list)
Display list of images on associated window.
CImgDisplay & operator= (const CImgDisplay &disp)
Construct a display as a copy of another one .
operator bool () const
Return false if display is empty, true otherwise.
Instance Checking
bool is_empty () const
Return true if display is empty, false otherwise.
bool is_closed () const
Return true if display is closed (i.e. not visible on the screen), false otherwise.
bool is_resized () const
Return true if associated window has been resized on the screen, false otherwise.
bool is_moved () const
Return true if associated window has been moved on the screen, false otherwise.
bool is_event () const
Return true if any event has occured on the associated window, false otherwise.
bool is_fullscreen () const
Return true if current display is in fullscreen mode, false otherwise.
bool is_key () const
Return true if any key is being pressed on the associated window, false otherwise.
bool is_key (const unsigned int keycode) const
Return true if key specified by given keycode is being pressed on the associated window, false otherwise.
bool & is_key (const char *const keycode)
Return true if key specified by given keycode is being pressed on the associated window, false otherwise.
bool is_key_sequence (const unsigned int *const keycodes_sequence, const unsigned int length, const bool remove_sequence=false)
Return true if specified key sequence has been typed on the associated window, false otherwise.
_cimg_iskey_def (ESC)
Return true if the ESC key is being pressed on the associated window, false otherwise.
_cimg_iskey_def (F1)
_cimg_iskey_def (F2)
_cimg_iskey_def (F3)
_cimg_iskey_def (F4)
_cimg_iskey_def (F5)
_cimg_iskey_def (F6)
_cimg_iskey_def (F7)
_cimg_iskey_def (F8)
_cimg_iskey_def (F9)
_cimg_iskey_def (F10)
_cimg_iskey_def (F11)
_cimg_iskey_def (F12)
_cimg_iskey_def (PAUSE)
_cimg_iskey_def (1)
_cimg_iskey_def (2)
_cimg_iskey_def (3)
_cimg_iskey_def (4)
_cimg_iskey_def (5)
_cimg_iskey_def (6)
_cimg_iskey_def (7)
_cimg_iskey_def (8)
_cimg_iskey_def (9)
_cimg_iskey_def (0)
_cimg_iskey_def (BACKSPACE)
_cimg_iskey_def (INSERT)
_cimg_iskey_def (HOME)
_cimg_iskey_def (PAGEUP)
_cimg_iskey_def (TAB)
_cimg_iskey_def (Q)
_cimg_iskey_def (W)
_cimg_iskey_def (E)
_cimg_iskey_def (R)
_cimg_iskey_def (T)
_cimg_iskey_def (Y)
_cimg_iskey_def (U)
_cimg_iskey_def (I)
_cimg_iskey_def (O)
_cimg_iskey_def (P)
_cimg_iskey_def (DELETE)
_cimg_iskey_def (END)
_cimg_iskey_def (PAGEDOWN)
_cimg_iskey_def (CAPSLOCK)
_cimg_iskey_def (A)
_cimg_iskey_def (S)
_cimg_iskey_def (D)
_cimg_iskey_def (F)
_cimg_iskey_def (G)
_cimg_iskey_def (H)
_cimg_iskey_def (J)
_cimg_iskey_def (K)
_cimg_iskey_def (L)
_cimg_iskey_def (ENTER)
_cimg_iskey_def (SHIFTLEFT)
_cimg_iskey_def (Z)
_cimg_iskey_def (X)
_cimg_iskey_def (C)
_cimg_iskey_def (V)
_cimg_iskey_def (B)
_cimg_iskey_def (N)
_cimg_iskey_def (M)
_cimg_iskey_def (SHIFTRIGHT)
_cimg_iskey_def (ARROWUP)
_cimg_iskey_def (CTRLLEFT)
_cimg_iskey_def (APPLEFT)
_cimg_iskey_def (ALT)
_cimg_iskey_def (SPACE)
_cimg_iskey_def (ALTGR)
_cimg_iskey_def (APPRIGHT)
_cimg_iskey_def (MENU)
_cimg_iskey_def (CTRLRIGHT)
_cimg_iskey_def (ARROWLEFT)
_cimg_iskey_def (ARROWDOWN)
_cimg_iskey_def (ARROWRIGHT)
_cimg_iskey_def (PAD0)
_cimg_iskey_def (PAD1)
_cimg_iskey_def (PAD2)
_cimg_iskey_def (PAD3)
_cimg_iskey_def (PAD4)
_cimg_iskey_def (PAD5)
_cimg_iskey_def (PAD6)
_cimg_iskey_def (PAD7)
_cimg_iskey_def (PAD8)
_cimg_iskey_def (PAD9)
_cimg_iskey_def (PADADD)
_cimg_iskey_def (PADSUB)
_cimg_iskey_def (PADMUL)
_cimg_iskey_def (PADDIV)
Public Attributes
cimg_ulong _timer
cimg_ulong _fps_frames
cimg_ulong _fps_timer
unsigned int _width
unsigned int _height
unsigned int _normalization
float _fps_fps
float _min
float _max
bool _is_fullscreen
char * _title
unsigned int _window_width
unsigned int _window_height
unsigned int _button
unsigned int * _keys
unsigned int * _released_keys
int _window_x
int _window_y
int _mouse_x
int _mouse_y
int _wheel
bool _is_closed
bool _is_resized
bool _is_moved
bool _is_event
bool _is_keyESC
bool _is_keyF1
bool _is_keyF2
bool _is_keyF3
bool _is_keyF4
bool _is_keyF5
bool _is_keyF6
bool _is_keyF7
bool _is_keyF8
bool _is_keyF9
bool _is_keyF10
bool _is_keyF11
bool _is_keyF12
bool _is_keyPAUSE
bool _is_key1
bool _is_key2
bool _is_key3
bool _is_key4
bool _is_key5
bool _is_key6
bool _is_key7
bool _is_key8
bool _is_key9
bool _is_key0
bool _is_keyBACKSPACE
bool _is_keyINSERT
bool _is_keyHOME
bool _is_keyPAGEUP
bool _is_keyTAB
bool _is_keyQ
bool _is_keyW
bool _is_keyE
bool _is_keyR
bool _is_keyT
bool _is_keyY
bool _is_keyU
bool _is_keyI
bool _is_keyO
bool _is_keyP
bool _is_keyDELETE
bool _is_keyEND
bool _is_keyPAGEDOWN
bool _is_keyCAPSLOCK
bool _is_keyA
bool _is_keyS
bool _is_keyD
bool _is_keyF
bool _is_keyG
bool _is_keyH
bool _is_keyJ
bool _is_keyK
bool _is_keyL
bool _is_keyENTER
bool _is_keySHIFTLEFT
bool _is_keyZ
bool _is_keyX
bool _is_keyC
bool _is_keyV
bool _is_keyB
bool _is_keyN
bool _is_keyM
bool _is_keySHIFTRIGHT
bool _is_keyARROWUP
bool _is_keyCTRLLEFT
bool _is_keyAPPLEFT
bool _is_keyALT
bool _is_keySPACE
bool _is_keyALTGR
bool _is_keyAPPRIGHT
bool _is_keyMENU
bool _is_keyCTRLRIGHT
bool _is_keyARROWLEFT
bool _is_keyARROWDOWN
bool _is_keyARROWRIGHT
bool _is_keyPAD0
bool _is_keyPAD1
bool _is_keyPAD2
bool _is_keyPAD3
bool _is_keyPAD4
bool _is_keyPAD5
bool _is_keyPAD6
bool _is_keyPAD7
bool _is_keyPAD8
bool _is_keyPAD9
bool _is_keyPADADD
bool _is_keyPADSUB
bool _is_keyPADMUL
bool _is_keyPADDIV
Constructors / Destructor / Instance Management
~CImgDisplay ()
Destructor.
CImgDisplay ()
Construct an empty display.
CImgDisplay (const unsigned int width, const unsigned int height, const char *const title=0, const unsigned int normalization=3, const bool is_fullscreen=false, const bool is_closed=false)
Construct a display with specified dimensions.
template<typename T >
CImgDisplay (const CImg< T > &img, const char *const title=0, const unsigned int normalization=3, const bool is_fullscreen=false, const bool is_closed=false)
Construct a display from an image.
template<typename T >
CImgDisplay (const CImgList< T > &list, const char *const title=0, const unsigned int normalization=3, const bool is_fullscreen=false, const bool is_closed=false)
Construct a display from an image list.
CImgDisplay (const CImgDisplay &disp)
Construct a display as a copy of an existing one.
CImgDisplay & assign ()
Destructor - Empty constructor .
CImgDisplay & assign (const unsigned int width, const unsigned int height, const char *const title=0, const unsigned int normalization=3, const bool is_fullscreen=false, const bool is_closed=false)
Construct a display with specified dimensions .
template<typename T >
CImgDisplay & assign (const CImg< T > &img, const char *const title=0, const unsigned int normalization=3, const bool is_fullscreen=false, const bool is_closed=false)
Construct a display from an image .
template<typename T >
CImgDisplay & assign (const CImgList< T > &list, const char *const title=0, const unsigned int normalization=3, const bool is_fullscreen=false, const bool is_closed=false)
Construct a display from an image list .
CImgDisplay & assign (const CImgDisplay &disp)
Construct a display as a copy of another one .
template<typename T >
static void screenshot (CImg< T > &img)
Take a screenshot.
static void _no_display_exception ()
static CImgDisplay & empty ()
Return a reference to an empty display.
static const CImgDisplay & const_empty ()
Return a reference to an empty display .
static unsigned int _fitscreen (const unsigned int dx, const unsigned int dy, const unsigned int dz, const int dmin, const int dmax, const bool return_y)
Instance Characteristics
int width () const
Return display width.
int height () const
Return display height.
unsigned int normalization () const
Return normalization type of the display.
const char * title () const
Return title of the associated window as a C-string.
int window_width () const
Return width of the associated window.
int window_height () const
Return height of the associated window.
int window_x () const
Return X-coordinate of the associated window.
int window_y () const
Return Y-coordinate of the associated window.
int mouse_x () const
Return X-coordinate of the mouse pointer.
int mouse_y () const
Return Y-coordinate of the mouse pointer.
unsigned int button () const
Return current state of the mouse buttons.
int wheel () const
Return current state of the mouse wheel.
unsigned int key (const unsigned int pos=0) const
Return one entry from the pressed keys history.
unsigned int released_key (const unsigned int pos=0) const
Return one entry from the released keys history.
float frames_per_second ()
Return the current refresh rate, in frames per second.
static int screen_width ()
Return width of the screen (current resolution along the X-axis).
static int screen_height ()
Return height of the screen (current resolution along the Y-axis).
static unsigned int keycode (const char *const keycode)
Return keycode corresponding to the specified string.
Window Manipulation
template<typename T >
CImgDisplay & display (const CImg< T > &img)
Display image on associated window.
template<typename T >
CImgDisplay & display (const CImgList< T > &list, const char axis='x', const float align=0)
Display list of images on associated window.
CImgDisplay & show ()
Show (closed) associated window on the screen.
CImgDisplay & close ()
Close (visible) associated window and make it disappear from the screen.
CImgDisplay & move (const int pos_x, const int pos_y)
Move associated window to a new location.
CImgDisplay & resize (const bool force_redraw=true)
Resize display to the size of the associated window.
CImgDisplay & resize (const int width, const int height, const bool force_redraw=true)
Resize display to the specified size.
template<typename T >
CImgDisplay & resize (const CImg< T > &img, const bool force_redraw=true)
Resize display to the size of an input image.
CImgDisplay & resize (const CImgDisplay &disp, const bool force_redraw=true)
Resize display to the size of another CImgDisplay instance.
CImgDisplay & set_normalization (const unsigned int normalization)
Set normalization type.
CImgDisplay & set_title (const char *const format,...)
Set title of the associated window.
CImgDisplay & set_fullscreen (const bool is_fullscreen, const bool force_redraw=true)
Enable or disable fullscreen mode.
CImgDisplay & toggle_fullscreen (const bool force_redraw=true)
Toggle fullscreen mode.
CImgDisplay & show_mouse ()
Show mouse pointer.
CImgDisplay & hide_mouse ()
Hide mouse pointer.
CImgDisplay & set_mouse (const int pos_x, const int pos_y)
Move mouse pointer to a specified location.
CImgDisplay & set_button ()
Simulate a mouse button release event.
CImgDisplay & set_button (const unsigned int button, const bool is_pressed=true)
Simulate a mouse button press or release event.
CImgDisplay & set_wheel ()
Flush all mouse wheel events.
CImgDisplay & set_wheel (const int amplitude)
Simulate a wheel event.
CImgDisplay & set_key ()
Flush all key events.
CImgDisplay & set_key (const unsigned int keycode, const bool is_pressed=true)
Simulate a keyboard press/release event.
CImgDisplay & flush ()
Flush all display events.
CImgDisplay & wait ()
Wait for any user event occuring on the current display.
CImgDisplay & wait (const unsigned int milliseconds)
Wait for a given number of milliseconds since the last call to wait().
template<typename T >
CImgDisplay & render (const CImg< T > &img)
Render image into internal display buffer.
CImgDisplay & paint ()
Paint internal display buffer on associated window.
template<typename T >
const CImgDisplay & snapshot (CImg< T > &img) const
Take a snapshot of the associated window content.
template<typename t , typename T >
static void _render_resize (const T *ptrs, const unsigned int ws, const unsigned int hs, t *ptrd, const unsigned int wd, const unsigned int hd)
static void wait (CImgDisplay &disp1)
Wait for any event occuring on the display disp1.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2)
Wait for any event occuring either on the display disp1 or disp2.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3)
Wait for any event occuring either on the display disp1, disp2 or disp3.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4)
Wait for any event occuring either on the display disp1, disp2, disp3 or disp4.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4, CImgDisplay &disp5)
Wait for any event occuring either on the display disp1, disp2, disp3, disp4 or disp5.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4, CImgDisplay &disp5, CImgDisplay &disp6)
Wait for any event occuring either on the display disp1, disp2, disp3, disp4, ... disp6.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4, CImgDisplay &disp5, CImgDisplay &disp6, CImgDisplay &disp7)
Wait for any event occuring either on the display disp1, disp2, disp3, disp4, ... disp7.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4, CImgDisplay &disp5, CImgDisplay &disp6, CImgDisplay &disp7, CImgDisplay &disp8)
Wait for any event occuring either on the display disp1, disp2, disp3, disp4, ... disp8.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4, CImgDisplay &disp5, CImgDisplay &disp6, CImgDisplay &disp7, CImgDisplay &disp8, CImgDisplay &disp9)
Wait for any event occuring either on the display disp1, disp2, disp3, disp4, ... disp9.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4, CImgDisplay &disp5, CImgDisplay &disp6, CImgDisplay &disp7, CImgDisplay &disp8, CImgDisplay &disp9, CImgDisplay &disp10)
Wait for any event occuring either on the display disp1, disp2, disp3, disp4, ... disp10.
static void wait_all ()
Wait for any window event occuring in any opened CImgDisplay.
template<typename T >
static void screenshot (const int x0, const int y0, const int x1, const int y1, CImg< T > &img)
Take a snapshot of the current screen content.
Detailed Description
Allow the creation of windows, display images on them and manage user events (keyboard, mouse and windows events).
CImgDisplay methods rely on a low-level graphic library to perform: it can be either X-Window (X11, for Unix-based systems) or GDI32 (for Windows-based systems). If both libraries are missing, CImgDisplay will not be able to display images on screen, and will enter a minimal mode where warning messages will be outputed each time the program is trying to call one of the CImgDisplay method.
The configuration variable cimg_display tells about the graphic library used. It is set automatically by when one of these graphic libraries has been detected. But, you can override its value if necessary. Valid choices are:
0: Disable display capabilities.
1: Use X-Window (X11) library.
2: Use GDI32 library.
Remember to link your program against X11 or GDI32 libraries if you use CImgDisplay.
Definition at line 7063 of file CImg.h.
Constructor & Destructor Documentation
~CImgDisplay()
cimg_library_suffixed::CImgDisplay::~CImgDisplay () inline
Destructor.
Note
If the associated window is visible on the screen, it is closed by the call to the destructor.
Definition at line 7131 of file CImg.h.
CImgDisplay() [1/5]
cimg_library_suffixed::CImgDisplay::CImgDisplay () inline
Construct an empty display.
Note
Constructing an empty CImgDisplay instance does not make a window appearing on the screen, until display of valid data is performed.
Example
CImgDisplay disp;  // Does actually nothing.
...
disp.display(img); // Construct new window and display image in it.
Definition at line 7148 of file CImg.h.
CImgDisplay() [2/5]
cimg_library_suffixed::CImgDisplay::CImgDisplay (const unsigned int width, const unsigned int height, const char *const title = 0, const unsigned int normalization = 3, const bool is_fullscreen = false, const bool is_closed = false) inline
Construct a display with specified dimensions.
Parameters
width Window width.
height Window height.
title Window title.
normalization Normalization type (0=none, 1=always, 2=once, 3=pixel type-dependent, see normalization()).
is_fullscreen Tells if fullscreen mode is enabled.
is_closed Tells if associated window is initially visible or not.
Note
A black background is initially displayed on the associated window.
Definition at line 7170 of file CImg.h.
CImgDisplay() [3/5]
template<typename T > cimg_library_suffixed::CImgDisplay::CImgDisplay (const CImg< T > & img, const char *const title = 0, const unsigned int normalization = 3, const bool is_fullscreen = false, const bool is_closed = false) inline explicit
Construct a display from an image.
Parameters
img Image used as a model to create the window.
title Window title.
normalization Normalization type (0=none, 1=always, 2=once, 3=pixel type-dependent, see normalization()).
is_fullscreen Tells if fullscreen mode is enabled.
is_closed Tells if associated window is initially visible or not.
Note
The pixels of the input image are initially displayed on the associated window.
Definition at line 7194 of file CImg.h.
CImgDisplay() [4/5]
template<typename T > cimg_library_suffixed::CImgDisplay::CImgDisplay (const CImgList< T > & list, const char *const title = 0, const unsigned int normalization = 3, const bool is_fullscreen = false, const bool is_closed = false) inline explicit
Construct a display from an image list.
Parameters
list The images list to display.
title Window title.
normalization Normalization type (0=none, 1=always, 2=once, 3=pixel type-dependent, see normalization()).
is_fullscreen Tells if fullscreen mode is enabled.
is_closed Tells if associated window is initially visible or not.
Note
All images of the list, appended along the X-axis, are initially displayed on the associated window.
Definition at line 7218 of file CImg.h.
CImgDisplay() [5/5]
cimg_library_suffixed::CImgDisplay::CImgDisplay (const CImgDisplay & disp) inline
Construct a display as a copy of an existing one.
Parameters
disp Display instance to copy.
Note
The pixel buffer of the input window is initially displayed on the associated window.
Definition at line 7237 of file CImg.h.
Member Function Documentation
_cimg_iskey_def()
cimg_library_suffixed::CImgDisplay::_cimg_iskey_def (ESC)
Return true if the ESC key is being pressed on the associated window, false otherwise.
Note
Similar methods exist for all keys managed by (see cimg::keyESC).
assign()
CImgDisplay& cimg_library_suffixed::CImgDisplay::assign () inline
Destructor - Empty constructor .
Note
Replace the current instance by an empty display.
Definition at line 7268 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), empty(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
button()
unsigned int cimg_library_suffixed::CImgDisplay::button () const inline
Return current state of the mouse buttons.
Note
Three mouse buttons can be managed. If one button is pressed, its corresponding bit in the returned value is set:
bit 0 (value 0x1): State of the left mouse button.
bit 1 (value 0x2): State of the right mouse button.
bit 2 (value 0x4): State of the middle mouse button.
Several bits can be activated if more than one button are pressed at the same time.
Example
CImgDisplay disp(400,400);
while (!disp.is_closed()) {
  if (disp.button()&1) { // Left button clicked.
    ...
  }
  if (disp.button()&2) { // Right button clicked.
    ...
  }
  if (disp.button()&4) { // Middle button clicked.
    ...
  }
  disp.wait();
}
Definition at line 7807 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
close()
CImgDisplay& cimg_library_suffixed::CImgDisplay::close () inline
Close (visible) associated window and make it disappear from the screen.
Note
A closed display only means the associated window is not visible anymore. This does not mean the display has been destroyed. Use show() to make the associated window reappear.
Using close() on a closed display does nothing.
Definition at line 7998 of file CImg.h.
display() [1/2]
template<typename T > CImgDisplay& cimg_library_suffixed::CImgDisplay::display (const CImg< T > & img) inline
Display image on associated window.
Parameters
img Input image to display.
Note
This method returns immediately.
Definition at line 7945 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), and snapshot().
display() [2/2]
template<typename T > CImgDisplay& cimg_library_suffixed::CImgDisplay::display (const CImgList< T > & list, const char axis = 'x', const float align = 0) inline
Display list of images on associated window.
Parameters
list List of images to display.
axis Axis used to append the images along, for the visualization (can be x, y, z or c).
align Relative position of aligned images when displaying lists with images of different sizes (0 for upper-left, 0.5 for centering and 1 for lower-right).
Note
This method returns immediately.
Definition at line 7960 of file CImg.h.
empty()
static CImgDisplay& cimg_library_suffixed::CImgDisplay::empty () inline static
Return a reference to an empty display.
Note
Can be useful for writing function prototypes where one of the argument (of type CImgDisplay&) must have a default value.
Example
void foo(CImgDisplay& disp=CImgDisplay::empty());
Definition at line 7324 of file CImg.h.
flush()
CImgDisplay& cimg_library_suffixed::CImgDisplay::flush () inline
Flush all display events.
Note
Remove all passed events from the current display.
Definition at line 8347 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), and cimg_library_suffixed::CImg< charT >::display_object3d().
frames_per_second()
float cimg_library_suffixed::CImgDisplay::frames_per_second () inline
Return the current refresh rate, in frames per second.
Note
Returns a significant value when the current instance is used to display successive frames. It measures the delay between successive calls to frames_per_second().
Definition at line 7918 of file CImg.h.
height()
int cimg_library_suffixed::CImgDisplay::height () const inline
Return display height.
Note
The height of the display (i.e. the height of the pixel data buffer associated to the CImgDisplay instance) may be different from the actual height of the associated window.
Definition at line 7687 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_resize(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), cimg_library_suffixed::CImg< charT >::get_select_graph(), resize(), and cimg_library_suffixed::CImg< charT >::resize().
hide_mouse()
CImgDisplay& cimg_library_suffixed::CImgDisplay::hide_mouse () inline
Hide mouse pointer.
Note
Depending on the window manager behavior, this method may not succeed (no exceptions are thrown nevertheless).
Definition at line 8171 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_select().
is_closed()
bool cimg_library_suffixed::CImgDisplay::is_closed () const inline
Return true if display is closed (i.e. not visible on the screen), false otherwise.
Note
When a user physically closes the associated window, the display is set to closed.
A closed display is not destroyed. Its associated window can be show again on the screen using show().
Definition at line 7418 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
is_key() [1/3]
bool cimg_library_suffixed::CImgDisplay::is_key () const inline
Return true if any key is being pressed on the associated window, false otherwise.
Note
The methods below do the same only for specific keys.
Definition at line 7454 of file CImg.h.
is_key() [2/3]
bool cimg_library_suffixed::CImgDisplay::is_key (const unsigned int keycode) const inline
Return true if key specified by given keycode is being pressed on the associated window, false otherwise.
Parameters
keycode Keycode to test.
Note
Keycode constants are defined in the cimg namespace and are architecture-dependent. Use them to ensure your code stay portable (see cimg::keyESC).
Example
CImgDisplay disp(400,400);
while (!disp.is_closed()) {
  if (disp.key(cimg::keyTAB)) { ... }  // Equivalent to 'if (disp.is_keyTAB())'.
  disp.wait();
}
Definition at line 7496 of file CImg.h.
is_key() [3/3]
bool& cimg_library_suffixed::CImgDisplay::is_key (const char *const keycode) inline
Return true if key specified by given keycode is being pressed on the associated window, false otherwise.
Parameters
keycode C-string containing the keycode label of the key to test.
Note
Use it when the key you want to test can be dynamically set by the user.
Example
CImgDisplay disp(400,400);
const char *const keycode = "TAB";
while (!disp.is_closed()) {
  if (disp.is_key(keycode)) { ... }  // Equivalent to 'if (disp.is_keyTAB())'.
  disp.wait();
}
Definition at line 7540 of file CImg.h.
is_key_sequence()
bool cimg_library_suffixed::CImgDisplay::is_key_sequence (const unsigned int *const keycodes_sequence, const unsigned int length, const bool remove_sequence = false) inline
Return true if specified key sequence has been typed on the associated window, false otherwise.
Parameters
keycodes_sequence Buffer of keycodes to test.
length Number of keys in the keycodes_sequence buffer.
remove_sequence Tells if the key sequence must be removed from the key history, if found.
Note
Keycode constants are defined in the cimg namespace and are architecture-dependent. Use them to ensure your code stay portable (see cimg::keyESC).
Example
CImgDisplay disp(400,400);
const unsigned int key_seq[] = { cimg::keyCTRLLEFT, cimg::keyD };
while (!disp.is_closed()) {
  if (disp.is_key_sequence(key_seq,2)) { ... }  // Test for the 'CTRL+D' keyboard event.
  disp.wait();
}
Definition at line 7589 of file CImg.h.
key()
unsigned int cimg_library_suffixed::CImgDisplay::key (const unsigned int pos = 0) const inline
Return one entry from the pressed keys history.
Parameters
pos Indice to read from the pressed keys history (indice 0 corresponds to latest entry).
Returns
Keycode of a pressed key or 0 for a released key.
Note
Each CImgDisplay stores a history of the pressed keys in a buffer of size 128. When a new key is pressed, its keycode is stored in the pressed keys history. When a key is released, 0 is put instead. This means that up to the 64 last pressed keys may be read from the pressed keys history. When a new value is stored, the pressed keys history is shifted so that the latest entry is always stored at position 0.
Keycode constants are defined in the cimg namespace and are architecture-dependent. Use them to ensure your code stay portable (see cimg::keyESC).
Definition at line 7853 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
keycode()
static unsigned int cimg_library_suffixed::CImgDisplay::keycode (const char *const keycode) inline static
Return keycode corresponding to the specified string.
Note
Keycode constants are defined in the cimg namespace and are architecture-dependent. Use them to ensure your code stay portable (see cimg::keyESC).
Example
const unsigned int keyTAB = CImgDisplay::keycode("TAB");  // Return cimg::keyTAB.
Definition at line 7883 of file CImg.h.
mouse_x()
int cimg_library_suffixed::CImgDisplay::mouse_x () const inline
Return X-coordinate of the mouse pointer.
Note
If the mouse pointer is outside window area, -1 is returned.
Otherwise, the returned value is in the range [0,width()-1].
Definition at line 7767 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
mouse_y()
int cimg_library_suffixed::CImgDisplay::mouse_y () const inline
Return Y-coordinate of the mouse pointer.
Note
If the mouse pointer is outside window area, -1 is returned.
Otherwise, the returned value is in the range [0,height()-1].
Definition at line 7777 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
move()
CImgDisplay& cimg_library_suffixed::CImgDisplay::move (const int pos_x, const int pos_y) inline
Move associated window to a new location.
Parameters
pos_x X-coordinate of the new window location.
pos_y Y-coordinate of the new window location.
Note
Depending on the window manager behavior, this method may not succeed (no exceptions are thrown nevertheless).
Definition at line 8009 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog().
normalization()
unsigned int cimg_library_suffixed::CImgDisplay::normalization () const inline
Return normalization type of the display.
The normalization type tells about how the values of an input image are normalized by the CImgDisplay to be correctly displayed. The range of values for pixels displayed on screen is [0,255]. If the range of values of the data to display is different, a normalization may be required for displaying the data in a correct way. The normalization type can be one of:
0: Value normalization is disabled. It is then assumed that all input data to be displayed by the CImgDisplay instance have values in range [0,255].
1: Value normalization is always performed (this is the default behavior). Before displaying an input image, its values will be (virtually) stretched in range [0,255], so that the contrast of the displayed pixels will be maximum. Use this mode for images whose minimum and maximum values are not prescribed to known values (e.g. float-valued images). Note that when normalized versions of images are computed for display purposes, the actual values of these images are not modified.
2: Value normalization is performed once (on the first image display), then the same normalization coefficients are kept for next displayed frames.
3: Value normalization depends on the pixel type of the data to display. For integer pixel types, the normalization is done regarding the minimum/maximum values of the type (no normalization occurs then for unsigned char). For float-valued pixel types, the normalization is done regarding the minimum/maximum value of the image data instead.
Definition at line 7714 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
operator bool()
cimg_library_suffixed::CImgDisplay::operator bool () const inline
Return false if display is empty, true otherwise.
Note
if (disp) { ... } is equivalent to if (!disp.is_empty()) { ... }.
Definition at line 7394 of file CImg.h.
operator=() [1/3]
template<typename t > CImgDisplay& cimg_library_suffixed::CImgDisplay::operator= (const CImg< t > & img) inline
Display image on associated window.
Note
disp = img is equivalent to disp.display(img).
Definition at line 7369 of file CImg.h.
operator=() [2/3]
template<typename t > CImgDisplay& cimg_library_suffixed::CImgDisplay::operator= (const CImgList< t > & list) inline
Display list of images on associated window.
Note
disp = list is equivalent to disp.display(list).
Definition at line 7378 of file CImg.h.
operator=() [3/3]
CImgDisplay& cimg_library_suffixed::CImgDisplay::operator= (const CImgDisplay & disp) inline
Construct a display as a copy of another one .
Note
Equivalent to assign(const CImgDisplay&).
Definition at line 7386 of file CImg.h.
paint()
CImgDisplay& cimg_library_suffixed::CImgDisplay::paint () inline
Paint internal display buffer on associated window.
Note
Update the content of the associated window with the internal display buffer, e.g. after a render() call.
Should not be used for common CImgDisplay uses, since display() is more useful.
Definition at line 8490 of file CImg.h.
released_key()
unsigned int cimg_library_suffixed::CImgDisplay::released_key (const unsigned int pos = 0) const inline
Return one entry from the released keys history.
Parameters
pos Indice to read from the released keys history (indice 0 corresponds to latest entry).
Returns
Keycode of a released key or 0 for a pressed key.
Note
Each CImgDisplay stores a history of the released keys in a buffer of size 128. When a new key is released, its keycode is stored in the pressed keys history. When a key is pressed, 0 is put instead. This means that up to the 64 last released keys may be read from the released keys history. When a new value is stored, the released keys history is shifted so that the latest entry is always stored at position 0.
Keycode constants are defined in the cimg namespace and are architecture-dependent. Use them to ensure your code stay portable (see cimg::keyESC).
Definition at line 7870 of file CImg.h.
render()
template<typename T > CImgDisplay& cimg_library_suffixed::CImgDisplay::render (const CImg< T > & img) inline
Render image into internal display buffer.
Parameters
img Input image data to render.
Note
Convert image data representation into the internal display buffer (architecture-dependent structure).
The content of the associated window is not modified, until paint() is called.
Should not be used for common CImgDisplay uses, since display() is more useful.
Definition at line 8480 of file CImg.h.
resize() [1/4]
CImgDisplay& cimg_library_suffixed::CImgDisplay::resize (const bool force_redraw = true) inline
Resize display to the size of the associated window.
Parameters
force_redraw Tells if the previous window content must be updated and refreshed as well.
Note
Calling this method ensures that width() and window_width() become equal, as well as height() and window_height().
The associated window is also resized to specified dimensions.
Definition at line 8023 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
resize() [2/4]
CImgDisplay& cimg_library_suffixed::CImgDisplay::resize (const int width, const int height, const bool force_redraw = true) inline
Resize display to the specified size.
Parameters
width Requested display width.
height Requested display height.
force_redraw Tells if the previous window content must be updated and refreshed as well.
Note
The associated window is also resized to specified dimensions.
Definition at line 8037 of file CImg.h.
resize() [3/4]
template<typename T > CImgDisplay& cimg_library_suffixed::CImgDisplay::resize (const CImg< T > & img, const bool force_redraw = true) inline
Resize display to the size of an input image.
Parameters
img Input image to take size from.
force_redraw Tells if the previous window content must be resized and updated as well.
Note
Calling this method ensures that width() and img.width() become equal, as well as height() and img.height().
The associated window is also resized to specified dimensions.
Definition at line 8053 of file CImg.h.
resize() [4/4]
CImgDisplay& cimg_library_suffixed::CImgDisplay::resize (const CImgDisplay & disp, const bool force_redraw = true) inline
Resize display to the size of another CImgDisplay instance.
Parameters
disp Input display to take size from.
force_redraw Tells if the previous window content must be resized and updated as well.
Note
Calling this method ensures that width() and disp.width() become equal, as well as height() and disp.height().
The associated window is also resized to specified dimensions.
Definition at line 8066 of file CImg.h.
screenshot() [1/2]
template<typename T > static void cimg_library_suffixed::CImgDisplay::screenshot (CImg< T > & img) inline static
Take a screenshot.
Parameters
[out] img Output screenshot. Can be empty on input
Definition at line 7254 of file CImg.h.
screenshot() [2/2]
template<typename T > static void cimg_library_suffixed::CImgDisplay::screenshot (const int x0, const int y0, const int x1, const int y1, CImg< T > & img) inline static
Take a snapshot of the current screen content.
Parameters
x0 X-coordinate of the upper left corner.
y0 Y-coordinate of the upper left corner.
x1 X-coordinate of the lower right corner.
y1 Y-coordinate of the lower right corner.
[out] img Output screenshot. Can be empty on input
Definition at line 8504 of file CImg.h.
set_button() [1/2]
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_button () inline
Simulate a mouse button release event.
Note
All mouse buttons are considered released at the same time.
Definition at line 8190 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), flush(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
set_button() [2/2]
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_button (const unsigned int button, const bool is_pressed = true) inline
Simulate a mouse button press or release event.
Parameters
button Buttons event code, where each button is associated to a single bit.
is_pressed Tells if the mouse button is considered as pressed or released.
Definition at line 8206 of file CImg.h.
set_fullscreen()
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_fullscreen (const bool is_fullscreen, const bool force_redraw = true) inline
Enable or disable fullscreen mode.
Parameters
is_fullscreen Tells is the fullscreen mode must be activated or not.
force_redraw Tells if the previous window content must be displayed as well.
Note
When the fullscreen mode is enabled, the associated window fills the entire screen but the size of the current display is not modified.
The screen resolution may be switched to fit the associated window size and ensure it appears the largest as possible. For X-Window (X11) users, the configuration flag cimg_use_xrandr has to be set to allow the screen resolution change (requires the X11 extensions to be enabled).
Definition at line 8141 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
set_key() [1/2]
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_key () inline
Flush all key events.
Note
Make key() to return 0, if called afterwards.
Definition at line 8257 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
set_key() [2/2]
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_key (const unsigned int keycode, const bool is_pressed = true) inline
Simulate a keyboard press/release event.
Parameters
keycode Keycode of the associated key.
is_pressed Tells if the key is considered as pressed or released.
Note
Keycode constants are defined in the cimg namespace and are architecture-dependent. Use them to ensure your code stay portable (see cimg::keyESC).
Definition at line 8288 of file CImg.h.
set_mouse()
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_mouse (const int pos_x, const int pos_y) inline
Move mouse pointer to a specified location.
Note
Depending on the window manager behavior, this method may not succeed (no exceptions are thrown nevertheless).
Definition at line 8180 of file CImg.h.
set_normalization()
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_normalization (const unsigned int normalization) inline
Set normalization type.
Parameters
normalization New normalization mode.
Definition at line 8102 of file CImg.h.
set_title()
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_title (const char *const format, ...) inline
Set title of the associated window.
Parameters
format C-string containing the format of the title, as with std::printf().
Warning
As the first argument is a format string, it is highly recommended to write
disp.set_title("%s",window_title);
instead of
disp.set_title(window_title);
if window_title can be arbitrary, to prevent nasty memory access.
Definition at line 8123 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), and cimg_library_suffixed::CImgList< charT >::get_select().
set_wheel() [1/2]
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_wheel () inline
Flush all mouse wheel events.
Note
Make wheel() to return 0, if called afterwards.
Definition at line 8224 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), flush(), cimg_library_suffixed::CImg< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
set_wheel() [2/2]
CImgDisplay& cimg_library_suffixed::CImgDisplay::set_wheel (const int amplitude) inline
Simulate a wheel event.
Parameters
amplitude Amplitude of the wheel scrolling to simulate.
Note
Make wheel() to return amplitude, if called afterwards.
Definition at line 8240 of file CImg.h.
show()
CImgDisplay& cimg_library_suffixed::CImgDisplay::show () inline
Show (closed) associated window on the screen.
Note
Force the associated window of a display to be visible on the screen, even if it has been closed before.
Using show() on a visible display does nothing.
Definition at line 7986 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
show_mouse()
CImgDisplay& cimg_library_suffixed::CImgDisplay::show_mouse () inline
Show mouse pointer.
Note
Depending on the window manager behavior, this method may not succeed (no exceptions are thrown nevertheless).
Definition at line 8162 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_select().
snapshot()
template<typename T > const CImgDisplay& cimg_library_suffixed::CImgDisplay::snapshot (CImg< T > & img) const inline
Take a snapshot of the associated window content.
Parameters
[out] img Output snapshot. Can be empty on input.
Definition at line 8514 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::assign(), cimg_library_suffixed::CImg< charT >::CImg(), and cimg_library_suffixed::CImg< charT >::operator=().
title()
const char* cimg_library_suffixed::CImgDisplay::title () const inline
Return title of the associated window as a C-string.
Note
Window title may be not visible, depending on the used window manager or if the current display is in fullscreen mode.
Definition at line 7723 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), and cimg_library_suffixed::CImgList< charT >::display().
toggle_fullscreen()
CImgDisplay& cimg_library_suffixed::CImgDisplay::toggle_fullscreen (const bool force_redraw = true) inline
Toggle fullscreen mode.
Parameters
force_redraw Tells if the previous window content must be displayed as well.
Note
Enable fullscreen mode if it was not enabled, and disable it otherwise.
Definition at line 8153 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display_object3d().
wait()
CImgDisplay& cimg_library_suffixed::CImgDisplay::wait (const unsigned int milliseconds) inline
Wait for a given number of milliseconds since the last call to wait().
Parameters
milliseconds Number of milliseconds to wait for.
Note
Similar to cimg::wait().
Definition at line 8366 of file CImg.h.
wheel()
int cimg_library_suffixed::CImgDisplay::wheel () const inline
Return current state of the mouse wheel.
Note
The returned value can be positive or negative depending on whether the mouse wheel has been scrolled forward or backward.
Scrolling the wheel forward add 1 to the wheel value.
Scrolling the wheel backward substract 1 to the wheel value.
The returned value cumulates the number of forward of backward scrolls since the creation of the display, or since the last reset of the wheel value (using set_wheel()). It is strongly recommended to quickly reset the wheel counter when an action has been performed regarding the current wheel value. Otherwise, the returned wheel value may be for instance 0 despite the fact that many scrolls have been done (as many in forward as in backward directions).
Example
CImgDisplay disp(400,400);
while (!disp.is_closed()) {
  if (disp.wheel()) {
    int counter = disp.wheel();  // Read the state of the mouse wheel.
    ...                          // Do what you want with 'counter'.
    disp.set_wheel();            // Reset the wheel value to 0.
  }
  disp.wait();
}
Definition at line 7836 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), and cimg_library_suffixed::CImg< charT >::get_select_graph().
width()
int cimg_library_suffixed::CImgDisplay::width () const inline
Return display width.
Note
The width of the display (i.e. the width of the pixel data buffer associated to the CImgDisplay instance) may be different from the actual width of the associated window.
Definition at line 7678 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::get_resize(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), cimg_library_suffixed::CImg< charT >::get_select_graph(), resize(), and cimg_library_suffixed::CImg< charT >::resize().
window_height()
int cimg_library_suffixed::CImgDisplay::window_height () const inline
Return height of the associated window.
Note
The height of the display (i.e. the height of the pixel data buffer associated to the CImgDisplay instance) may be different from the actual height of the associated window.
Definition at line 7741 of file CImg.h.
window_width()
int cimg_library_suffixed::CImgDisplay::window_width () const inline
Return width of the associated window.
Note
The width of the display (i.e. the width of the pixel data buffer associated to the CImgDisplay instance) may be different from the actual width of the associated window.
Definition at line 7732 of file CImg.h.
window_x()
int cimg_library_suffixed::CImgDisplay::window_x () const inline
Return X-coordinate of the associated window.
Note
The returned coordinate corresponds to the location of the upper-left corner of the associated window.
Definition at line 7749 of file CImg.h.
window_y()
int cimg_library_suffixed::CImgDisplay::window_y () const inline
Return Y-coordinate of the associated window.
Note
The returned coordinate corresponds to the location of the upper-left corner of the associated window.
Definition at line 7757 of file CImg.h.
The documentation for this struct was generated from the following file:
deps/CImg.h