jubilant-funicular: nta::utils::Path Class Reference
nta::utils::Path Class Reference
A (case-sensitive) Path in a file system.
#include <Path.h>
Classes
class iterator
class SetBeginEndKey
Key unlocking the set_{begin,end}() "private" functions of class Path::iterator.
Public Member Functions
Path ()
Path (crstring path)
Path (const char *p)
Path & resolve ()
Converts this to an absolute path and returns it.
Path parent () const
Returns the folder containing this path.
std::string file_name (bool extension=true) const
bool exists () const
bool empty () const
bool is_empty () const
bool is_file () const
bool is_directory () const
bool is_folder () const
bool is_relative () const
bool is_absolute () const
const std::string & to_string ()
Path & operator= (const char *p)
Path & operator= (crstring p)
bool operator== (const char *p) const
bool operator== (const Path &p) const
bool operator== (crstring p) const
Path operator+ (const char *p) const
Path & operator+= (const char *p)
Path operator+ (crstring p) const
Path & operator+= (crstring p)
Path operator+ (const Path &p) const
Path & operator+= (const Path &p)
Path::iterator begin () const
Path::iterator end () const
Static Public Member Functions
static Path cwd ()
Returns Path representing the current working directory.
Private Attributes
std::string m_path
Friends
std::ostream & operator<< (std::ostream &out, const Path &path)
Detailed Description
A (case-sensitive) Path in a file system.
Definition at line 17 of file Path.h.
Constructor & Destructor Documentation
Path() [1/3]
nta::utils::Path::Path () inline
Definition at line 121 of file Path.h.
Referenced by cwd(), and operator+().
Path() [2/3]
nta::utils::Path::Path (crstring path)
Definition at line 15 of file Path.cpp.
Path() [3/3]
nta::utils::Path::Path (const char * p) inline
Definition at line 123 of file Path.h.
Member Function Documentation
begin()
Path::iterator nta::utils::Path::begin () const
Definition at line 95 of file Path.cpp.
Referenced by operator+=().
cwd()
Path nta::utils::Path::cwd () static
Returns Path representing the current working directory.
Definition at line 18 of file Path.cpp.
Referenced by Path(), and resolve().
empty()
bool nta::utils::Path::empty () const inline
Definition at line 138 of file Path.h.
end()
Path::iterator nta::utils::Path::end () const
Definition at line 100 of file Path.cpp.
Referenced by file_name(), and operator+=().
exists()
bool nta::utils::Path::exists () const
Definition at line 60 of file Path.cpp.
Referenced by is_directory(), is_file(), Path(), nta::utils::Path::iterator::set_begin(), and nta::utils::Path::iterator::set_end().
file_name()
std::string nta::utils::Path::file_name (bool extension = true) const
Returns the last componenet (file or directory) name of the path
When extension=false, the extension is dropped from the returned string
Definition at line 53 of file Path.cpp.
Referenced by Path().
is_absolute()
bool nta::utils::Path::is_absolute () const
Definition at line 81 of file Path.cpp.
Referenced by is_relative().
is_directory()
bool nta::utils::Path::is_directory () const
Definition at line 67 of file Path.cpp.
Referenced by is_empty(), is_file(), is_folder(), and nta::utils::Path::iterator::set_begin().
is_empty()
bool nta::utils::Path::is_empty () const inline
Definition at line 139 of file Path.h.
Referenced by empty(), and resolve().
is_file()
bool nta::utils::Path::is_file () const
Definition at line 63 of file Path.cpp.
Referenced by is_empty(), nta::utils::Path::iterator::operator*(), nta::utils::Path::iterator::operator++(), nta::utils::Path::iterator::operator==(), and nta::utils::Path::iterator::set_end().
is_folder()
bool nta::utils::Path::is_folder () const inline
Definition at line 142 of file Path.h.
is_relative()
bool nta::utils::Path::is_relative () const inline
Definition at line 143 of file Path.h.
Referenced by resolve().
operator+() [1/3]
Path nta::utils::Path::operator+ (const char * p) const
Definition at line 90 of file Path.cpp.
Referenced by operator==().
operator+() [2/3]
Path nta::utils::Path::operator+ (crstring p) const inline
Definition at line 156 of file Path.h.
Referenced by operator+().
operator+() [3/3]
Path nta::utils::Path::operator+ (const Path & p) const inline
Definition at line 158 of file Path.h.
Referenced by operator+().
operator+=() [1/3]
Path& nta::utils::Path::operator+= (const char * p) inline
Definition at line 155 of file Path.h.
operator+=() [2/3]
Path& nta::utils::Path::operator+= (crstring p) inline
Definition at line 157 of file Path.h.
Referenced by operator+=().
operator+=() [3/3]
Path& nta::utils::Path::operator+= (const Path & p) inline
Definition at line 159 of file Path.h.
Referenced by operator+=().
operator=() [1/2]
Path& nta::utils::Path::operator= (const char * p) inline
Definition at line 148 of file Path.h.
operator=() [2/2]
Path& nta::utils::Path::operator= (crstring p) inline
Definition at line 149 of file Path.h.
Referenced by operator=().
operator==() [1/3]
bool nta::utils::Path::operator== (const char * p) const
Definition at line 87 of file Path.cpp.
Referenced by nta::utils::Path::iterator::operator!=(), and operator=().
operator==() [2/3]
bool nta::utils::Path::operator== (const Path & p) const inline
Definition at line 151 of file Path.h.
operator==() [3/3]
bool nta::utils::Path::operator== (crstring p) const inline
Definition at line 152 of file Path.h.
Referenced by operator==().
parent()
Path nta::utils::Path::parent () const
Returns the folder containing this path.
Todo:
Make work for relative paths
Definition at line 45 of file Path.cpp.
Referenced by Path().
resolve()
Path & nta::utils::Path::resolve ()
Converts this to an absolute path and returns it.
Definition at line 27 of file Path.cpp.
Referenced by Path().
to_string()
const std::string& nta::utils::Path::to_string () inline
Definition at line 146 of file Path.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Path & path) friend
Definition at line 106 of file Path.cpp.
Referenced by operator+=().
Member Data Documentation
m_path
std::string nta::utils::Path::m_path private
Definition at line 119 of file Path.h.
Referenced by exists(), file_name(), is_absolute(), is_directory(), operator+(), operator+=(), nta::utils::operator<<(), operator==(), parent(), Path(), resolve(), nta::utils::Path::iterator::set_begin(), and to_string().
The documentation for this class was generated from the following files:
include/nta/Path.h
src/Path.cpp