jubilant-funicular: nta::ECS Class Reference
nta::ECS Class Reference
#include <ECS.h>
Public Member Functions
ECS ()
~ECS ()
Entity gen_entity ()
Generates a new Entity, returning its ID.
void gen_entities (std::size_t num, Entity *ids)
Generates several entities, storing their IDs in ids.
bool delete_entity (Entity id)
template<typename T >
bool add_component (T cmpn, Entity entity)
bool delete_component (Component *cmpn)
template<typename T >
void delete_components (Entity entity)
template<typename T >
bool has_component (Entity entity) const
Returns true if the given Entity has a Component of type T.
bool does_entity_exist (Entity entity) const
Returns true if the given Entity exists.
Entity get_owner (Component *cmpn) const
Returns the Entity associated to this Component.
template<typename T >
std::vector< T * > & get_component_list ()
Returns a list of all components of the given type.
template<typename T >
std::vector< T * > & get_component_list (Entity entity)
Returna a list of all component of a given type belonging to entity.
ComponentLists & get_components (Entity entity)
ComponentLists & get_siblings (Component *cmpn)
Returns the lists of components with the same owner as this one.
template<typename T >
T & get_component (Entity entity) const
Returns the (first) Component of the given type associated to the given Entity.
template<typename T >
T & get_sibling (Component *cmpn) const
Returns the (first) Component of the given type with the same owner as cmpn.
void broadcast (const Message &message, Component *cmpn)
Forwards message to all Components associated to the same Entity as cmpn.
void broadcast (const Message &message, Entity entity)
Forwards message to all Components belonging to entity.
template<typename T >
void broadcast (const Message &message)
Forwards message to all Components of the given type.
void clear ()
Removes all entites and components from this system.
Private Attributes
EntitySet m_entity_set
All Entities in the system.
ComponentSet m_component_set
All components in the system.
EntityComponentMap m_components_map
Map associating each Entity to its (linked) list of components.
ComponentEntityMap m_entity_map
Map associating each component to its entity.
ComponentListMap m_list_map
Map associating each component to the lists (roughly, types) it belongs to.
ComponentLists m_component_lists
utils::IDFactory< Entity > m_entity_gen
Responsible for creating unique IDs for the Entities.
Detailed Description
Container class representing a complete Entity-Component System
Manages creation of Entities and grouping of Components
Todo:
Make this class's implementation less complicated
Definition at line 30 of file ECS.h.
Constructor & Destructor Documentation
ECS()
nta::ECS::ECS () inline
Definition at line 50 of file ECS.h.
~ECS()
nta::ECS::~ECS () inline
Definition at line 51 of file ECS.h.
Member Function Documentation
add_component()
template<typename T > bool nta::ECS::add_component (T cmpn, Entity entity)
Adds the given Component to the given Entity.
T should be a concrete type, not a pointer type
Returns false on failure
Definition at line 120 of file ECS.h.
Referenced by ~ECS().
broadcast() [1/3]
void nta::ECS::broadcast (const Message & message, Component * cmpn)
Forwards message to all Components associated to the same Entity as cmpn.
Definition at line 62 of file ECS.cpp.
Referenced by get_sibling(), and nta::Component::send().
broadcast() [2/3]
void nta::ECS::broadcast (const Message & message, Entity entity)
Forwards message to all Components belonging to entity.
Definition at line 66 of file ECS.cpp.
broadcast() [3/3]
template<typename T > void nta::ECS::broadcast (const Message & message)
Forwards message to all Components of the given type.
Definition at line 163 of file ECS.h.
clear()
void nta::ECS::clear ()
Removes all entites and components from this system.
Definition at line 75 of file ECS.cpp.
Referenced by get_sibling(), and ~ECS().
delete_component()
bool nta::ECS::delete_component (Component * cmpn)
Attempts to delete the given Component
Returns true on success
Definition at line 29 of file ECS.cpp.
Referenced by delete_components(), and ~ECS().
delete_components()
template<typename T > void nta::ECS::delete_components (Entity entity)
Deletes all componenets of the given type from the given entity
if entity == NTA_INVALID_ID, then deletes all components of that type from all entities
Definition at line 133 of file ECS.h.
Referenced by ~ECS().
delete_entity()
bool nta::ECS::delete_entity (Entity id)
Attempts to delete Entity with given id.
Returns true on success
Definition at line 18 of file ECS.cpp.
Referenced by ~ECS().
does_entity_exist()
bool nta::ECS::does_entity_exist (Entity entity) const
Returns true if the given Entity exists.
Definition at line 49 of file ECS.cpp.
Referenced by delete_components(), get_component_list(), has_component(), and ~ECS().
gen_entities()
void nta::ECS::gen_entities (std::size_t num, Entity * ids)
Generates several entities, storing their IDs in ids.
Definition at line 15 of file ECS.cpp.
Referenced by ~ECS().
gen_entity()
Entity nta::ECS::gen_entity ()
Generates a new Entity, returning its ID.
Definition at line 10 of file ECS.cpp.
Referenced by ~ECS().
get_component()
template<typename T > T & nta::ECS::get_component (Entity entity) const
Returns the (first) Component of the given type associated to the given Entity.
Definition at line 156 of file ECS.h.
Referenced by get_siblings().
get_component_list() [1/2]
template<typename T > std::vector< T * > & nta::ECS::get_component_list ()
Returns a list of all components of the given type.
Definition at line 147 of file ECS.h.
Referenced by ~ECS().
get_component_list() [2/2]
template<typename T > std::vector< T * > & nta::ECS::get_component_list (Entity entity)
Returna a list of all component of a given type belonging to entity.
Definition at line 151 of file ECS.h.
get_components()
ComponentLists & nta::ECS::get_components (Entity entity)
Returns the lists of components associated to the given Entity
Crashes if entity does not exist
Todo:
Make return type an Optional
Definition at line 56 of file ECS.cpp.
Referenced by get_siblings(), and ~ECS().
get_owner()
Entity nta::ECS::get_owner (Component * cmpn) const
Returns the Entity associated to this Component.
Definition at line 52 of file ECS.cpp.
Referenced by get_sibling(), get_siblings(), and ~ECS().
get_sibling()
template<typename T > T& nta::ECS::get_sibling (Component * cmpn) const inline
Returns the (first) Component of the given type with the same owner as cmpn.
Definition at line 106 of file ECS.h.
get_siblings()
ComponentLists& nta::ECS::get_siblings (Component * cmpn) inline
Returns the lists of components with the same owner as this one.
Definition at line 100 of file ECS.h.
has_component()
template<typename T > bool nta::ECS::has_component (Entity entity) const
Returns true if the given Entity has a Component of type T.
Definition at line 141 of file ECS.h.
Referenced by ~ECS().
Member Data Documentation
m_component_lists
ComponentLists nta::ECS::m_component_lists private
Components are organized into several lists for convenience
e.g. all GraphicsComponents may be in one list that's looped over during rendering.
Definition at line 46 of file ECS.h.
Referenced by add_component(), broadcast(), and get_component_list().
m_component_set
ComponentSet nta::ECS::m_component_set private
All components in the system.
Definition at line 35 of file ECS.h.
Referenced by add_component().
m_components_map
EntityComponentMap nta::ECS::m_components_map private
Map associating each Entity to its (linked) list of components.
Definition at line 37 of file ECS.h.
Referenced by add_component(), delete_components(), get_component(), get_component_list(), and has_component().
m_entity_gen
utils::IDFactory<Entity> nta::ECS::m_entity_gen private
Responsible for creating unique IDs for the Entities.
Definition at line 48 of file ECS.h.
m_entity_map
ComponentEntityMap nta::ECS::m_entity_map private
Map associating each component to its entity.
Definition at line 39 of file ECS.h.
Referenced by add_component().
m_entity_set
EntitySet nta::ECS::m_entity_set private
All Entities in the system.
Definition at line 33 of file ECS.h.
Referenced by add_component().
m_list_map
ComponentListMap nta::ECS::m_list_map private
Map associating each component to the lists (roughly, types) it belongs to.
Definition at line 41 of file ECS.h.
Referenced by add_component().
The documentation for this class was generated from the following files:
include/nta/ECS.h
src/ECS.cpp