jubilant-funicular: GLM_GTX_extented_min_max
GLM_GTX_extented_min_max
Experimental extensions
Functions
template<typename T >
GLM_FUNC_DECL T glm::min (T const &x, T const &y, T const &z)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, C< T > const &y, C< T > const &z)
template<typename T >
GLM_FUNC_DECL T glm::min (T const &x, T const &y, T const &z, T const &w)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z, typename C< T >::T const &w)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::min (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)
template<typename T >
GLM_FUNC_DECL T glm::max (T const &x, T const &y, T const &z)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, C< T > const &y, C< T > const &z)
template<typename T >
GLM_FUNC_DECL T glm::max (T const &x, T const &y, T const &z, T const &w)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z, typename C< T >::T const &w)
template<typename T , template< typename > class C>
GLM_FUNC_DECL C< T > glm::max (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)
template<typename genType >
GLM_FUNC_DECL genType glm::fmin (genType x, genType y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fmin (vec< L, T, Q > const &x, T y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fmin (vec< L, T, Q > const &x, vec< L, T, Q > const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::fmax (genType x, genType y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fmax (vec< L, T, Q > const &x, T y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fmax (vec< L, T, Q > const &x, vec< L, T, Q > const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::fclamp (genType x, genType minVal, genType maxVal)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fclamp (vec< L, T, Q > const &x, T minVal, T maxVal)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fclamp (vec< L, T, Q > const &x, vec< L, T, Q > const &minVal, vec< L, T, Q > const &maxVal)
Detailed Description
Include <glm/gtx/extented_min_max.hpp> to use the features of this extension.
Min and max functions for 3 to 4 parameters.
Function Documentation
fclamp() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::fclamp (genType x, genType minVal, genType maxVal)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns min(max(x, minVal), maxVal) for each component in x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
genType Floating-point scalar or vector types.
See also
gtx_extented_min_max
Definition at line 202 of file extended_min_max.inl.
fclamp() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fclamp (vec< L, T, Q > const & x, T minVal, T maxVal)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns min(max(x, minVal), maxVal) for each component in x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
gtx_extented_min_max
Definition at line 209 of file extended_min_max.inl.
fclamp() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fclamp (vec< L, T, Q > const & x, vec< L, T, Q > const & minVal, vec< L, T, Q > const & maxVal)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns min(max(x, minVal), maxVal) for each component in x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
gtx_extented_min_max
Definition at line 215 of file extended_min_max.inl.
fmax() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::fmax (genType x, genType y)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns y if x < y; otherwise, it returns x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
genType Floating-point; scalar or vector types.
See also
gtx_extented_min_max
std::fmax documentation
Definition at line 175 of file extended_min_max.inl.
fmax() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fmax (vec< L, T, Q > const & x, T y)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns y if x < y; otherwise, it returns x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
gtx_extented_min_max
std::fmax documentation
Definition at line 189 of file extended_min_max.inl.
fmax() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fmax (vec< L, T, Q > const & x, vec< L, T, Q > const & y)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns y if x < y; otherwise, it returns x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
gtx_extented_min_max
std::fmax documentation
Definition at line 195 of file extended_min_max.inl.
fmin() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::fmin (genType x, genType y)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns y if y < x; otherwise, it returns x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
gtx_extented_min_max
Definition at line 145 of file extended_min_max.inl.
fmin() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fmin (vec< L, T, Q > const & x, T y)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns y if y < x; otherwise, it returns x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
gtx_extented_min_max
std::fmin documentation
Definition at line 159 of file extended_min_max.inl.
fmin() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fmin (vec< L, T, Q > const & x, vec< L, T, Q > const & y)
#include <deps/glm/gtx/extended_min_max.hpp>
Returns y if y < x; otherwise, it returns x. If one of the two arguments is NaN, the value of the other argument is returned.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
gtx_extented_min_max
std::fmin documentation
Definition at line 165 of file extended_min_max.inl.
Referenced by glm::max().
max() [1/6]
template<typename T > GLM_FUNC_DECL T glm::max (T const & x, T const & y, T const & z)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the maximum component-wise values of 3 inputs
See also
gtx_extented_min_max
Definition at line 74 of file extended_min_max.inl.
max() [2/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the maximum component-wise values of 3 inputs
See also
gtx_extented_min_max
Definition at line 84 of file extended_min_max.inl.
max() [3/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, C< T > const & y, C< T > const & z)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the maximum component-wise values of 3 inputs
See also
gtx_extented_min_max
Definition at line 95 of file extended_min_max.inl.
max() [4/6]
template<typename T > GLM_FUNC_DECL T glm::max (T const & x, T const & y, T const & z, T const & w)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the maximum component-wise values of 4 inputs
See also
gtx_extented_min_max
Definition at line 106 of file extended_min_max.inl.
max() [5/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z, typename C< T >::T const & w)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the maximum component-wise values of 4 inputs
See also
gtx_extented_min_max
Definition at line 118 of file extended_min_max.inl.
max() [6/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the maximum component-wise values of 4 inputs
See also
gtx_extented_min_max
Definition at line 130 of file extended_min_max.inl.
Referenced by glm::max().
min() [1/6]
template<typename T > GLM_FUNC_DECL T glm::min (T const & x, T const & y, T const & z)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the minimum component-wise values of 3 inputs
See also
gtx_extented_min_max
Definition at line 7 of file extended_min_max.inl.
min() [2/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the minimum component-wise values of 3 inputs
See also
gtx_extented_min_max
Definition at line 17 of file extended_min_max.inl.
min() [3/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, C< T > const & y, C< T > const & z)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the minimum component-wise values of 3 inputs
See also
gtx_extented_min_max
Definition at line 28 of file extended_min_max.inl.
min() [4/6]
template<typename T > GLM_FUNC_DECL T glm::min (T const & x, T const & y, T const & z, T const & w)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the minimum component-wise values of 4 inputs
See also
gtx_extented_min_max
Definition at line 39 of file extended_min_max.inl.
min() [5/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z, typename C< T >::T const & w)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the minimum component-wise values of 4 inputs
See also
gtx_extented_min_max
Definition at line 51 of file extended_min_max.inl.
min() [6/6]
template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w)
#include <deps/glm/gtx/extended_min_max.hpp>
Return the minimum component-wise values of 4 inputs
See also
gtx_extented_min_max
Definition at line 63 of file extended_min_max.inl.
Referenced by glm::min().