jubilant-funicular: nta::Random Class Reference
nta::Random Class Reference
Used for generating random numbers.
#include <Random.h>
Static Public Member Functions
static void init ()
initializes random number generation
static bool randBool ()
randomly returns true or false
static long randInt (long min, long max)
returns a random int in the specified range exclusive (uniform distribution)
static long randInt (long max)
static long randInt ()
static float randFloat (float min, float max)
returns a random float in the specified range (uniform distribution)
static float randFloat (float max)
static float randFloat ()
static float randGaussian (float mean, float sd)
returns a random float using the specified distribution
static glm::vec3 randRGB ()
returns a random color
static glm::vec4 randRGBA ()
static glm::vec2 randVec2 (float min, float max)
returna a random vector
static std::default_random_engine getRNG ()
returns the random number generator
Static Private Attributes
static std::default_random_engine m_generator
Detailed Description
Used for generating random numbers.
Definition at line 14 of file Random.h.
Member Function Documentation
getRNG()
static std::default_random_engine nta::Random::getRNG () inline static
returns the random number generator
Definition at line 38 of file Random.h.
init()
void nta::Random::init () static
initializes random number generation
Definition at line 8 of file Random.cpp.
Referenced by nta::init().
randBool()
static bool nta::Random::randBool () inline static
randomly returns true or false
Definition at line 21 of file Random.h.
randFloat() [1/3]
float nta::Random::randFloat (float min, float max) static
returns a random float in the specified range (uniform distribution)
Definition at line 16 of file Random.cpp.
randFloat() [2/3]
static float nta::Random::randFloat (float max) inline static
Definition at line 28 of file Random.h.
Referenced by randFloat().
randFloat() [3/3]
static float nta::Random::randFloat () inline static
Definition at line 29 of file Random.h.
Referenced by randFloat(), randInt(), randRGB(), randRGBA(), and randVec2().
randGaussian()
float nta::Random::randGaussian (float mean, float sd) static
returns a random float using the specified distribution
Definition at line 19 of file Random.cpp.
Referenced by randFloat().
randInt() [1/3]
long nta::Random::randInt (long min, long max) static
returns a random int in the specified range exclusive (uniform distribution)
Definition at line 12 of file Random.cpp.
randInt() [2/3]
static long nta::Random::randInt (long max) inline static
Definition at line 24 of file Random.h.
Referenced by randInt().
randInt() [3/3]
static long nta::Random::randInt () inline static
Definition at line 25 of file Random.h.
Referenced by nta::FontMap::addRect(), randBool(), and randInt().
randRGB()
static glm::vec3 nta::Random::randRGB () inline static
returns a random color
Definition at line 33 of file Random.h.
randRGBA()
static glm::vec4 nta::Random::randRGBA () inline static
Definition at line 34 of file Random.h.
randVec2()
static glm::vec2 nta::Random::randVec2 (float min, float max) inline static
returna a random vector
Definition at line 36 of file Random.h.
Member Data Documentation
m_generator
std::default_random_engine nta::Random::m_generator static private
Definition at line 16 of file Random.h.
Referenced by getRNG(), init(), and randGaussian().
The documentation for this class was generated from the following files:
include/nta/Random.h
src/Random.cpp