jubilant-funicular: nta::utils Namespace Reference
nta::utils Namespace Reference
Namespace for classes/functionality not necessarily specific to game/opengl development.
Classes
class IDFactory
Class for generating unique (integral) IDs.
class Json
class JsonNum
struct LinkedNode
A generic linked list.
class Path
A (case-sensitive) Path in a file system.
class Semaphore
class ThreadPool
Collection of threads for running scheduled functions.
Typedefs
typedef std::map< std::string, Json > JsonObject
typedef std::vector< Json > JsonArray
Enumerations
enum JsonNumType { POS_INT, NEG_INT, FLOAT }
The various types a Json number can take.
enum JsonValueType {
STRING = 0, NUMBER = 1, OBJECT = 2, ARRAY = 3,
BOOLEAN = 4, NONE = 5
}
The various Json types.
Functions
std::ostream & operator<< (std::ostream &out, const Path &path)
bool starts_with (crstring str, crstring prefix)
Checks if str starts with prefix.
bool ends_with (crstring str, crstring suffix)
Checks if str ends with suffix.
std::string replace_all (crstring str, crstring o, crstring n)
Replaces all occurences of o in str with n.
std::string replace_all (crstring str, const std::vector< std::vector< std::string >> &os, const std::vector< std::string > &ns)
Replaces all occurences of any string in the ith element of os with the ith element of ns.
std::string trim (crstring str, crstring back_trash=" \\\", crstring front_trash=" \\\")
Removes leading and trailing whitespace.
std::vector< std::string > split (crstring str, char delim)
Splits a string into substrings separated by delim.
glm::vec2 rotate (crvec2 pt, float angle)
Rotates a point (about the origin) by the given angle.
template<class T >
std::string to_string (const T &input, std::size_t precision=0)
converts input to a std::string
template<class T >
bool in_range (T val, T min, T max)
returns whether or not min <= val <= max
Detailed Description
Namespace for classes/functionality not necessarily specific to game/opengl development.
Typedef Documentation
JsonArray
typedef std::vector<Json> nta::utils::JsonArray
Definition at line 16 of file Json.h.
JsonObject
typedef std::map<std::string, Json> nta::utils::JsonObject
Definition at line 14 of file Json.h.
Enumeration Type Documentation
JsonNumType
enum nta::utils::JsonNumType
The various types a Json number can take.
Enumerator
POS_INT
NEG_INT
FLOAT
Definition at line 19 of file Json.h.
JsonValueType
enum nta::utils::JsonValueType
The various Json types.
Enumerator
STRING
NUMBER
OBJECT
ARRAY
BOOLEAN
NONE
Definition at line 84 of file Json.h.
Function Documentation
ends_with()
bool nta::utils::ends_with (crstring str, crstring suffix)
Checks if str ends with suffix.
Definition at line 8 of file utils.cpp.
Referenced by nta::utils::Path::operator+(), and nta::utils::Path::parent().
in_range()
template<class T > bool nta::utils::in_range (T val, T min, T max)
returns whether or not min <= val <= max
Definition at line 39 of file utils.h.
operator<<()
std::ostream & nta::utils::operator<< (std::ostream & out, const Path & path)
Definition at line 106 of file Path.cpp.
replace_all() [1/2]
std::string nta::utils::replace_all (crstring str, crstring o, crstring n)
Replaces all occurences of o in str with n.
Definition at line 11 of file utils.cpp.
Referenced by nta::utils::Path::Path(), and replace_all().
replace_all() [2/2]
std::string nta::utils::replace_all (crstring str, const std::vector< std::vector< std::string >> & os, const std::vector< std::string > & ns)
Replaces all occurences of any string in the ith element of os with the ith element of ns.
Definition at line 21 of file utils.cpp.
rotate()
glm::vec2 nta::utils::rotate (crvec2 pt, float angle)
Rotates a point (about the origin) by the given angle.
Definition at line 48 of file utils.cpp.
Referenced by nta::DebugBatch::addRect(), and nta::Glyph::Glyph().
split()
std::vector< std::string > nta::utils::split (crstring str, char delim)
Splits a string into substrings separated by delim.
Definition at line 39 of file utils.cpp.
Referenced by nta::utils::Path::resolve().
starts_with()
bool nta::utils::starts_with (crstring str, crstring prefix)
Checks if str starts with prefix.
Definition at line 5 of file utils.cpp.
Referenced by nta::utils::Json::parse_tokens().
to_string()
template<class T > std::string nta::utils::to_string (const T & input, std::size_t precision = 0)
converts input to a std::string
Definition at line 28 of file utils.h.
Referenced by nta::ScreenManager::addScreen(), nta::check_error(), nta::Compressor::compress(), nta::Window::createWindow(), nta::ResourceManager::deleteSpriteFont(), nta::ResourceManager::destroy(), nta::utils::JsonNum::dump(), nta::AudioManager::getMusic(), nta::AudioManager::getSoundEffect(), nta::init(), nta::AudioManager::init(), nta::ImageLoader::readImage(), nta::ScreenManager::run(), nta::SpriteFont::SpriteFont(), and nta::ScreenManager::switchScreen().
trim()
std::string nta::utils::trim (crstring str, crstring back_trash = " \t\n\v\f\r\0", crstring front_trash = " \t\n\v\f\r\0")
Removes leading and trailing whitespace.
Definition at line 33 of file utils.cpp.
Referenced by nta::utils::Path::operator==(), and nta::utils::Json::parse().