jubilant-funicular: GLM_GTX_euler_angles
GLM_GTX_euler_angles
Experimental extensions
Functions
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleX (T const &angleX)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleY (T const &angleY)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleZ (T const &angleZ)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleXY (T const &angleX, T const &angleY)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleYX (T const &angleY, T const &angleX)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleXZ (T const &angleX, T const &angleZ)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleZX (T const &angle, T const &angleX)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleYZ (T const &angleY, T const &angleZ)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleZY (T const &angleZ, T const &angleY)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleXYZ (T const &t1, T const &t2, T const &t3)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::eulerAngleYXZ (T const &yaw, T const &pitch, T const &roll)
template<typename T >
GLM_FUNC_DECL mat< 4, 4, T, defaultp > glm::yawPitchRoll (T const &yaw, T const &pitch, T const &roll)
template<typename T >
GLM_FUNC_DECL mat< 2, 2, T, defaultp > glm::orientate2 (T const &angle)
template<typename T >
GLM_FUNC_DECL mat< 3, 3, T, defaultp > glm::orientate3 (T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL mat< 3, 3, T, Q > glm::orientate3 (vec< 3, T, Q > const &angles)
template<typename T , qualifier Q>
GLM_FUNC_DECL mat< 4, 4, T, Q > glm::orientate4 (vec< 3, T, Q > const &angles)
template<typename T >
GLM_FUNC_DECL void glm::extractEulerAngleXYZ (mat< 4, 4, T, defaultp > const &M, T &t1, T &t2, T &t3)
Detailed Description
Include <glm/gtx/euler_angles.hpp> to use the features of this extension.
Build matrices from Euler angles.
Function Documentation
eulerAngleX()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleX (T const & angleX)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle X.
See also
GLM_GTX_euler_angles
Definition at line 10 of file euler_angles.inl.
Referenced by glm::eulerAngleXZ(), and glm::eulerAngleZX().
eulerAngleXY()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleXY (T const & angleX, T const & angleY)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Y).
See also
GLM_GTX_euler_angles
Definition at line 58 of file euler_angles.inl.
eulerAngleXYZ()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleXYZ (T const & t1, T const & t2, T const & t3)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Y * Z).
See also
GLM_GTX_euler_angles
Definition at line 136 of file euler_angles.inl.
eulerAngleXZ()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleXZ (T const & angleX, T const & angleZ)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Z).
See also
GLM_GTX_euler_angles
Definition at line 96 of file euler_angles.inl.
eulerAngleY()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleY (T const & angleY)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle Y.
See also
GLM_GTX_euler_angles
Definition at line 26 of file euler_angles.inl.
Referenced by glm::eulerAngleYZ(), and glm::eulerAngleZY().
eulerAngleYX()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleYX (T const & angleY, T const & angleX)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X).
See also
GLM_GTX_euler_angles
Definition at line 77 of file euler_angles.inl.
eulerAngleYXZ()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleYXZ (T const & yaw, T const & pitch, T const & roll)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
Definition at line 171 of file euler_angles.inl.
eulerAngleYZ()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleYZ (T const & angleY, T const & angleZ)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * Z).
See also
GLM_GTX_euler_angles
Definition at line 116 of file euler_angles.inl.
eulerAngleZ()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleZ (T const & angleZ)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle Z.
See also
GLM_GTX_euler_angles
Definition at line 42 of file euler_angles.inl.
Referenced by glm::eulerAngleXZ(), glm::eulerAngleYZ(), glm::eulerAngleZX(), and glm::eulerAngleZY().
eulerAngleZX()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleZX (T const & angle, T const & angleX)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Z * X).
See also
GLM_GTX_euler_angles
Definition at line 106 of file euler_angles.inl.
eulerAngleZY()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::eulerAngleZY (T const & angleZ, T const & angleY)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Z * Y).
See also
GLM_GTX_euler_angles
Definition at line 126 of file euler_angles.inl.
extractEulerAngleXYZ()
template<typename T > GLM_FUNC_DECL void glm::extractEulerAngleXYZ (mat< 4, 4, T, defaultp > const & M, T & t1, T & t2, T & t3)
#include <deps/glm/gtx/euler_angles.hpp>
Extracts the (X * Y * Z) Euler angles from the rotation matrix M
See also
GLM_GTX_euler_angles
Definition at line 297 of file euler_angles.inl.
orientate2()
template<typename T > GLM_FUNC_DECL mat<2, 2, T, defaultp> glm::orientate2 (T const & angle)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 2D 2 * 2 rotation matrix from an euler angle.
See also
GLM_GTX_euler_angles
Definition at line 241 of file euler_angles.inl.
orientate3() [1/2]
template<typename T > GLM_FUNC_DECL mat<3, 3, T, defaultp> glm::orientate3 (T const & angle)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 2D 4 * 4 homogeneous rotation matrix from an euler angle.
See also
GLM_GTX_euler_angles
Definition at line 258 of file euler_angles.inl.
orientate3() [2/2]
template<typename T , qualifier Q> GLM_FUNC_DECL mat<3, 3, T, Q> glm::orientate3 (vec< 3, T, Q > const & angles)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 3 * 3 rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
Definition at line 280 of file euler_angles.inl.
orientate4()
template<typename T , qualifier Q> GLM_FUNC_DECL mat<4, 4, T, Q> glm::orientate4 (vec< 3, T, Q > const & angles)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
Definition at line 289 of file euler_angles.inl.
yawPitchRoll()
template<typename T > GLM_FUNC_DECL mat<4, 4, T, defaultp> glm::yawPitchRoll (T const & yaw, T const & pitch, T const & roll)
#include <deps/glm/gtx/euler_angles.hpp>
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
Definition at line 206 of file euler_angles.inl.
Referenced by glm::orientate3(), and glm::orientate4().