jubilant-funicular: nta::Logger Class Reference
nta::Logger Class Reference
stores program information in internal and external logs
#include <Logger.h>
Static Public Member Functions
static void createLog ()
creates the log
static void writeToLog (crstring entry)
writes an entry in the log
static Error writeErrorToLog (crstring error, ErrorType type=OTHER)
writes entry in log and then exits program
static void indent (size_t tab_size=TAB_SIZE)
indents entries
static void unindent (size_t tab_size=TAB_SIZE)
unindents entries
Static Private Attributes
static std::ofstream m_logFile
the file that keeps the external log
static size_t m_tabs = 0
static const size_t TAB_SIZE = 4
Detailed Description
stores program information in internal and external logs
Definition at line 10 of file Logger.h.
Member Function Documentation
createLog()
void nta::Logger::createLog () static
creates the log
Definition at line 9 of file Logger.cpp.
Referenced by nta::init().
indent()
void nta::Logger::indent (size_t tab_size = TAB_SIZE) static
indents entries
Definition at line 35 of file Logger.cpp.
Referenced by nta::ScreenManager::addScreen(), nta::SystemManager::destroy(), nta::ResourceManager::destroy(), nta::init(), and nta::ScreenManager::switchScreen().
unindent()
void nta::Logger::unindent (size_t tab_size = TAB_SIZE) static
unindents entries
Definition at line 38 of file Logger.cpp.
Referenced by nta::ScreenManager::addScreen(), nta::SystemManager::destroy(), nta::ResourceManager::destroy(), nta::init(), and nta::ScreenManager::switchScreen().
writeErrorToLog()
Error nta::Logger::writeErrorToLog (crstring error, ErrorType type = OTHER) static
writes entry in log and then exits program
Todo:
Make sure all the code that previously assumed this function always exits still behaves sensibly
Definition at line 23 of file Logger.cpp.
Referenced by nta::Animation2D::Animation2D(), nta::GLSLProgram::compileShader(), nta::Window::createWindow(), nta::ResourceManager::getFile(), nta::AudioManager::getMusic(), nta::AudioManager::getSoundEffect(), nta::GLSLProgram::getUniformLocation(), nta::init(), nta::AudioManager::init(), nta::GLSLProgram::linkShaders(), nta::IOManager::readFileToBuffer(), nta::ImageLoader::readImage(), nta::ScreenManager::run(), nta::SpriteFont::SpriteFont(), and nta::Animation2D::switch_animation().
writeToLog()
void nta::Logger::writeToLog (crstring entry) static
writes an entry in the log
Definition at line 14 of file Logger.cpp.
Referenced by nta::GLSLProgram::addAttribute(), nta::ScreenManager::addScreen(), nta::check_error(), nta::GLSLProgram::compileShader(), nta::GLSLProgram::compileShaders(), nta::Compressor::compress(), createLog(), nta::Compressor::createTree(), nta::Window::createWindow(), nta::ResourceManager::deleteSpriteFont(), nta::ResourceManager::deleteTexture(), nta::SystemManager::destroy(), nta::ScreenManager::destroy(), nta::ResourceManager::destroy(), nta::CallbackManager::destroy(), nta::AudioManager::destroy(), nta::AudioManager::getMusic(), nta::AudioManager::getSoundEffect(), nta::init(), nta::CallbackManager::init(), nta::AudioManager::init(), nta::GLSLProgram::linkShaders(), nta::IOManager::readFileToBuffer(), nta::ImageLoader::readImage(), nta::ScreenManager::run(), nta::SpriteFont::SpriteFont(), nta::ScreenManager::switchScreen(), writeErrorToLog(), and nta::IOManager::writeFileFromBuffer().
Member Data Documentation
m_logFile
std::ofstream nta::Logger::m_logFile static private
the file that keeps the external log
Definition at line 13 of file Logger.h.
Referenced by createLog(), and writeToLog().
m_tabs
size_t nta::Logger::m_tabs = 0 static private
Definition at line 14 of file Logger.h.
Referenced by indent(), unindent(), and writeToLog().
TAB_SIZE
const size_t nta::Logger::TAB_SIZE = 4 static private
Definition at line 15 of file Logger.h.
The documentation for this class was generated from the following files:
include/nta/Logger.h
src/Logger.cpp