jubilant-funicular: nta::Compressor Class Reference
nta::Compressor Class Reference
Static class for compressing byte buffers.
#include <Compressor.h>
Static Public Member Functions
static std::vector< GLubyte > decompress (const std::vector< GLubyte > &data)
decompressed data that was compressed by this class
static std::vector< GLubyte > compress (const std::vector< GLubyte > &data)
compresses a bye buffer
Static Private Member Functions
static std::string toBinary (int num, int numBits=8)
converts number to its binary representation
static int fromBinary (crstring num)
reads a binary number from a string
static void createTree (const std::vector< GLubyte > &data)
creates a Huffman tree from a buffer
Static Private Attributes
static std::map< GLubyte, std::string > m_encodings
the encodings generated from the tree
static HuffmanNode * m_root
the root of the created Huffman tree
Detailed Description
Static class for compressing byte buffers.
Definition at line 53 of file Compressor.h.
Member Function Documentation
compress()
std::vector< GLubyte > nta::Compressor::compress (const std::vector< GLubyte > & data) static
compresses a bye buffer
Definition at line 61 of file Compressor.cpp.
createTree()
void nta::Compressor::createTree (const std::vector< GLubyte > & data) static private
creates a Huffman tree from a buffer
Definition at line 30 of file Compressor.cpp.
Referenced by compress().
decompress()
std::vector< GLubyte > nta::Compressor::decompress (const std::vector< GLubyte > & data) static
decompressed data that was compressed by this class
Definition at line 90 of file Compressor.cpp.
fromBinary()
int nta::Compressor::fromBinary (crstring num) static private
reads a binary number from a string
Definition at line 21 of file Compressor.cpp.
Referenced by compress(), and decompress().
toBinary()
std::string nta::Compressor::toBinary (int num, int numBits = 8) static private
converts number to its binary representation
Definition at line 10 of file Compressor.cpp.
Referenced by compress(), and decompress().
Member Data Documentation
m_encodings
std::map< GLubyte, std::string > nta::Compressor::m_encodings static private
the encodings generated from the tree
Definition at line 62 of file Compressor.h.
Referenced by compress(), and createTree().
m_root
HuffmanNode * nta::Compressor::m_root static private
the root of the created Huffman tree
Definition at line 64 of file Compressor.h.
Referenced by createTree().
The documentation for this class was generated from the following files:
include/nta/Compressor.h
src/Compressor.cpp