jubilant-funicular: nta::utils::Json::iterator< c > Class Template Reference
nta::utils::Json::iterator< c > Class Template Reference
#include <Json.h>
Public Types
using value_type = typename std::conditional< c, const Json, Json >::type
using difference_type = std::ptrdiff_t
using pointer = typename std::conditional< c, const Json *, Json * >::type
using reference = typename std::conditional< c, const Json &, Json & >::type
using iterator_category = std::bidirectional_iterator_tag
Public Member Functions
iterator ()
iterator (pointer json)
reference operator* () const
pointer operator-> () const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator== (const iterator &rhs) const
bool operator!= (const iterator &rhs) const
std::string key ()
reference value ()
void set_begin (SetBeginEndKey _)
void set_end (SetBeginEndKey _)
Private Attributes
pointer m_json
union {
JsonObject::iterator m_obj_iter
JsonArray::iterator m_arr_iter
};
Detailed Description
template<bool c = 0>
class nta::utils::Json::iterator< c >
Custom iterator for looping over Json values
For Arrays: loops over the elements
For Objects: loops over the values (keys accessible via Json::iterator::key())
For None: empty iterator
For anything else (except None): returns the value itself (see tests/utils/json_tests.cpp)
c=0 gives a regular iterator and c=1 gives a const_iterator
Definition at line 117 of file Json.h.
Member Typedef Documentation
difference_type
template<bool c = 0> using nta::utils::Json::iterator< c >::difference_type = std::ptrdiff_t
Definition at line 120 of file Json.h.
iterator_category
template<bool c = 0> using nta::utils::Json::iterator< c >::iterator_category = std::bidirectional_iterator_tag
Definition at line 123 of file Json.h.
pointer
template<bool c = 0> using nta::utils::Json::iterator< c >::pointer = typename std::conditional<c, const Json*, Json*>::type
Definition at line 121 of file Json.h.
reference
template<bool c = 0> using nta::utils::Json::iterator< c >::reference = typename std::conditional<c, const Json&, Json&>::type
Definition at line 122 of file Json.h.
value_type
template<bool c = 0> using nta::utils::Json::iterator< c >::value_type = typename std::conditional<c, const Json, Json>::type
Definition at line 119 of file Json.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<bool c = 0> nta::utils::Json::iterator< c >::iterator () inline
Definition at line 131 of file Json.h.
iterator() [2/2]
template<bool c = 0> nta::utils::Json::iterator< c >::iterator (pointer json) inline
Definition at line 132 of file Json.h.
Member Function Documentation
key()
template<bool c = 0> std::string nta::utils::Json::iterator< c >::key () inline
Definition at line 191 of file Json.h.
operator!=()
template<bool c = 0> bool nta::utils::Json::iterator< c >::operator!= (const iterator< c > & rhs) const inline
Definition at line 187 of file Json.h.
operator*()
template<bool c = 0> reference nta::utils::Json::iterator< c >::operator* () const inline
Definition at line 139 of file Json.h.
operator++() [1/2]
template<bool c = 0> iterator& nta::utils::Json::iterator< c >::operator++ () inline
Definition at line 153 of file Json.h.
operator++() [2/2]
template<bool c = 0> iterator nta::utils::Json::iterator< c >::operator++ (int) inline
Definition at line 161 of file Json.h.
operator--() [1/2]
template<bool c = 0> iterator& nta::utils::Json::iterator< c >::operator-- () inline
Definition at line 166 of file Json.h.
operator--() [2/2]
template<bool c = 0> iterator nta::utils::Json::iterator< c >::operator-- (int) inline
Definition at line 174 of file Json.h.
operator->()
template<bool c = 0> pointer nta::utils::Json::iterator< c >::operator-> () const inline
Definition at line 146 of file Json.h.
operator==()
template<bool c = 0> bool nta::utils::Json::iterator< c >::operator== (const iterator< c > & rhs) const inline
Definition at line 179 of file Json.h.
set_begin()
template<bool c = 0> void nta::utils::Json::iterator< c >::set_begin (SetBeginEndKey _) inline
Definition at line 205 of file Json.h.
Referenced by nta::utils::Json::begin(), and nta::utils::Json::cbegin().
set_end()
template<bool c = 0> void nta::utils::Json::iterator< c >::set_end (SetBeginEndKey _) inline
Definition at line 212 of file Json.h.
Referenced by nta::utils::Json::cend(), and nta::utils::Json::end().
value()
template<bool c = 0> reference nta::utils::Json::iterator< c >::value () inline
Definition at line 197 of file Json.h.
Member Data Documentation
@11
union { ... }
m_json
template<bool c = 0> pointer nta::utils::Json::iterator< c >::m_json private
Definition at line 125 of file Json.h.
Referenced by nta::utils::Json::iterator< c >::operator==().
The documentation for this class was generated from the following file:
include/nta/Json.h