jubilant-funicular: GLM_GTX_rotate_vector
GLM_GTX_rotate_vector
Experimental extensions
Functions
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::slerp (vec< 3, T, Q > const &x, vec< 3, T, Q > const &y, T const &a)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 2, T, Q > glm::rotate (vec< 2, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::rotate (vec< 3, T, Q > const &v, T const &angle, vec< 3, T, Q > const &normal)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, T, Q > glm::rotate (vec< 4, T, Q > const &v, T const &angle, vec< 3, T, Q > const &normal)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::rotateX (vec< 3, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::rotateY (vec< 3, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::rotateZ (vec< 3, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, T, Q > glm::rotateX (vec< 4, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, T, Q > glm::rotateY (vec< 4, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, T, Q > glm::rotateZ (vec< 4, T, Q > const &v, T const &angle)
template<typename T , qualifier Q>
GLM_FUNC_DECL mat< 4, 4, T, Q > glm::orientation (vec< 3, T, Q > const &Normal, vec< 3, T, Q > const &Up)
Detailed Description
Include <glm/gtx/rotate_vector.hpp> to use the features of this extension.
Function to directly rotate a vector
Function Documentation
orientation()
template<typename T , qualifier Q> GLM_FUNC_DECL mat<4, 4, T, Q> glm::orientation (vec< 3, T, Q > const & Normal, vec< 3, T, Q > const & Up)
#include <deps/glm/gtx/rotate_vector.hpp>
Build a rotation matrix from a normal and a up vector. From GLM_GTX_rotate_vector extension.
Definition at line 175 of file rotate_vector.inl.
Referenced by nta::DebugBatch::addLine(), nta::PrimitiveBatch::addPrimitive(), nta::Camera2D::Camera2D(), and nta::Primitive::Primitive().
rotate() [1/3]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<2, T, Q> glm::rotate (vec< 2, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a two dimensional vector. From GLM_GTX_rotate_vector extension.
Definition at line 30 of file rotate_vector.inl.
rotate() [2/3]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::rotate (vec< 3, T, Q > const & v, T const & angle, vec< 3, T, Q > const & normal)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a three dimensional vector around an axis. From GLM_GTX_rotate_vector extension.
Definition at line 46 of file rotate_vector.inl.
rotate() [3/3]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, T, Q> glm::rotate (vec< 4, T, Q > const & v, T const & angle, vec< 3, T, Q > const & normal)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a four dimensional vector around an axis. From GLM_GTX_rotate_vector extension.
Definition at line 68 of file rotate_vector.inl.
Referenced by glm::rotate().
rotateX() [1/2]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::rotateX (vec< 3, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a three dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 79 of file rotate_vector.inl.
rotateX() [2/2]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, T, Q> glm::rotateX (vec< 4, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a four dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 127 of file rotate_vector.inl.
rotateY() [1/2]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::rotateY (vec< 3, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a three dimensional vector around the Y axis. From GLM_GTX_rotate_vector extension.
Definition at line 95 of file rotate_vector.inl.
rotateY() [2/2]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, T, Q> glm::rotateY (vec< 4, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a four dimensional vector around the Y axis. From GLM_GTX_rotate_vector extension.
Definition at line 143 of file rotate_vector.inl.
rotateZ() [1/2]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::rotateZ (vec< 3, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a three dimensional vector around the Z axis. From GLM_GTX_rotate_vector extension.
Definition at line 111 of file rotate_vector.inl.
rotateZ() [2/2]
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, T, Q> glm::rotateZ (vec< 4, T, Q > const & v, T const & angle)
#include <deps/glm/gtx/rotate_vector.hpp>
Rotate a four dimensional vector around the Z axis. From GLM_GTX_rotate_vector extension.
Definition at line 159 of file rotate_vector.inl.
slerp()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::slerp (vec< 3, T, Q > const & x, vec< 3, T, Q > const & y, T const & a)
#include <deps/glm/gtx/rotate_vector.hpp>
Returns Spherical interpolation between two vectors
Parameters
x A first vector
y A second vector
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
See also
GLM_GTX_rotate_vector
Definition at line 8 of file rotate_vector.inl.