jubilant-funicular: nta::Screen Class Reference
nta::Screen Class Reference abstract
Represents a game screen.
#include <Screen.h>
Public Member Functions
Screen (crstring name="nameless")
basic constructor and destructor
virtual ~Screen ()
ScreenState getState () const
returns state of screen
std::string getName () const
gets name of screen
int getEscIndex () const
gets various screen indices
int getXIndex () const
int getNextIndex () const
int getIndex () const
void * getSwitchData () const
gets the switch data (shoudl this require a key?)
void setManager (ScreenManager *manager, SetManagerKey key)
Sets the manager of this screen.
void setIndices (int index, int escIndex, int xIndex, SetIndicesKey key)
sets various screen indices
void setWindow (crstring title, SetWindowKey key)
sets the window to associate with this screen
virtual void render ()=0
renders screen
virtual void update ()=0
updates screen
virtual void handleInput ()
handles user input
virtual void onFocus (const ScreenSwitchInfo &info)
called when the screen becomes active
virtual void offFocus ()
called when the screen is no longer active
virtual void init ()=0
initializes the screen
Protected Attributes
ScreenState m_state = ScreenState::NONE
the state of this screen
Window * m_window = nullptr
the window the screen is rendered in
ScreenManager * m_manager = nullptr
the ScreenManager that owns this screen
std::string m_name
the name of the Screen
int m_nextIndex = -1
the index of the screen to go to when m_state == SWITCH
void * m_switchData = nullptr
data to pass to the new screen (via onFocus) when m_state == SWITCH
Private Attributes
int m_index = -1
the index of this screen in its container
int m_escIndex = -1
the index of the screen to go to when the Esc key is pressed
int m_xIndex = -1
the index of the screen to go to when the window's X button is pressed
Detailed Description
Represents a game screen.
Definition at line 45 of file Screen.h.
Constructor & Destructor Documentation
Screen()
nta::Screen::Screen (crstring name = "nameless")
basic constructor and destructor
Definition at line 14 of file Screen.cpp.
~Screen()
nta::Screen::~Screen () virtual
Definition at line 16 of file Screen.cpp.
Member Function Documentation
getEscIndex()
int nta::Screen::getEscIndex () const
gets various screen indices
Definition at line 24 of file Screen.cpp.
Referenced by nta::ScreenManager::run().
getIndex()
int nta::Screen::getIndex () const
Definition at line 30 of file Screen.cpp.
getName()
std::string nta::Screen::getName () const
gets name of screen
Definition at line 21 of file Screen.cpp.
Referenced by nta::ScreenManager::addScreen().
getNextIndex()
int nta::Screen::getNextIndex () const
Definition at line 33 of file Screen.cpp.
Referenced by nta::ScreenManager::run().
getState()
ScreenState nta::Screen::getState () const
returns state of screen
Definition at line 18 of file Screen.cpp.
Referenced by nta::ScreenManager::run().
getSwitchData()
void * nta::Screen::getSwitchData () const
gets the switch data (shoudl this require a key?)
Definition at line 36 of file Screen.cpp.
getXIndex()
int nta::Screen::getXIndex () const
Definition at line 27 of file Screen.cpp.
Referenced by nta::ScreenManager::run().
handleInput()
void nta::Screen::handleInput () virtual
handles user input
Definition at line 50 of file Screen.cpp.
Referenced by nta::ScreenManager::run().
init()
virtual void nta::Screen::init () pure virtual
initializes the screen
Referenced by nta::ScreenManager::addScreen().
offFocus()
void nta::Screen::offFocus () virtual
called when the screen is no longer active
Definition at line 79 of file Screen.cpp.
Referenced by nta::ScreenManager::switchScreen().
onFocus()
void nta::Screen::onFocus (const ScreenSwitchInfo & info) virtual
called when the screen becomes active
Definition at line 76 of file Screen.cpp.
Referenced by nta::ScreenManager::run(), and nta::ScreenManager::switchScreen().
render()
virtual void nta::Screen::render () pure virtual
renders screen
Referenced by nta::ScreenManager::run().
setIndices()
void nta::Screen::setIndices (int index, int escIndex, int xIndex, SetIndicesKey key)
sets various screen indices
Definition at line 42 of file Screen.cpp.
Referenced by nta::ScreenManager::addScreen().
setManager()
void nta::Screen::setManager (ScreenManager * manager, SetManagerKey key)
Sets the manager of this screen.
Definition at line 39 of file Screen.cpp.
Referenced by nta::ScreenManager::addScreen().
setWindow()
void nta::Screen::setWindow (crstring title, SetWindowKey key)
sets the window to associate with this screen
Definition at line 47 of file Screen.cpp.
Referenced by nta::ScreenManager::addScreen().
update()
virtual void nta::Screen::update () pure virtual
updates screen
Referenced by nta::ScreenManager::run().
Member Data Documentation
m_escIndex
int nta::Screen::m_escIndex = -1 private
the index of the screen to go to when the Esc key is pressed
Definition at line 50 of file Screen.h.
Referenced by getEscIndex(), and setIndices().
m_index
int nta::Screen::m_index = -1 private
the index of this screen in its container
Definition at line 48 of file Screen.h.
Referenced by getIndex(), and setIndices().
m_manager
ScreenManager* nta::Screen::m_manager = nullptr protected
the ScreenManager that owns this screen
Definition at line 59 of file Screen.h.
Referenced by setManager().
m_name
std::string nta::Screen::m_name protected
the name of the Screen
Definition at line 61 of file Screen.h.
Referenced by getName().
m_nextIndex
int nta::Screen::m_nextIndex = -1 protected
the index of the screen to go to when m_state == SWITCH
Definition at line 63 of file Screen.h.
Referenced by getNextIndex().
m_state
ScreenState nta::Screen::m_state = ScreenState::NONE protected
the state of this screen
Definition at line 55 of file Screen.h.
Referenced by getState(), handleInput(), and onFocus().
m_switchData
void* nta::Screen::m_switchData = nullptr protected
data to pass to the new screen (via onFocus) when m_state == SWITCH
Definition at line 65 of file Screen.h.
Referenced by getSwitchData().
m_window
Window* nta::Screen::m_window = nullptr protected
the window the screen is rendered in
Definition at line 57 of file Screen.h.
Referenced by handleInput(), and setWindow().
m_xIndex
int nta::Screen::m_xIndex = -1 private
the index of the screen to go to when the window's X button is pressed
Definition at line 52 of file Screen.h.
Referenced by getXIndex(), and setIndices().
The documentation for this class was generated from the following files:
include/nta/Screen.h
src/Screen.cpp