jubilant-funicular: nta::Vertex2D Struct Reference
nta::Vertex2D Struct Reference
represents a vertex in 2 dimensions
#include <Vertex.h>
Public Member Functions
Vertex2D ()
Initializes an "empty" vertex.
Vertex2D (crvec2 p)
Initializes a white, textureless vertex with given position.
Vertex2D (crvec2 p, crvec4 c)
Initializes textureless, colorful vertex.
Vertex2D (crvec2 p, crvec4 c, crvec2 u, float t=1.0)
Initializes a vertex with everything.
Vertex2D (crvec4 c, crvec2 u, float t=1.0)
Initializes vertex with everything except position.
void setPosition (float x, float y)
sets the position of the vertex
void setColor (float r, float g, float b, float a)
sets the color of the vertex
void setColor (crvec3 c)
void setUV (float u, float v)
sets the uv coordinates of the vertex
Public Attributes
glm::vec2 pos
the vertex's position, color, and uv coordinates, respectively
glm::vec4 color
glm::vec2 uv
float hasTexture
Static Public Attributes
static const VertexAttrib attribs [4]
Detailed Description
represents a vertex in 2 dimensions
Definition at line 20 of file Vertex.h.
Constructor & Destructor Documentation
Vertex2D() [1/5]
nta::Vertex2D::Vertex2D () inline
Initializes an "empty" vertex.
Definition at line 22 of file Vertex.h.
Vertex2D() [2/5]
nta::Vertex2D::Vertex2D (crvec2 p) inline
Initializes a white, textureless vertex with given position.
Definition at line 25 of file Vertex.h.
Vertex2D() [3/5]
nta::Vertex2D::Vertex2D (crvec2 p, crvec4 c) inline
Initializes textureless, colorful vertex.
Definition at line 28 of file Vertex.h.
Vertex2D() [4/5]
nta::Vertex2D::Vertex2D (crvec2 p, crvec4 c, crvec2 u, float t = 1.0) inline
Initializes a vertex with everything.
Definition at line 31 of file Vertex.h.
Vertex2D() [5/5]
nta::Vertex2D::Vertex2D (crvec4 c, crvec2 u, float t = 1.0) inline
Initializes vertex with everything except position.
Definition at line 34 of file Vertex.h.
Member Function Documentation
setColor() [1/2]
void nta::Vertex2D::setColor (float r, float g, float b, float a) inline
sets the color of the vertex
Definition at line 42 of file Vertex.h.
Referenced by nta::Sprite::init().
setColor() [2/2]
void nta::Vertex2D::setColor (crvec3 c) inline
Definition at line 48 of file Vertex.h.
setPosition()
void nta::Vertex2D::setPosition (float x, float y) inline
sets the position of the vertex
Definition at line 37 of file Vertex.h.
Referenced by nta::Glyph::Glyph(), and nta::Sprite::init().
setUV()
void nta::Vertex2D::setUV (float u, float v) inline
sets the uv coordinates of the vertex
Definition at line 55 of file Vertex.h.
Referenced by nta::Glyph::Glyph(), and nta::Sprite::init().
Member Data Documentation
attribs
const VertexAttrib nta::Vertex2D::attribs static
Initial value:
= {
        {2, GL_FLOAT, GL_FALSE, (void*)offsetof(Vertex2D, pos)},
        {4, GL_FLOAT, GL_TRUE,  (void*)offsetof(Vertex2D, color)},
        {2, GL_FLOAT, GL_FALSE, (void*)offsetof(Vertex2D, uv)},
        {1, GL_FLOAT, GL_FALSE, (void*)offsetof(Vertex2D, hasTexture)}
    }
Definition at line 65 of file Vertex.h.
Referenced by nta::PrimitiveBatch::createVertexArrayObject(), nta::SpriteBatch::createVertexArrayObject(), and nta::DebugBatch::init().
color
glm::vec4 nta::Vertex2D::color
Definition at line 61 of file Vertex.h.
Referenced by nta::Glyph::Glyph().
hasTexture
float nta::Vertex2D::hasTexture
Definition at line 63 of file Vertex.h.
Referenced by nta::Glyph::Glyph().
pos
glm::vec2 nta::Vertex2D::pos
the vertex's position, color, and uv coordinates, respectively
Definition at line 60 of file Vertex.h.
Referenced by nta::Glyph::Glyph().
uv
glm::vec2 nta::Vertex2D::uv
Definition at line 62 of file Vertex.h.
The documentation for this struct was generated from the following files:
include/nta/Vertex.h
src/Vertex.cpp