jubilant-funicular: nta::utils::JsonNum Class Reference
nta::utils::JsonNum Class Reference
#include <Json.h>
Public Member Functions
JsonNum ()
By default, this is 0.
JsonNum (uint64_t n)
JsonNum (int64_t n)
JsonNum (double n)
JsonNum (int n)
JsonNumType get_type ()
uint64_t as_uint () const
int64_t as_int () const
double as_float () const
double as_double () const
operator uint64_t () const
operator int64_t () const
operator double () const
bool operator== (const JsonNum &rhs) const
std::string to_string () const
Return string equivalent of stored value.
std::string dump () const
Same as to_string()
Private Attributes
JsonNumType m_type
The type of number.
union {
uint64_t m_pos
Positive integer.
int64_t m_neg
Negative integer.
double m_flt
(Double precision) floating point number
};
Detailed Description
Todo:
add math operators
A Json Number
Definition at line 27 of file Json.h.
Constructor & Destructor Documentation
JsonNum() [1/5]
nta::utils::JsonNum::JsonNum () inline
By default, this is 0.
Definition at line 41 of file Json.h.
JsonNum() [2/5]
nta::utils::JsonNum::JsonNum (uint64_t n) inline
Definition at line 42 of file Json.h.
JsonNum() [3/5]
nta::utils::JsonNum::JsonNum (int64_t n) inline
Definition at line 43 of file Json.h.
JsonNum() [4/5]
nta::utils::JsonNum::JsonNum (double n) inline
Definition at line 44 of file Json.h.
JsonNum() [5/5]
nta::utils::JsonNum::JsonNum (int n) inline
Definition at line 45 of file Json.h.
Member Function Documentation
as_double()
double nta::utils::JsonNum::as_double () const inline
Definition at line 56 of file Json.h.
Referenced by operator double(), nta::utils::Json::operator double(), and nta::utils::Json::operator float().
as_float()
double nta::utils::JsonNum::as_float () const inline
Definition at line 55 of file Json.h.
Referenced by nta::utils::Json::as_float().
as_int()
int64_t nta::utils::JsonNum::as_int () const inline
Definition at line 54 of file Json.h.
Referenced by nta::utils::Json::as_int(), nta::utils::Json::operator int(), operator int64_t(), and nta::utils::Json::operator int64_t().
as_uint()
uint64_t nta::utils::JsonNum::as_uint () const inline
Definition at line 53 of file Json.h.
Referenced by nta::utils::Json::as_uint(), operator uint64_t(), and nta::utils::Json::operator uint64_t().
dump()
std::string nta::utils::JsonNum::dump () const inline
Same as to_string()
Definition at line 74 of file Json.h.
Referenced by nta::utils::Json::is_empty(), and to_string().
get_type()
JsonNumType nta::utils::JsonNum::get_type () inline
Definition at line 52 of file Json.h.
operator double()
nta::utils::JsonNum::operator double () const inline
Definition at line 60 of file Json.h.
operator int64_t()
nta::utils::JsonNum::operator int64_t () const inline
Definition at line 59 of file Json.h.
operator uint64_t()
nta::utils::JsonNum::operator uint64_t () const inline
Definition at line 58 of file Json.h.
operator==()
bool nta::utils::JsonNum::operator== (const JsonNum & rhs) const inline
Definition at line 62 of file Json.h.
Referenced by nta::utils::Json::operator bool(), and nta::utils::Json::iterator< c >::operator!=().
to_string()
std::string nta::utils::JsonNum::to_string () const inline
Return string equivalent of stored value.
Definition at line 72 of file Json.h.
Member Data Documentation
@7
union { ... }
m_type
JsonNumType nta::utils::JsonNum::m_type private
The type of number.
Definition at line 30 of file Json.h.
Referenced by get_type(), nta::utils::Json::get_type(), and operator==().
The documentation for this class was generated from the following file:
include/nta/Json.h