jubilant-funicular: nta::SpriteBatch Class Reference
nta::SpriteBatch Class Reference
#include <SpriteBatch.h>
Public Member Functions
SpriteBatch ()
constructor and destructor
~SpriteBatch ()
void init ()
initializes the batch
void begin ()
begins collection of glyphs for the batch
void end ()
ends collection of glyphs and prepares to render
void addGlyph (crvec4 posRect, crvec4 uvRect, GLuint texture, float depth=0.5, crvec4 color=glm::vec4(1))
void addGlyph (crvec2 corner1, crvec2 corner2, crvec4 uvRect, GLuint texture, float depth=0.5, crvec4 color=glm::vec4(1))
void addGlyph (crvec4 posRect, crvec4 uvRect, GLuint texture, crvec4 color, float angle=0.0f, float depth=0.5)
void addGlyph (crvec2 corner1, crvec2 corner2, crvec4 uvRect, GLuint texture, crvec4 color, float angle=0.0f, float depth=0.5)
void render () const
renders the batch
Private Member Functions
void createVertexArrayObject ()
creates the vertex array object
void createRenderBatches ()
creates the render batches
void sortGlyphs ()
sorts the glyphs
Static Private Member Functions
static bool compareTexture (Glyph *lhs, Glyph *rhs)
comparers used to sort
static bool compareDepth (Glyph *lhs, Glyph *rhs)
Private Attributes
std::vector< Glyph * > m_glyphPointers
pointers to the glyphs to be rendered (used for sorting)
std::vector< Glyph > m_glyphs
the glyphs to be rendered (used for fast vector operations)
std::vector< RenderBatch > m_renderBatches
the render batches used for rendering the glyphs
GLuint m_vao = 0
ids of the vertex buffer object and vertex array object used to render the glyphs
GLuint m_vbo = 0
Detailed Description
represents a collection of sprites to be drawn If you want to draw a shape other than a square, use PrimitiveBatch instead
Todo:
Allow for custom vertex types
Definition at line 85 of file SpriteBatch.h.
Constructor & Destructor Documentation
SpriteBatch()
nta::SpriteBatch::SpriteBatch ()
constructor and destructor
Definition at line 7 of file SpriteBatch.cpp.
~SpriteBatch()
nta::SpriteBatch::~SpriteBatch ()
Definition at line 9 of file SpriteBatch.cpp.
Member Function Documentation
addGlyph() [1/4]
void nta::SpriteBatch::addGlyph (crvec4 posRect, crvec4 uvRect, GLuint texture, float depth = 0.5, crvec4 color = glm::vec4(1))
adds a glyph to the batch
Todo:
Give some of these different names?
Definition at line 103 of file SpriteBatch.cpp.
Referenced by addGlyph(), nta::ParticleBatch2D::draw(), nta::SpriteFont::drawText(), and nta::SpriteFont::drawTexture().
addGlyph() [2/4]
void nta::SpriteBatch::addGlyph (crvec2 corner1, crvec2 corner2, crvec4 uvRect, GLuint texture, float depth = 0.5, crvec4 color = glm::vec4(1))
Definition at line 107 of file SpriteBatch.cpp.
addGlyph() [3/4]
void nta::SpriteBatch::addGlyph (crvec4 posRect, crvec4 uvRect, GLuint texture, crvec4 color, float angle = 0.0f, float depth = 0.5)
Definition at line 121 of file SpriteBatch.cpp.
addGlyph() [4/4]
void nta::SpriteBatch::addGlyph (crvec2 corner1, crvec2 corner2, crvec4 uvRect, GLuint texture, crvec4 color, float angle = 0.0f, float depth = 0.5)
Definition at line 125 of file SpriteBatch.cpp.
begin()
void nta::SpriteBatch::begin ()
begins collection of glyphs for the batch
Definition at line 41 of file SpriteBatch.cpp.
Referenced by sortGlyphs().
compareDepth()
bool nta::SpriteBatch::compareDepth (Glyph * lhs, Glyph * rhs) static private
Definition at line 63 of file SpriteBatch.cpp.
Referenced by sortGlyphs().
compareTexture()
bool nta::SpriteBatch::compareTexture (Glyph * lhs, Glyph * rhs) static private
comparers used to sort
Definition at line 66 of file SpriteBatch.cpp.
Referenced by sortGlyphs().
createRenderBatches()
void nta::SpriteBatch::createRenderBatches () private
creates the render batches
Definition at line 69 of file SpriteBatch.cpp.
Referenced by end().
createVertexArrayObject()
void nta::SpriteBatch::createVertexArrayObject () private
creates the vertex array object
Definition at line 23 of file SpriteBatch.cpp.
Referenced by init().
end()
void nta::SpriteBatch::end ()
ends collection of glyphs and prepares to render
Definition at line 45 of file SpriteBatch.cpp.
init()
void nta::SpriteBatch::init ()
initializes the batch
Definition at line 20 of file SpriteBatch.cpp.
render()
void nta::SpriteBatch::render () const
renders the batch
Definition at line 131 of file SpriteBatch.cpp.
sortGlyphs()
void nta::SpriteBatch::sortGlyphs () private
sorts the glyphs
Definition at line 53 of file SpriteBatch.cpp.
Referenced by end().
Member Data Documentation
m_glyphPointers
std::vector<Glyph*> nta::SpriteBatch::m_glyphPointers private
pointers to the glyphs to be rendered (used for sorting)
Definition at line 97 of file SpriteBatch.h.
Referenced by createRenderBatches(), end(), sortGlyphs(), and ~SpriteBatch().
m_glyphs
std::vector<Glyph> nta::SpriteBatch::m_glyphs private
the glyphs to be rendered (used for fast vector operations)
Definition at line 99 of file SpriteBatch.h.
Referenced by addGlyph(), begin(), end(), and ~SpriteBatch().
m_renderBatches
std::vector<RenderBatch> nta::SpriteBatch::m_renderBatches private
the render batches used for rendering the glyphs
Definition at line 101 of file SpriteBatch.h.
Referenced by begin(), createRenderBatches(), render(), and ~SpriteBatch().
m_vao
GLuint nta::SpriteBatch::m_vao = 0 private
ids of the vertex buffer object and vertex array object used to render the glyphs
Definition at line 103 of file SpriteBatch.h.
Referenced by createVertexArrayObject(), render(), and ~SpriteBatch().
m_vbo
GLuint nta::SpriteBatch::m_vbo = 0 private
Definition at line 104 of file SpriteBatch.h.
Referenced by createRenderBatches(), createVertexArrayObject(), and ~SpriteBatch().
The documentation for this class was generated from the following files:
include/nta/SpriteBatch.h
src/SpriteBatch.cpp