jubilant-funicular: GLM_GTC_quaternion
GLM_GTC_quaternion
Stable extensions
Classes
struct glm::tquat< T, Q >
Functions
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator+ (tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator- (tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator+ (tquat< T, Q > const &q, tquat< T, Q > const &p)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator- (tquat< T, Q > const &q, tquat< T, Q > const &p)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator* (tquat< T, Q > const &q, tquat< T, Q > const &p)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::operator* (tquat< T, Q > const &q, vec< 3, T, Q > const &v)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::operator* (vec< 3, T, Q > const &v, tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, T, Q > glm::operator* (tquat< T, Q > const &q, vec< 4, T, Q > const &v)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, T, Q > glm::operator* (vec< 4, T, Q > const &v, tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator* (tquat< T, Q > const &q, T const &s)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator* (T const &s, tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::operator/ (tquat< T, Q > const &q, T const &s)
template<typename T , qualifier Q>
GLM_FUNC_DECL bool glm::operator== (tquat< T, Q > const &q1, tquat< T, Q > const &q2)
template<typename T , qualifier Q>
GLM_FUNC_DECL bool glm::operator!= (tquat< T, Q > const &q1, tquat< T, Q > const &q2)
template<typename T , qualifier Q>
GLM_FUNC_DECL T glm::length (tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::normalize (tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL T glm::dot (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::mix (tquat< T, Q > const &x, tquat< T, Q > const &y, T a)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::lerp (tquat< T, Q > const &x, tquat< T, Q > const &y, T a)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::slerp (tquat< T, Q > const &x, tquat< T, Q > const &y, T a)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::conjugate (tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::inverse (tquat< T, Q > const &q)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::rotate (tquat< T, Q > const &q, T const &angle, vec< 3, T, Q > const &axis)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::eulerAngles (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL T glm::roll (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL T glm::pitch (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL T glm::yaw (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL mat< 3, 3, T, Q > glm::mat3_cast (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL mat< 4, 4, T, Q > glm::mat4_cast (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::quat_cast (mat< 3, 3, T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::quat_cast (mat< 4, 4, T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL T glm::angle (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 3, T, Q > glm::axis (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL tquat< T, Q > glm::angleAxis (T const &angle, vec< 3, T, Q > const &axis)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::lessThan (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::lessThanEqual (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::greaterThan (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::greaterThanEqual (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::equal (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::notEqual (tquat< T, Q > const &x, tquat< T, Q > const &y)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::isnan (tquat< T, Q > const &x)
template<typename T , qualifier Q>
GLM_FUNC_DECL vec< 4, bool, Q > glm::isinf (tquat< T, Q > const &x)
Detailed Description
Include <glm/gtc/quaternion.hpp> to use the features of this extension.
Defines a templated quaternion type and several quaternion operations.
Function Documentation
angle()
template<typename T , qualifier Q> GLM_FUNC_DECL T glm::angle (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns the quaternion rotation angle.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 701 of file quaternion.inl.
Referenced by cimg_library_suffixed::CImg< charT >::get_rotate(), nta::Primitive::Primitive(), and glm::rotateNormalizedAxis().
angleAxis()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::angleAxis (T const & angle, vec< 3, T, Q > const & axis)
#include <deps/glm/gtc/quaternion.hpp>
Build a quaternion from an angle and a normalized axis.
Parameters
angle Angle expressed in radians.
axis Axis of the quaternion, must be normalized.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 717 of file quaternion.inl.
axis()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::axis (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns the q rotation axis.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 707 of file quaternion.inl.
Referenced by cimg_library_suffixed::CImg< charT >::autocrop(), cimg_library_suffixed::CImg< charT >::discard(), cimg_library_suffixed::CImgDisplay::display(), cimg_library_suffixed::CImg< charT >::get_autocrop(), cimg_library_suffixed::CImg< charT >::get_discard(), cimg_library_suffixed::CImg< charT >::get_sort(), glm::rotateNormalizedAxis(), and cimg_library_suffixed::CImg< charT >::sort().
conjugate()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::conjugate (tquat< T, Q > const & q)
#include <deps/glm/gtc/quaternion.hpp>
Returns the q conjugate.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 211 of file quaternion.inl.
dot()
template<typename T , qualifier Q> GLM_FUNC_DECL T glm::dot (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns dot product of q1 and q2, i.e., q1[0] * q2[0] + q1[1] * q2[1] + ...
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 388 of file quaternion.inl.
equal()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::equal (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns the component-wise comparison of result x == y.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 768 of file quaternion.inl.
eulerAngles()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<3, T, Q> glm::eulerAngles (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns euler angles, pitch as x, yaw as y, roll as z. The result is expressed in radians.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 585 of file quaternion.inl.
greaterThan()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::greaterThan (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns the component-wise comparison of result x > y.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 750 of file quaternion.inl.
greaterThanEqual()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::greaterThanEqual (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns the component-wise comparison of result x >= y.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 759 of file quaternion.inl.
inverse()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::inverse (tquat< T, Q > const & q)
#include <deps/glm/gtc/quaternion.hpp>
Returns the q inverse.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 217 of file quaternion.inl.
Referenced by glm::intermediate().
isinf()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::isinf (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns true if x holds a positive infinity or negative infinity representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no infinity representations.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 794 of file quaternion.inl.
isnan()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::isnan (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns true if x holds a NaN (not a number) representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no NaN representations.
/!\ When using compiler fast math, this function may fail.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 786 of file quaternion.inl.
length()
template<typename T , qualifier Q> GLM_FUNC_DECL T glm::length (tquat< T, Q > const & q)
#include <deps/glm/gtc/quaternion.hpp>
Returns the length of the quaternion.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 395 of file quaternion.inl.
lerp()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::lerp (tquat< T, Q > const & x, tquat< T, Q > const & y, T a)
#include <deps/glm/gtc/quaternion.hpp>
Linear interpolation of two quaternions. The interpolation is oriented.
Parameters
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined in the range [0, 1].
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 520 of file quaternion.inl.
lessThan()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::lessThan (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns the component-wise comparison result of x < y.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 732 of file quaternion.inl.
lessThanEqual()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::lessThanEqual (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns the component-wise comparison of result x <= y.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 741 of file quaternion.inl.
mat3_cast()
template<typename T , qualifier Q> GLM_FUNC_DECL mat<3, 3, T, Q> glm::mat3_cast (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Converts a quaternion to a 3 * 3 matrix.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 616 of file quaternion.inl.
mat4_cast()
template<typename T , qualifier Q> GLM_FUNC_DECL mat<4, 4, T, Q> glm::mat4_cast (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Converts a quaternion to a 4 * 4 matrix.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 644 of file quaternion.inl.
mix()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::mix (tquat< T, Q > const & x, tquat< T, Q > const & y, T a)
#include <deps/glm/gtc/quaternion.hpp>
Spherical linear interpolation of two quaternions. The interpolation is oriented and the rotation is performed at constant speed. For short path spherical linear interpolation, use the slerp function.
Parameters
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
Template Parameters
T Floating-point scalar types.
See also
- slerp(tquat<T, Q> const& x, tquat<T, Q> const& y, T const& a)
GLM_GTC_quaternion
Definition at line 497 of file quaternion.inl.
Referenced by glm::squad().
normalize()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::normalize (tquat< T, Q > const & q)
#include <deps/glm/gtc/quaternion.hpp>
Returns the normalized quaternion.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 401 of file quaternion.inl.
notEqual()
template<typename T , qualifier Q> GLM_FUNC_DECL vec<4, bool, Q> glm::notEqual (tquat< T, Q > const & x, tquat< T, Q > const & y)
#include <deps/glm/gtc/quaternion.hpp>
Returns the component-wise comparison of result x != y.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 777 of file quaternion.inl.
pitch()
template<typename T , qualifier Q> GLM_FUNC_DECL T glm::pitch (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns pitch value of euler angles expressed in radians.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 597 of file quaternion.inl.
quat_cast() [1/2]
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::quat_cast (mat< 3, 3, T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Converts a 3 * 3 matrix to a quaternion.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 650 of file quaternion.inl.
quat_cast() [2/2]
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::quat_cast (mat< 4, 4, T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Converts a 4 * 4 matrix to a quaternion.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 695 of file quaternion.inl.
roll()
template<typename T , qualifier Q> GLM_FUNC_DECL T glm::roll (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns roll value of euler angles expressed in radians.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 591 of file quaternion.inl.
rotate()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::rotate (tquat< T, Q > const & q, T const & angle, vec< 3, T, Q > const & axis)
#include <deps/glm/gtc/quaternion.hpp>
Rotates a quaternion from a vector of 3 components axis and an angle.
Parameters
q Source orientation
angle Angle expressed in radians.
axis Axis of the rotation
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 563 of file quaternion.inl.
slerp()
template<typename T , qualifier Q> GLM_FUNC_DECL tquat<T, Q> glm::slerp (tquat< T, Q > const & x, tquat< T, Q > const & y, T a)
#include <deps/glm/gtc/quaternion.hpp>
Spherical linear interpolation of two quaternions. The interpolation always take the short path and the rotation is performed at constant speed.
Parameters
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 530 of file quaternion.inl.
yaw()
template<typename T , qualifier Q> GLM_FUNC_DECL T glm::yaw (tquat< T, Q > const & x)
#include <deps/glm/gtc/quaternion.hpp>
Returns yaw value of euler angles expressed in radians.
Template Parameters
T Floating-point scalar types.
See also
GLM_GTC_quaternion
Definition at line 610 of file quaternion.inl.