jubilant-funicular: nta::InputManager Class Reference
nta::InputManager Class Reference
keeps track of all input
#include <InputManager.h>
Static Public Member Functions
static glm::vec2 getMouseCoords ()
returns the mouse's coordinates
static glm::vec2 getMouseCoordsStandard (int height)
returns the mouse's coordinates with the y axis flipped (0 represents the bottom of the screen instead of top)
static MouseWheelMotion getMouseWheelMotion ()
returns the mouse wheel's motion
static bool isPressed (unsigned int key)
returns whether or not specified key is pressed
static bool justPressed (unsigned int key)
returns whether or not the key was just pressed this frame
static bool justReleased (unsigned int key)
returns whether or not the key was just released this frame
static void pressKey (unsigned int key)
tells InputManager that specified key was pressed
static void releaseKey (unsigned int key)
tells InputManager that specified key was released
static void setMouseCoords (float x, float y)
tells InputManager where the mouse is
static void setMouseWheelMotion (const MouseWheelMotion &motion)
tells InputManager how the wheel is rolling
static void update (SDL_Event &event)
updates the state of m_KeyMap
static void updatePrev ()
updates the state of m_prevKeyMap
Static Private Attributes
static std::unordered_map< unsigned int, bool > m_keyMap
stores whether each key is pressed or not
static std::unordered_map< unsigned int, bool > m_prevKeyMap
stores whether the key was pressed last frame or not
static glm::vec2 m_mouseCoords
stores the location of the mouse in mouse coordinates
static MouseWheelMotion m_mouseWheelMotion
stores the motion of the mouse wheel
Detailed Description
keeps track of all input
Definition at line 12 of file InputManager.h.
Member Function Documentation
getMouseCoords()
glm::vec2 nta::InputManager::getMouseCoords () static
returns the mouse's coordinates
Definition at line 8 of file InputManager.cpp.
getMouseCoordsStandard()
glm::vec2 nta::InputManager::getMouseCoordsStandard (int height) static
returns the mouse's coordinates with the y axis flipped (0 represents the bottom of the screen instead of top)
Definition at line 11 of file InputManager.cpp.
getMouseWheelMotion()
MouseWheelMotion nta::InputManager::getMouseWheelMotion () static
returns the mouse wheel's motion
Definition at line 14 of file InputManager.cpp.
isPressed()
bool nta::InputManager::isPressed (unsigned int key) static
returns whether or not specified key is pressed
Definition at line 17 of file InputManager.cpp.
justPressed()
bool nta::InputManager::justPressed (unsigned int key) static
returns whether or not the key was just pressed this frame
Definition at line 25 of file InputManager.cpp.
Referenced by nta::Screen::handleInput().
justReleased()
bool nta::InputManager::justReleased (unsigned int key) static
returns whether or not the key was just released this frame
Definition at line 33 of file InputManager.cpp.
pressKey()
void nta::InputManager::pressKey (unsigned int key) static
tells InputManager that specified key was pressed
Definition at line 41 of file InputManager.cpp.
Referenced by update().
releaseKey()
void nta::InputManager::releaseKey (unsigned int key) static
tells InputManager that specified key was released
Definition at line 44 of file InputManager.cpp.
Referenced by update().
setMouseCoords()
void nta::InputManager::setMouseCoords (float x, float y) static
tells InputManager where the mouse is
Definition at line 47 of file InputManager.cpp.
Referenced by update().
setMouseWheelMotion()
void nta::InputManager::setMouseWheelMotion (const MouseWheelMotion & motion) static
tells InputManager how the wheel is rolling
Definition at line 51 of file InputManager.cpp.
Referenced by nta::Screen::handleInput(), and update().
update()
void nta::InputManager::update (SDL_Event & event) static
updates the state of m_KeyMap
Definition at line 54 of file InputManager.cpp.
Referenced by nta::Screen::handleInput().
updatePrev()
void nta::InputManager::updatePrev () static
updates the state of m_prevKeyMap
Definition at line 64 of file InputManager.cpp.
Referenced by nta::Screen::handleInput().
Member Data Documentation
m_keyMap
std::unordered_map< unsigned int, bool > nta::InputManager::m_keyMap static private
stores whether each key is pressed or not
Definition at line 15 of file InputManager.h.
Referenced by isPressed(), justPressed(), justReleased(), pressKey(), releaseKey(), and updatePrev().
m_mouseCoords
glm::vec2 nta::InputManager::m_mouseCoords static private
stores the location of the mouse in mouse coordinates
Definition at line 19 of file InputManager.h.
Referenced by getMouseCoords(), getMouseCoordsStandard(), and setMouseCoords().
m_mouseWheelMotion
MouseWheelMotion nta::InputManager::m_mouseWheelMotion static private
stores the motion of the mouse wheel
Definition at line 21 of file InputManager.h.
Referenced by getMouseWheelMotion(), and setMouseWheelMotion().
m_prevKeyMap
std::unordered_map< unsigned int, bool > nta::InputManager::m_prevKeyMap static private
stores whether the key was pressed last frame or not
Definition at line 17 of file InputManager.h.
Referenced by justPressed(), justReleased(), and updatePrev().
The documentation for this class was generated from the following files:
include/nta/InputManager.h
src/InputManager.cpp