jubilant-funicular: cimg_library_suffixed::CImgList< T > Struct Template Reference
cimg_library_suffixed::CImgList< T > Struct Template Reference
Represent a list of images CImg<T>.
#include <CImg.h>
Public Types
typedef CImg< T > * iterator
Simple iterator type, to loop through each image of a list.
typedef const CImg< T > * const_iterator
Simple const iterator type, to loop through each image of a const list instance.
typedef T value_type
Pixel value type.
typedef cimg::superset< T, bool >::type Tbool
typedef cimg::superset< T, unsigned char >::type Tuchar
typedef cimg::superset< T, char >::type Tchar
typedef cimg::superset< T, unsigned short >::type Tushort
typedef cimg::superset< T, short >::type Tshort
typedef cimg::superset< T, unsigned int >::type Tuint
typedef cimg::superset< T, int >::type Tint
typedef cimg::superset< T, cimg_ulong >::type Tulong
typedef cimg::superset< T, cimg_long >::type Tlong
typedef cimg::superset< T, float >::type Tfloat
typedef cimg::superset< T, double >::type Tdouble
typedef cimg::last< T, bool >::type boolT
typedef cimg::last< T, unsigned char >::type ucharT
typedef cimg::last< T, char >::type charT
typedef cimg::last< T, unsigned short >::type ushortT
typedef cimg::last< T, short >::type shortT
typedef cimg::last< T, unsigned int >::type uintT
typedef cimg::last< T, int >::type intT
typedef cimg::last< T, cimg_ulong >::type ulongT
typedef cimg::last< T, cimg_long >::type longT
typedef cimg::last< T, cimg_uint64 >::type uint64T
typedef cimg::last< T, cimg_int64 >::type int64T
typedef cimg::last< T, float >::type floatT
typedef cimg::last< T, double >::type doubleT
Public Member Functions
Overloaded Operators
CImg< T > & operator() (const unsigned int pos)
Return a reference to one image element of the list.
const CImg< T > & operator() (const unsigned int pos) const
Return a reference to one image of the list.
T & operator() (const unsigned int pos, const unsigned int x, const unsigned int y=0, const unsigned int z=0, const unsigned int c=0)
Return a reference to one pixel value of one image of the list.
const T & operator() (const unsigned int pos, const unsigned int x, const unsigned int y=0, const unsigned int z=0, const unsigned int c=0) const
Return a reference to one pixel value of one image of the list .
operator CImg< T > * ()
Return pointer to the first image of the list.
operator const CImg< T > * () const
Return pointer to the first image of the list .
template<typename t >
CImgList< T > & operator= (const CImg< t > &img)
Construct list from one image .
template<typename t >
CImgList< T > & operator= (const CImgList< t > &list)
Construct list from another list.
CImgList< T > & operator= (const CImgList< T > &list)
Construct list from another list .
CImgList< T > & operator= (const char *const filename)
Construct list by reading the content of a file .
CImgList< T > & operator= (const CImgDisplay &disp)
Construct list from the content of a display window .
CImgList< T > operator+ () const
Return a non-shared copy of a list.
template<typename t >
CImgList< T > & operator, (const CImg< t > &img)
Return a copy of the list instance, where image img has been inserted at the end.
template<typename t >
CImgList< T > operator, (const CImg< t > &img) const
Return a copy of the list instance, where image img has been inserted at the end .
template<typename t >
CImgList< T > & operator, (const CImgList< t > &list)
Return a copy of the list instance, where all elements of input list list have been inserted at the end.
template<typename t >
CImgList< T > & operator, (const CImgList< t > &list) const
Return a copy of the list instance, where all elements of input list have been inserted at the end .
CImg< T > operator> (const char axis) const
Return image corresponding to the appending of all images of the instance list along specified axis.
CImgList< T > operator< (const char axis) const
Return list corresponding to the splitting of all images of the instance list along specified axis.
Mathematical Functions
T & min ()
Return a reference to the minimum pixel value of the instance list.
const T & min () const
Return a reference to the minimum pixel value of the instance list .
T & max ()
Return a reference to the maximum pixel value of the instance list.
const T & max () const
Return a reference to the maximum pixel value of the instance list .
template<typename t >
T & min_max (t &max_val)
Return a reference to the minimum pixel value of the instance list and return the maximum vvalue as well.
template<typename t >
const T & min_max (t &max_val) const
Return a reference to the minimum pixel value of the instance list and return the maximum vvalue as well .
template<typename t >
T & max_min (t &min_val)
Return a reference to the minimum pixel value of the instance list and return the minimum value as well.
template<typename t >
const T & max_min (t &min_val) const
Return a reference to the minimum pixel value of the instance list and return the minimum value as well .
List Manipulation
template<typename t >
CImgList< T > & insert (const CImg< t > &img, const unsigned int pos=~0U, const bool is_shared=false)
Insert a copy of the image img into the current image list, at position pos.
CImgList< T > & insert (const CImg< T > &img, const unsigned int pos=~0U, const bool is_shared=false)
Insert a copy of the image img into the current image list, at position pos .
template<typename t >
CImgList< T > get_insert (const CImg< t > &img, const unsigned int pos=~0U, const bool is_shared=false) const
Insert a copy of the image img into the current image list, at position pos .
CImgList< T > & insert (const unsigned int n, const unsigned int pos=~0U)
Insert n empty images img into the current image list, at position pos.
CImgList< T > get_insert (const unsigned int n, const unsigned int pos=~0U) const
Insert n empty images img into the current image list, at position pos .
template<typename t >
CImgList< T > & insert (const unsigned int n, const CImg< t > &img, const unsigned int pos=~0U, const bool is_shared=false)
Insert n copies of the image img into the current image list, at position pos.
template<typename t >
CImgList< T > get_insert (const unsigned int n, const CImg< t > &img, const unsigned int pos=~0U, const bool is_shared=false) const
Insert n copies of the image img into the current image list, at position pos .
template<typename t >
CImgList< T > & insert (const CImgList< t > &list, const unsigned int pos=~0U, const bool is_shared=false)
Insert a copy of the image list list into the current image list, starting from position pos.
template<typename t >
CImgList< T > get_insert (const CImgList< t > &list, const unsigned int pos=~0U, const bool is_shared=false) const
Insert a copy of the image list list into the current image list, starting from position pos .
template<typename t >
CImgList< T > & insert (const unsigned int n, const CImgList< t > &list, const unsigned int pos=~0U, const bool is_shared=false)
Insert n copies of the list list at position pos of the current list.
template<typename t >
CImgList< T > get_insert (const unsigned int n, const CImgList< t > &list, const unsigned int pos=~0U, const bool is_shared=false) const
Insert n copies of the list list at position pos of the current list .
CImgList< T > & remove (const unsigned int pos1, const unsigned int pos2)
Remove all images between from indexes.
CImgList< T > get_remove (const unsigned int pos1, const unsigned int pos2) const
Remove all images between from indexes .
CImgList< T > & remove (const unsigned int pos)
Remove image at index pos from the image list.
CImgList< T > get_remove (const unsigned int pos) const
Remove image at index pos from the image list .
CImgList< T > & remove ()
Remove last image.
CImgList< T > get_remove () const
Remove last image .
CImgList< T > & reverse ()
Reverse list order.
CImgList< T > get_reverse () const
Reverse list order .
CImgList< T > & images (const unsigned int pos0, const unsigned int pos1)
Return a sublist.
CImgList< T > get_images (const unsigned int pos0, const unsigned int pos1) const
Return a sublist .
CImgList< T > get_shared_images (const unsigned int pos0, const unsigned int pos1)
Return a shared sublist.
const CImgList< T > get_shared_images (const unsigned int pos0, const unsigned int pos1) const
Return a shared sublist .
CImg< T > get_append (const char axis, const float align=0) const
Return a single image which is the appending of all images of the current CImgList instance.
CImgList< T > & split (const char axis, const int nb=-1)
Return a list where each image has been split along the specified axis.
CImgList< T > get_split (const char axis, const int nb=-1) const
Return a list where each image has been split along the specified axis .
template<typename t >
CImgList< T > & push_back (const CImg< t > &img)
Insert image at the end of the list.
template<typename t >
CImgList< T > & push_front (const CImg< t > &img)
Insert image at the front of the list.
template<typename t >
CImgList< T > & push_back (const CImgList< t > &list)
Insert list at the end of the current list.
template<typename t >
CImgList< T > & push_front (const CImgList< t > &list)
Insert list at the front of the current list.
CImgList< T > & pop_back ()
Remove last image.
CImgList< T > & pop_front ()
Remove first image.
CImgList< T > & erase (const iterator iter)
Remove image pointed by iterator.
Public Attributes
unsigned int _width
unsigned int _allocated_width
CImg< T > * _data
Constructors / Destructor / Instance Management
~CImgList ()
Destructor.
CImgList ()
Default constructor.
CImgList (const unsigned int n)
Construct list containing empty images.
CImgList (const unsigned int n, const unsigned int width, const unsigned int height=1, const unsigned int depth=1, const unsigned int spectrum=1)
Construct list containing images of specified size.
CImgList (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const T &val)
Construct list containing images of specified size, and initialize pixel values.
CImgList (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const int val0, const int val1,...)
Construct list containing images of specified size, and initialize pixel values from a sequence of integers.
CImgList (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const double val0, const double val1,...)
Construct list containing images of specified size, and initialize pixel values from a sequence of doubles.
template<typename t >
CImgList (const unsigned int n, const CImg< t > &img, const bool is_shared=false)
Construct list containing copies of an input image.
template<typename t >
CImgList (const CImg< t > &img, const bool is_shared=false)
Construct list from one image.
template<typename t1 , typename t2 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const bool is_shared=false)
Construct list from two images.
template<typename t1 , typename t2 , typename t3 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const bool is_shared=false)
Construct list from three images.
template<typename t1 , typename t2 , typename t3 , typename t4 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const bool is_shared=false)
Construct list from four images.
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const bool is_shared=false)
Construct list from five images.
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const CImg< t6 > &img6, const bool is_shared=false)
Construct list from six images.
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const CImg< t6 > &img6, const CImg< t7 > &img7, const bool is_shared=false)
Construct list from seven images.
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 , typename t8 >
CImgList (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const CImg< t6 > &img6, const CImg< t7 > &img7, const CImg< t8 > &img8, const bool is_shared=false)
Construct list from eight images.
template<typename t >
CImgList (const CImgList< t > &list)
Construct list copy.
CImgList (const CImgList< T > &list)
Construct list copy .
template<typename t >
CImgList (const CImgList< t > &list, const bool is_shared)
Construct list copy, and force the shared state of the list elements.
CImgList (const char *const filename)
Construct list by reading the content of a file.
CImgList (const CImgDisplay &disp)
Construct list from the content of a display window.
CImgList< T > get_shared ()
Return a list with elements being shared copies of images in the list instance.
const CImgList< T > get_shared () const
Return a list with elements being shared copies of images in the list instance .
CImgList< T > & assign ()
Destructor .
CImgList< T > & clear ()
Destructor .
CImgList< T > & assign (const unsigned int n)
Construct list containing empty images .
CImgList< T > & assign (const unsigned int n, const unsigned int width, const unsigned int height=1, const unsigned int depth=1, const unsigned int spectrum=1)
Construct list containing images of specified size .
CImgList< T > & assign (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const T &val)
Construct list containing images of specified size, and initialize pixel values .
CImgList< T > & assign (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const int val0, const int val1,...)
Construct list with images of specified size, and initialize pixel values from a sequence of integers .
CImgList< T > & assign (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const double val0, const double val1,...)
Construct list with images of specified size, and initialize pixel values from a sequence of doubles .
template<typename t >
CImgList< T > & assign (const unsigned int n, const CImg< t > &img, const bool is_shared=false)
Construct list containing copies of an input image .
template<typename t >
CImgList< T > & assign (const CImg< t > &img, const bool is_shared=false)
Construct list from one image .
template<typename t1 , typename t2 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const bool is_shared=false)
Construct list from two images .
template<typename t1 , typename t2 , typename t3 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const bool is_shared=false)
Construct list from three images .
template<typename t1 , typename t2 , typename t3 , typename t4 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const bool is_shared=false)
Construct list from four images .
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const bool is_shared=false)
Construct list from five images .
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const CImg< t6 > &img6, const bool is_shared=false)
Construct list from six images .
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const CImg< t6 > &img6, const CImg< t7 > &img7, const bool is_shared=false)
Construct list from seven images .
template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 , typename t8 >
CImgList< T > & assign (const CImg< t1 > &img1, const CImg< t2 > &img2, const CImg< t3 > &img3, const CImg< t4 > &img4, const CImg< t5 > &img5, const CImg< t6 > &img6, const CImg< t7 > &img7, const CImg< t8 > &img8, const bool is_shared=false)
Construct list from eight images .
template<typename t >
CImgList< T > & assign (const CImgList< t > &list, const bool is_shared=false)
Construct list as a copy of an existing list and force the shared state of the list elements .
CImgList< T > & assign (const CImgList< T > &list, const bool is_shared=false)
Construct list as a copy of an existing list and force shared state of elements .
CImgList< T > & assign (const char *const filename)
Construct list by reading the content of a file .
CImgList< T > & assign (const CImgDisplay &disp)
Construct list from the content of a display window .
template<typename t >
CImgList< t > & move_to (CImgList< t > &list)
Transfer the content of the list instance to another list.
template<typename t >
CImgList< t > & move_to (CImgList< t > &list, const unsigned int pos)
Transfer the content of the list instance at a specified position in another list.
CImgList< T > & swap (CImgList< T > &list)
Swap all fields between two list instances.
static CImgList< T > & empty ()
Return a reference to an empty list.
static const CImgList< T > & const_empty ()
Return a reference to an empty list .
Instance Characteristics
int width () const
Return the size of the list, i.e. the number of images contained in it.
unsigned int size () const
Return the size of the list, i.e. the number of images contained in it.
CImg< T > * data ()
Return pointer to the first image of the list.
const CImg< T > * data () const
Return pointer to the first image of the list .
CImg< T > * data (const unsigned int l)
Return pointer to the pos-th image of the list.
const CImg< T > * data (const unsigned int l) const
Return pointer to the pos-th image of the list .
iterator begin ()
Return iterator to the first image of the list.
const_iterator begin () const
Return iterator to the first image of the list .
iterator end ()
Return iterator to one position after the last image of the list.
const_iterator end () const
Return iterator to one position after the last image of the list .
CImg< T > & front ()
Return reference to the first image of the list.
const CImg< T > & front () const
Return reference to the first image of the list .
const CImg< T > & back () const
Return a reference to the last image of the list.
CImg< T > & back ()
Return a reference to the last image of the list .
CImg< T > & at (const int pos)
Return pos-th image of the list.
T & atNXYZC (const int pos, const int x, const int y, const int z, const int c, const T &out_value)
Access to pixel value with Dirichlet boundary conditions.
T atNXYZC (const int pos, const int x, const int y, const int z, const int c, const T &out_value) const
Access to pixel value with Dirichlet boundary conditions .
T & atNXYZC (const int pos, const int x, const int y, const int z, const int c)
Access to pixel value with Neumann boundary conditions.
T atNXYZC (const int pos, const int x, const int y, const int z, const int c) const
Access to pixel value with Neumann boundary conditions .
T & _atNXYZC (const int pos, const int x, const int y, const int z, const int c)
T _atNXYZC (const int pos, const int x, const int y, const int z, const int c) const
T & atNXYZ (const int pos, const int x, const int y, const int z, const int c, const T &out_value)
Access pixel value with Dirichlet boundary conditions for the 3 coordinates (pos, x,y,z).
T atNXYZ (const int pos, const int x, const int y, const int z, const int c, const T &out_value) const
Access pixel value with Dirichlet boundary conditions for the 3 coordinates (pos, x,y,z) .
T & atNXYZ (const int pos, const int x, const int y, const int z, const int c=0)
Access to pixel value with Neumann boundary conditions for the 4 coordinates (pos, x,y,z).
T atNXYZ (const int pos, const int x, const int y, const int z, const int c=0) const
Access to pixel value with Neumann boundary conditions for the 4 coordinates (pos, x,y,z) .
T & _atNXYZ (const int pos, const int x, const int y, const int z, const int c=0)
T _atNXYZ (const int pos, const int x, const int y, const int z, const int c=0) const
T & atNXY (const int pos, const int x, const int y, const int z, const int c, const T &out_value)
Access to pixel value with Dirichlet boundary conditions for the 3 coordinates (pos, x,y).
T atNXY (const int pos, const int x, const int y, const int z, const int c, const T &out_value) const
Access to pixel value with Dirichlet boundary conditions for the 3 coordinates (pos, x,y) .
T & atNXY (const int pos, const int x, const int y, const int z=0, const int c=0)
Access to pixel value with Neumann boundary conditions for the 3 coordinates (pos, x,y).
T atNXY (const int pos, const int x, const int y, const int z=0, const int c=0) const
Access to pixel value with Neumann boundary conditions for the 3 coordinates (pos, x,y) .
T & _atNXY (const int pos, const int x, const int y, const int z=0, const int c=0)
T _atNXY (const int pos, const int x, const int y, const int z=0, const int c=0) const
T & atNX (const int pos, const int x, const int y, const int z, const int c, const T &out_value)
Access to pixel value with Dirichlet boundary conditions for the 2 coordinates (pos,x).
T atNX (const int pos, const int x, const int y, const int z, const int c, const T &out_value) const
Access to pixel value with Dirichlet boundary conditions for the 2 coordinates (pos,x) .
T & atNX (const int pos, const int x, const int y=0, const int z=0, const int c=0)
Access to pixel value with Neumann boundary conditions for the 2 coordinates (pos, x).
T atNX (const int pos, const int x, const int y=0, const int z=0, const int c=0) const
Access to pixel value with Neumann boundary conditions for the 2 coordinates (pos, x) .
T & _atNX (const int pos, const int x, const int y=0, const int z=0, const int c=0)
T _atNX (const int pos, const int x, const int y=0, const int z=0, const int c=0) const
T & atN (const int pos, const int x, const int y, const int z, const int c, const T &out_value)
Access to pixel value with Dirichlet boundary conditions for the coordinate (pos).
T atN (const int pos, const int x, const int y, const int z, const int c, const T &out_value) const
Access to pixel value with Dirichlet boundary conditions for the coordinate (pos) .
T & atN (const int pos, const int x=0, const int y=0, const int z=0, const int c=0)
Return pixel value with Neumann boundary conditions for the coordinate (pos).
T atN (const int pos, const int x=0, const int y=0, const int z=0, const int c=0) const
Return pixel value with Neumann boundary conditions for the coordinate (pos) .
T & _atN (const int pos, const int x=0, const int y=0, const int z=0, const int c=0)
T _atN (const int pos, const int x=0, const int y=0, const int z=0, const int c=0) const
static const char * pixel_type ()
Return the type of image pixel values as a C string.
Instance Checking
Y C C Y
Y C C Z Z
Y C C Z C const unsigned int dy
Y C C Z C const unsigned int const unsigned int dz
Y C C Z C const unsigned int const unsigned int const unsigned int dc const
return res
bool is_empty () const
Return true if list is empty.
bool is_sameN (const unsigned int size_n) const
Test if number of image elements is equal to specified value.
template<typename t >
bool is_sameN (const CImgList< t > &list) const
Test if number of image elements is equal between two images lists.
_cimglist_def_is_same (XY) _cimglist_def_is_same(XZ) _cimglist_def_is_same(XC) _cimglist_def_is_same(YZ) _cimglist_def_is_same(YC) _cimglist_def_is_same(XYZ) _cimglist_def_is_same(XYC) _cimglist_def_is_same(YZC) _cimglist_def_is_same(XYZC) _cimglist_def_is_same1(X) _cimglist_def_is_same1(Y) _cimglist_def_is_same1(Z) _cimglist_def_is_same1(C) _cimglist_def_is_same2(X
Y _cimglist_def_is_same2 (X, Z) _cimglist_def_is_same2(X
Y C _cimglist_def_is_same2 (Y, Z) _cimglist_def_is_same2(Y
Y C C _cimglist_def_is_same2 (Z, C) _cimglist_def_is_same3(X
Y C C Z _cimglist_def_is_same3 (X, Y, C) _cimglist_def_is_same3(X
Y C C Z C _cimglist_def_is_same3 (Y, Z, C) bool is_sameXYZC(const unsigned int dx
Test if dimensions of each image of the list match specified arguments.
for (unsigned int l=0;l< _width &&res;++l) res
bool is_sameNXYZC (const unsigned int n, const unsigned int dx, const unsigned int dy, const unsigned int dz, const unsigned int dc) const
Test if list dimensions match specified arguments.
bool containsNXYZC (const int n, const int x=0, const int y=0, const int z=0, const int c=0) const
Test if list contains one particular pixel location.
bool containsN (const int n) const
Test if list contains image with specified indice.
template<typename t >
bool contains (const T &pixel, t &n, t &x, t &y, t &z, t &c) const
Test if one image of the list contains the specified referenced value.
template<typename t >
bool contains (const T &pixel, t &n, t &x, t &y, t &z) const
Test if one of the image list contains the specified referenced value.
template<typename t >
bool contains (const T &pixel, t &n, t &x, t &y) const
Test if one of the image list contains the specified referenced value.
template<typename t >
bool contains (const T &pixel, t &n, t &x) const
Test if one of the image list contains the specified referenced value.
template<typename t >
bool contains (const T &pixel, t &n) const
Test if one of the image list contains the specified referenced value.
bool contains (const T &pixel) const
Test if one of the image list contains the specified referenced value.
template<typename t >
bool contains (const CImg< T > &img, t &n) const
Test if the list contains the image 'img'.
bool contains (const CImg< T > &img) const
Test if the list contains the image img.
Data Input
CImg< intT > get_select (CImgDisplay &disp, const bool feature_type=true, const char axis='x', const float align=0, const bool exit_on_anykey=false) const
Display a simple interactive interface to select images or sublists.
CImg< intT > get_select (const char *const title, const bool feature_type=true, const char axis='x', const float align=0, const bool exit_on_anykey=false) const
Display a simple interactive interface to select images or sublists.
CImg< intT > _select (CImgDisplay &disp, const char *const title, const bool feature_type, const char axis, const float align, const bool exit_on_anykey, const unsigned int orig, const bool resize_disp, const bool exit_on_rightbutton, const bool exit_on_wheel) const
CImgList< T > & load (const char *const filename)
Load a list from a file.
CImgList< T > & load_cimg (const char *const filename)
Load a list from a .cimg file.
CImgList< T > & load_cimg (std::FILE *const file)
Load a list from a .cimg file.
CImgList< T > & _load_cimg (std::FILE *const file, const char *const filename)
CImgList< T > & load_cimg (const char *const filename, const unsigned int n0, const unsigned int n1, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0, const unsigned int x1, const unsigned int y1, const unsigned int z1, const unsigned int c1)
Load a sublist list from a (non compressed) .cimg file.
CImgList< T > & load_cimg (std::FILE *const file, const unsigned int n0, const unsigned int n1, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0, const unsigned int x1, const unsigned int y1, const unsigned int z1, const unsigned int c1)
Load a sub-image list from a (non compressed) .cimg file .
CImgList< T > & _load_cimg (std::FILE *const file, const char *const filename, const unsigned int n0, const unsigned int n1, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0, const unsigned int x1, const unsigned int y1, const unsigned int z1, const unsigned int c1)
CImgList< T > & load_parrec (const char *const filename)
Load a list from a PAR/REC (Philips) file.
CImgList< T > & load_yuv (const char *const filename, const unsigned int size_x, const unsigned int size_y, const unsigned int chroma_subsampling=444, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1, const bool yuv2rgb=true)
Load a list from a YUV image sequence file.
CImgList< T > & load_yuv (std::FILE *const file, const unsigned int size_x, const unsigned int size_y, const unsigned int chroma_subsampling=444, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1, const bool yuv2rgb=true)
Load a list from an image sequence YUV file .
CImgList< T > & _load_yuv (std::FILE *const file, const char *const filename, const unsigned int size_x, const unsigned int size_y, const unsigned int chroma_subsampling, const unsigned int first_frame, const unsigned int last_frame, const unsigned int step_frame, const bool yuv2rgb)
CImgList< T > & load_video (const char *const filename, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1)
Load an image from a video file, using OpenCV library.
CImgList< T > & load_ffmpeg_external (const char *const filename)
Load an image from a video file using the external tool 'ffmpeg'.
CImgList< T > & load_gif_external (const char *const filename)
Load gif file, using ImageMagick or GraphicsMagick's external tools.
CImgList< T > & _load_gif_external (const char *const filename, const bool use_graphicsmagick=false)
CImgList< T > & load_gzip_external (const char *const filename)
Load a gzipped list, using external tool 'gunzip'.
template<typename tf , typename tc >
CImgList< T > & load_off (const char *const filename, CImgList< tf > &primitives, CImgList< tc > &colors)
Load a 3d object from a .OFF file.
CImgList< T > & load_tiff (const char *const filename, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1, float *const voxel_size=0, CImg< charT > *const description=0)
Load images from a TIFF file.
static CImgList< T > get_load (const char *const filename)
Load a list from a file .
static CImgList< T > get_load_cimg (const char *const filename)
Load a list from a .cimg file .
static CImgList< T > get_load_cimg (std::FILE *const file)
Load a list from a .cimg file .
static CImgList< T > get_load_cimg (const char *const filename, const unsigned int n0, const unsigned int n1, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0, const unsigned int x1, const unsigned int y1, const unsigned int z1, const unsigned int c1)
Load a sublist list from a (non compressed) .cimg file .
static CImgList< T > get_load_cimg (std::FILE *const file, const unsigned int n0, const unsigned int n1, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0, const unsigned int x1, const unsigned int y1, const unsigned int z1, const unsigned int c1)
Load a sub-image list from a (non compressed) .cimg file .
static CImgList< T > get_load_parrec (const char *const filename)
Load a list from a PAR/REC (Philips) file .
static CImgList< T > get_load_yuv (const char *const filename, const unsigned int size_x, const unsigned int size_y=1, const unsigned int chroma_subsampling=444, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1, const bool yuv2rgb=true)
Load a list from a YUV image sequence file .
static CImgList< T > get_load_yuv (std::FILE *const file, const unsigned int size_x, const unsigned int size_y=1, const unsigned int chroma_subsampling=444, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1, const bool yuv2rgb=true)
Load a list from an image sequence YUV file .
static CImgList< T > get_load_video (const char *const filename, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1)
Load an image from a video file, using OpenCV library .
static CImgList< T > get_load_ffmpeg_external (const char *const filename)
Load an image from a video file using the external tool 'ffmpeg' .
static CImgList< T > get_load_gif_external (const char *const filename)
Load gif file, using ImageMagick or GraphicsMagick's external tools .
static CImgList< T > get_load_gzip_external (const char *const filename)
Load a gzipped list, using external tool 'gunzip' .
template<typename tf , typename tc >
static CImgList< T > get_load_off (const char *const filename, CImgList< tf > &primitives, CImgList< tc > &colors)
Load a 3d object from a .OFF file .
static CImgList< T > get_load_tiff (const char *const filename, const unsigned int first_frame=0, const unsigned int last_frame=~0U, const unsigned int step_frame=1, float *const voxel_size=0, CImg< charT > *const description=0)
Load a multi-page TIFF file .
Data Output
const CImgList< T > & print (const char *const title=0, const bool display_stats=true) const
Print information about the list on the standard output.
const CImgList< T > & display (CImgDisplay &disp, const char axis='x', const float align=0) const
Display the current CImgList instance in an existing CImgDisplay window (by reference).
const CImgList< T > & display (CImgDisplay &disp, const bool display_info, const char axis='x', const float align=0, unsigned int *const XYZ=0, const bool exit_on_anykey=false) const
Display the current CImgList instance in a new display window.
const CImgList< T > & display (const char *const title=0, const bool display_info=true, const char axis='x', const float align=0, unsigned int *const XYZ=0, const bool exit_on_anykey=false) const
Display the current CImgList instance in a new display window.
const CImgList< T > & _display (CImgDisplay &disp, const char *const title, const CImgList< charT > *const titles, const bool display_info, const char axis, const float align, unsigned int *const XYZ, const bool exit_on_anykey, const unsigned int orig, const bool is_first_call, bool &is_exit) const
CImg< charT > __display () const
const CImgList< T > & save (const char *const filename, const int number=-1, const unsigned int digits=6) const
Save list into a file.
const CImgList< T > & save_gif_external (const char *const filename, const float fps=25, const unsigned int nb_loops=0)
Save image sequence as a GIF animated file.
const CImgList< T > & save_yuv (const char *const filename=0, const unsigned int chroma_subsampling=444, const bool is_rgb=true) const
Save list as a YUV image sequence file.
const CImgList< T > & save_yuv (std::FILE *const file, const unsigned int chroma_subsampling=444, const bool is_rgb=true) const
Save image sequence into a YUV file.
const CImgList< T > & _save_yuv (std::FILE *const file, const char *const filename, const unsigned int chroma_subsampling, const bool is_rgb) const
const CImgList< T > & save_cimg (const char *const filename, const bool is_compressed=false) const
Save list into a .cimg file.
const CImgList< T > & _save_cimg (std::FILE *const file, const char *const filename, const bool is_compressed) const
const CImgList< T > & save_cimg (std::FILE *file, const bool is_compressed=false) const
Save list into a .cimg file.
const CImgList< T > & _save_cimg (std::FILE *const file, const char *const filename, const unsigned int n0, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0) const
const CImgList< T > & save_cimg (const char *const filename, const unsigned int n0, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0) const
Insert the image instance into into an existing .cimg file, at specified coordinates.
const CImgList< T > & save_cimg (std::FILE *const file, const unsigned int n0, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0) const
Insert the image instance into into an existing .cimg file, at specified coordinates.
const CImgList< T > & save_tiff (const char *const filename, const unsigned int compression_type=0, const float *const voxel_size=0, const char *const description=0, const bool use_bigtiff=true) const
Save list as a TIFF file.
const CImgList< T > & save_gzip_external (const char *const filename) const
Save list as a gzipped file, using external tool 'gzip'.
const CImgList< T > & save_video (const char *const filename, const unsigned int fps=25, const char *codec=0, const bool keep_open=false) const
Save image sequence, using the OpenCV library.
const CImgList< T > & save_ffmpeg_external (const char *const filename, const unsigned int fps=25, const char *const codec=0, const unsigned int bitrate=2048) const
Save image sequence, using the external tool 'ffmpeg'.
CImg< ucharT > get_serialize (const bool is_compressed=false) const
Serialize a CImgList<T> instance into a raw CImg<unsigned char> buffer.
static bool is_saveable (const char *const filename)
Tell if an image list can be saved as one single file.
static void _save_empty_cimg (std::FILE *const file, const char *const filename, const unsigned int nb, const unsigned int dx, const unsigned int dy, const unsigned int dz, const unsigned int dc)
static void save_empty_cimg (const char *const filename, const unsigned int nb, const unsigned int dx, const unsigned int dy=1, const unsigned int dz=1, const unsigned int dc=1)
Save empty (non-compressed) .cimg file with specified dimensions.
static void save_empty_cimg (std::FILE *const file, const unsigned int nb, const unsigned int dx, const unsigned int dy=1, const unsigned int dz=1, const unsigned int dc=1)
Save empty .cimg file with specified dimensions.
template<typename t >
static CImgList< T > get_unserialize (const CImg< t > &buffer)
Unserialize a CImg<unsigned char> serialized buffer into a CImgList<T> list.
Others
CImgList< T > & crop_font ()
Crop font along the X-axis.
CImgList< T > get_crop_font () const
Crop font along the X-axis .
CImgList< T > & FFT (const char axis, const bool invert=false)
Compute a 1d Fast Fourier Transform, along specified axis.
CImgList< Tfloat > get_FFT (const char axis, const bool invert=false) const
Compute a 1-D Fast Fourier Transform, along specified axis .
CImgList< T > & FFT (const bool invert=false)
Compute a n-d Fast Fourier Transform.
CImgList< Tfloat > get_FFT (const bool invert=false) const
Compute a n-d Fast Fourier Transform .
CImgList< T > & reverse_object3d ()
Reverse primitives orientations of a 3d object.
CImgList< T > get_reverse_object3d () const
Reverse primitives orientations of a 3d object .
static const CImgList< ucharT > & font (const unsigned int font_height, const bool is_variable_width=true)
Return a CImg pre-defined font with desired size.
Detailed Description
template<typename T>
struct cimg_library_suffixed::CImgList< T >
Represent a list of images CImg<T>.
Definition at line 2210 of file CImg.h.
Member Typedef Documentation
const_iterator
template<typename T> typedef const CImg<T>* cimg_library_suffixed::CImgList< T >::const_iterator
Simple const iterator type, to loop through each image of a const list instance.
Note
The CImgList<T>::const_iterator type is defined to be a const CImg<T>*.
Similar to CImgList<T>::iterator, but for constant list instances.
Definition at line 54651 of file CImg.h.
iterator
template<typename T> typedef CImg<T>* cimg_library_suffixed::CImgList< T >::iterator
Simple iterator type, to loop through each image of a list.
Note
The CImgList<T>::iterator type is defined as a CImg<T>*.
You may use it like this:
CImgList<> list;   // Assuming this image list is not empty.
for (CImgList<>::iterator it = list.begin(); it<list.end(); ++it) (*it).mirror('x');
Using the loop macro cimglist_for is another (more concise) alternative:
cimglist_for(list,l) list[l].mirror('x');
Definition at line 54643 of file CImg.h.
value_type
template<typename T> typedef T cimg_library_suffixed::CImgList< T >::value_type
Pixel value type.
Refer to the pixels value type of the images in the list.
Note
The CImgList<T>::value_type type of a CImgList<T> is defined to be a T. It is then similar to CImg<T>::value_type.
CImgList<T>::value_type is actually not used in CImg methods. It has been mainly defined for compatibility with STL naming conventions.
Definition at line 54662 of file CImg.h.
Constructor & Destructor Documentation
~CImgList()
template<typename T> cimg_library_suffixed::CImgList< T >::~CImgList () inline
Destructor.
Destroy current list instance.
Note
Any allocated buffer is deallocated.
Destroying an empty list does nothing actually.
Definition at line 54738 of file CImg.h.
CImgList() [1/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList () inline
Default constructor.
Construct a new empty list instance.
Note
An empty list has no pixel data and its dimension width() is set to 0, as well as its image buffer pointer data().
An empty list may be reassigned afterwards, with the family of the assign() methods. In all cases, the type of pixels stays T.
Definition at line 54751 of file CImg.h.
CImgList() [2/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const unsigned int n) inline explicit
Construct list containing empty images.
Parameters
n Number of empty images.
Note
Useful when you know by advance the number of images you want to manage, as it will allocate the right amount of memory for the list, without needs for reallocation (that may occur when starting from an empty list and inserting several images in it).
Definition at line 54761 of file CImg.h.
CImgList() [3/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const unsigned int n, const unsigned int width, const unsigned int height = 1, const unsigned int depth = 1, const unsigned int spectrum = 1) inline
Construct list containing images of specified size.
Parameters
n Number of images.
width Width of images.
height Height of images.
depth Depth of images.
spectrum Number of channels of images.
Note
Pixel values are not initialized and may probably contain garbage.
Definition at line 54775 of file CImg.h.
CImgList() [4/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const T & val) inline
Construct list containing images of specified size, and initialize pixel values.
Parameters
n Number of images.
width Width of images.
height Height of images.
depth Depth of images.
spectrum Number of channels of images.
val Initialization value for images pixels.
Definition at line 54791 of file CImg.h.
CImgList() [5/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const int val0, const int val1, ...) inline
Construct list containing images of specified size, and initialize pixel values from a sequence of integers.
Parameters
n Number of images.
width Width of images.
height Height of images.
depth Depth of images.
spectrum Number of channels of images.
val0 First value of the initializing integers sequence.
val1 Second value of the initializing integers sequence.
Warning
You must specify at least width*height*depth*spectrum values in your argument list, or you will probably segfault.
Definition at line 54810 of file CImg.h.
CImgList() [6/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const double val0, const double val1, ...) inline
Construct list containing images of specified size, and initialize pixel values from a sequence of doubles.
Parameters
n Number of images.
width Width of images.
height Height of images.
depth Depth of images.
spectrum Number of channels of images.
val0 First value of the initializing doubles sequence.
val1 Second value of the initializing doubles sequence.
Warning
You must specify at least width*height*depth*spectrum values in your argument list, or you will probably segfault.
Definition at line 54840 of file CImg.h.
CImgList() [7/19]
template<typename T> template<typename t > cimg_library_suffixed::CImgList< T >::CImgList (const unsigned int n, const CImg< t > & img, const bool is_shared = false) inline
Construct list containing copies of an input image.
Parameters
n Number of images.
img Input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of img.
Definition at line 54853 of file CImg.h.
CImgList() [8/19]
template<typename T> template<typename t > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t > & img, const bool is_shared = false) inline explicit
Construct list from one image.
Parameters
img Input image to copy in the constructed list.
is_shared Tells if the element of the list is a shared or non-shared copy of img.
Definition at line 54865 of file CImg.h.
CImgList() [9/19]
template<typename T> template<typename t1 , typename t2 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const bool is_shared = false) inline
Construct list from two images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54878 of file CImg.h.
CImgList() [10/19]
template<typename T> template<typename t1 , typename t2 , typename t3 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const bool is_shared = false) inline
Construct list from three images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
img3 Third input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54892 of file CImg.h.
CImgList() [11/19]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const bool is_shared = false) inline
Construct list from four images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
img3 Third input image to copy in the constructed list.
img4 Fourth input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54907 of file CImg.h.
CImgList() [12/19]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const bool is_shared = false) inline
Construct list from five images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
img3 Third input image to copy in the constructed list.
img4 Fourth input image to copy in the constructed list.
img5 Fifth input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54925 of file CImg.h.
CImgList() [13/19]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const CImg< t6 > & img6, const bool is_shared = false) inline
Construct list from six images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
img3 Third input image to copy in the constructed list.
img4 Fourth input image to copy in the constructed list.
img5 Fifth input image to copy in the constructed list.
img6 Sixth input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54944 of file CImg.h.
CImgList() [14/19]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const CImg< t6 > & img6, const CImg< t7 > & img7, const bool is_shared = false) inline
Construct list from seven images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
img3 Third input image to copy in the constructed list.
img4 Fourth input image to copy in the constructed list.
img5 Fifth input image to copy in the constructed list.
img6 Sixth input image to copy in the constructed list.
img7 Seventh input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54964 of file CImg.h.
CImgList() [15/19]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 , typename t8 > cimg_library_suffixed::CImgList< T >::CImgList (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const CImg< t6 > & img6, const CImg< t7 > & img7, const CImg< t8 > & img8, const bool is_shared = false) inline
Construct list from eight images.
Parameters
img1 First input image to copy in the constructed list.
img2 Second input image to copy in the constructed list.
img3 Third input image to copy in the constructed list.
img4 Fourth input image to copy in the constructed list.
img5 Fifth input image to copy in the constructed list.
img6 Sixth input image to copy in the constructed list.
img7 Seventh input image to copy in the constructed list.
img8 Eighth input image to copy in the constructed list.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 54986 of file CImg.h.
CImgList() [16/19]
template<typename T> template<typename t > cimg_library_suffixed::CImgList< T >::CImgList (const CImgList< t > & list) inline
Construct list copy.
Parameters
list Input list to copy.
Note
The shared state of each element of the constructed list is kept the same as in list.
Definition at line 55002 of file CImg.h.
CImgList() [17/19]
template<typename T> template<typename t > cimg_library_suffixed::CImgList< T >::CImgList (const CImgList< t > & list, const bool is_shared) inline
Construct list copy, and force the shared state of the list elements.
Parameters
list Input list to copy.
is_shared Tells if the elements of the list are shared or non-shared copies of input images.
Definition at line 55019 of file CImg.h.
CImgList() [18/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const char *const filename) inline explicit
Construct list by reading the content of a file.
Parameters
filename Filename, as a C-string.
Definition at line 55028 of file CImg.h.
CImgList() [19/19]
template<typename T> cimg_library_suffixed::CImgList< T >::CImgList (const CImgDisplay & disp) inline explicit
Construct list from the content of a display window.
Parameters
disp Display window to get content from.
Note
Constructed list contains a single image only.
Definition at line 55037 of file CImg.h.
Member Function Documentation
_cimglist_def_is_same3()
template<typename T> Y C C Z C cimg_library_suffixed::CImgList< T >::_cimglist_def_is_same3 (Y , Z , C) const
Test if dimensions of each image of the list match specified arguments.
Parameters
dx Checked image width.
dy Checked image height.
dz Checked image depth.
dc Checked image spectrum.
assign() [1/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign () inline
Destructor .
See also
CImgList().
Definition at line 55062 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::append_object3d(), cimg_library_suffixed::CImgList< charT >::assign(), cimg_library_suffixed::CImg< charT >::box3d(), cimg_library_suffixed::CImg< charT >::cone3d(), cimg_library_suffixed::CImg< charT >::cylinder3d(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::elevation3d(), cimg_library_suffixed::CImg< charT >::ellipsoid3d(), cimg_library_suffixed::CImgList< charT >::empty(), cimg_library_suffixed::CImgList< charT >::font(), cimg_library_suffixed::CImg< charT >::get_CImg3dtoobject3d(), cimg_library_suffixed::CImg< charT >::get_elevation3d(), cimg_library_suffixed::CImg< charT >::get_gradient(), cimg_library_suffixed::CImg< charT >::get_hessian(), cimg_library_suffixed::CImgList< charT >::get_images(), cimg_library_suffixed::CImg< charT >::get_isoline3d(), cimg_library_suffixed::CImg< charT >::get_isosurface3d(), cimg_library_suffixed::CImg< charT >::get_load_off(), cimg_library_suffixed::CImg< charT >::get_projections3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_shared(), cimg_library_suffixed::CImgList< charT >::get_shared_images(), cimg_library_suffixed::CImg< charT >::get_split(), cimg_library_suffixed::CImgList< charT >::get_unserialize(), cimg_library_suffixed::CImg< charT >::isoline3d(), cimg_library_suffixed::CImg< charT >::isosurface3d(), cimg_library_suffixed::CImgList< charT >::load_video(), cimg_library_suffixed::CImgList< charT >::move_to(), cimg_library_suffixed::CImg< charT >::plane3d(), cimg_library_suffixed::CImgList< charT >::save_video(), cimg_library_suffixed::CImg< charT >::sphere3d(), cimg_library_suffixed::CImg< charT >::texturize_object3d(), and cimg_library_suffixed::CImg< charT >::torus3d().
assign() [2/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const unsigned int n) inline
Construct list containing empty images .
See also
CImgList(unsigned int).
Definition at line 55082 of file CImg.h.
assign() [3/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const unsigned int n, const unsigned int width, const unsigned int height = 1, const unsigned int depth = 1, const unsigned int spectrum = 1) inline
Construct list containing images of specified size .
See also
CImgList(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int).
Definition at line 55096 of file CImg.h.
assign() [4/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const T & val) inline
Construct list containing images of specified size, and initialize pixel values .
See also
CImgList(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, const T).
Definition at line 55107 of file CImg.h.
assign() [5/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const int val0, const int val1, ...) inline
Construct list with images of specified size, and initialize pixel values from a sequence of integers .
See also
CImgList(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, const int, const int, ...).
Definition at line 55118 of file CImg.h.
assign() [6/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const unsigned int n, const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, const double val0, const double val1, ...) inline
Construct list with images of specified size, and initialize pixel values from a sequence of doubles .
See also
CImgList(unsigned int,unsigned int,unsigned int,unsigned int,unsigned int,const double,const double,...).
Definition at line 55128 of file CImg.h.
assign() [7/18]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const unsigned int n, const CImg< t > & img, const bool is_shared = false) inline
Construct list containing copies of an input image .
See also
CImgList(unsigned int, const CImg<t>&, bool).
Definition at line 55140 of file CImg.h.
assign() [8/18]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t > & img, const bool is_shared = false) inline
Construct list from one image .
See also
CImgList(const CImg<t>&, bool).
Definition at line 55151 of file CImg.h.
assign() [9/18]
template<typename T> template<typename t1 , typename t2 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const bool is_shared = false) inline
Construct list from two images .
See also
CImgList(const CImg<t>&, const CImg<t>&, bool).
Definition at line 55162 of file CImg.h.
assign() [10/18]
template<typename T> template<typename t1 , typename t2 , typename t3 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const bool is_shared = false) inline
Construct list from three images .
See also
CImgList(const CImg<t>&, const CImg<t>&, const CImg<t>&, bool).
Definition at line 55173 of file CImg.h.
assign() [11/18]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const bool is_shared = false) inline
Construct list from four images .
See also
CImgList(const CImg<t>&, const CImg<t>&, const CImg<t>&, const CImg<t>&, bool).
Definition at line 55184 of file CImg.h.
assign() [12/18]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const bool is_shared = false) inline
Construct list from five images .
See also
CImgList(const CImg<t>&, const CImg<t>&, const CImg<t>&, const CImg<t>&, const CImg<t>&, bool).
Definition at line 55197 of file CImg.h.
assign() [13/18]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const CImg< t6 > & img6, const bool is_shared = false) inline
Construct list from six images .
See also
CImgList(const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&, bool).
Definition at line 55210 of file CImg.h.
assign() [14/18]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const CImg< t6 > & img6, const CImg< t7 > & img7, const bool is_shared = false) inline
Construct list from seven images .
See also
CImgList(const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&, const CImg<t>&, bool).
Definition at line 55224 of file CImg.h.
assign() [15/18]
template<typename T> template<typename t1 , typename t2 , typename t3 , typename t4 , typename t5 , typename t6 , typename t7 , typename t8 > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImg< t1 > & img1, const CImg< t2 > & img2, const CImg< t3 > & img3, const CImg< t4 > & img4, const CImg< t5 > & img5, const CImg< t6 > & img6, const CImg< t7 > & img7, const CImg< t8 > & img8, const bool is_shared = false) inline
Construct list from eight images .
See also
CImgList(const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&,const CImg<t>&, const CImg<t>&, const CImg<t>&, bool).
Definition at line 55239 of file CImg.h.
assign() [16/18]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImgList< t > & list, const bool is_shared = false) inline
Construct list as a copy of an existing list and force the shared state of the list elements .
See also
CImgList(const CImgList<t>&, bool is_shared).
Definition at line 55254 of file CImg.h.
assign() [17/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const char *const filename) inline
Construct list by reading the content of a file .
See also
CImgList(const char *const).
Definition at line 55273 of file CImg.h.
assign() [18/18]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::assign (const CImgDisplay & disp) inline
Construct list from the content of a display window .
See also
CImgList(const CImgDisplay&).
Definition at line 55281 of file CImg.h.
at()
template<typename T> CImg<T>& cimg_library_suffixed::CImgList< T >::at (const int pos) inline
Return pos-th image of the list.
Parameters
pos Indice of the image element to access.
Definition at line 55646 of file CImg.h.
atN() [1/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atN (const int pos, const int x, const int y, const int z, const int c, const T & out_value) inline
Access to pixel value with Dirichlet boundary conditions for the coordinate (pos).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
out_value Default value returned if offset is outside image bounds.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55885 of file CImg.h.
atN() [2/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atN (const int pos, const int x = 0, const int y = 0, const int z = 0, const int c = 0) inline
Return pixel value with Neumann boundary conditions for the coordinate (pos).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55903 of file CImg.h.
atNX() [1/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNX (const int pos, const int x, const int y, const int z, const int c, const T & out_value) inline
Access to pixel value with Dirichlet boundary conditions for the 2 coordinates (pos,x).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
out_value Default value returned if offset is outside image bounds.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55830 of file CImg.h.
atNX() [2/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNX (const int pos, const int x, const int y = 0, const int z = 0, const int c = 0) inline
Access to pixel value with Neumann boundary conditions for the 2 coordinates (pos, x).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55848 of file CImg.h.
atNXY() [1/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNXY (const int pos, const int x, const int y, const int z, const int c, const T & out_value) inline
Access to pixel value with Dirichlet boundary conditions for the 3 coordinates (pos, x,y).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
out_value Default value returned if offset is outside image bounds.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55775 of file CImg.h.
atNXY() [2/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNXY (const int pos, const int x, const int y, const int z = 0, const int c = 0) inline
Access to pixel value with Neumann boundary conditions for the 3 coordinates (pos, x,y).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55793 of file CImg.h.
atNXYZ() [1/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNXYZ (const int pos, const int x, const int y, const int z, const int c, const T & out_value) inline
Access pixel value with Dirichlet boundary conditions for the 3 coordinates (pos, x,y,z).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
out_value Default value returned if offset is outside image bounds.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55720 of file CImg.h.
atNXYZ() [2/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNXYZ (const int pos, const int x, const int y, const int z, const int c = 0) inline
Access to pixel value with Neumann boundary conditions for the 4 coordinates (pos, x,y,z).
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
Note
list.atNXYZ(p,x,y,z,c); is equivalent to list[p].atXYZ(x,y,z,c);.
Definition at line 55738 of file CImg.h.
atNXYZC() [1/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNXYZC (const int pos, const int x, const int y, const int z, const int c, const T & out_value) inline
Access to pixel value with Dirichlet boundary conditions.
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
out_value Default value returned if offset is outside image bounds.
Note
list.atNXYZC(p,x,y,z,c); is equivalent to list[p].atXYZC(x,y,z,c);.
Definition at line 55665 of file CImg.h.
atNXYZC() [2/2]
template<typename T> T& cimg_library_suffixed::CImgList< T >::atNXYZC (const int pos, const int x, const int y, const int z, const int c) inline
Access to pixel value with Neumann boundary conditions.
Parameters
pos Indice of the image element to access.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
Note
list.atNXYZC(p,x,y,z,c); is equivalent to list[p].atXYZC(x,y,z,c);.
Definition at line 55683 of file CImg.h.
clear()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::clear () inline
Destructor .
Equivalent to assign().
Note
Only here for compatibility with STL naming conventions.
Definition at line 55074 of file CImg.h.
contains() [1/8]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::contains (const T & pixel, t & n, t & x, t & y, t & z, t & c) const inline
Test if one image of the list contains the specified referenced value.
Parameters
pixel Reference to pixel value to test.
[out] n Index of image containing the pixel value, if test succeeds.
[out] x X-coordinate of the pixel value, if test succeeds.
[out] y Y-coordinate of the pixel value, if test succeeds.
[out] z Z-coordinate of the pixel value, if test succeeds.
[out] c C-coordinate of the pixel value, if test succeeds.
Note
If true, set coordinates (n,x,y,z,c).
Definition at line 56092 of file CImg.h.
contains() [2/8]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::contains (const T & pixel, t & n, t & x, t & y, t & z) const inline
Test if one of the image list contains the specified referenced value.
Parameters
pixel Reference to pixel value to test.
[out] n Index of image containing the pixel value, if test succeeds.
[out] x X-coordinate of the pixel value, if test succeeds.
[out] y Y-coordinate of the pixel value, if test succeeds.
[out] z Z-coordinate of the pixel value, if test succeeds.
Note
If true, set coordinates (n,x,y,z).
Definition at line 56108 of file CImg.h.
contains() [3/8]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::contains (const T & pixel, t & n, t & x, t & y) const inline
Test if one of the image list contains the specified referenced value.
Parameters
pixel Reference to pixel value to test.
[out] n Index of image containing the pixel value, if test succeeds.
[out] x X-coordinate of the pixel value, if test succeeds.
[out] y Y-coordinate of the pixel value, if test succeeds.
Note
If true, set coordinates (n,x,y).
Definition at line 56122 of file CImg.h.
contains() [4/8]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::contains (const T & pixel, t & n, t & x) const inline
Test if one of the image list contains the specified referenced value.
Parameters
pixel Reference to pixel value to test.
[out] n Index of image containing the pixel value, if test succeeds.
[out] x X-coordinate of the pixel value, if test succeeds.
Note
If true, set coordinates (n,x).
Definition at line 56135 of file CImg.h.
contains() [5/8]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::contains (const T & pixel, t & n) const inline
Test if one of the image list contains the specified referenced value.
Parameters
pixel Reference to pixel value to test.
[out] n Index of image containing the pixel value, if test succeeds.
Note
If true, set coordinates (n).
Definition at line 56147 of file CImg.h.
contains() [6/8]
template<typename T> bool cimg_library_suffixed::CImgList< T >::contains (const T & pixel) const inline
Test if one of the image list contains the specified referenced value.
Parameters
pixel Reference to pixel value to test.
Definition at line 56156 of file CImg.h.
contains() [7/8]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::contains (const CImg< T > & img, t & n) const inline
Test if the list contains the image 'img'.
Parameters
img Reference to image to test.
[out] n Index of image in the list, if test succeeds.
Note
If true, returns the position (n) of the image in the list.
Definition at line 56168 of file CImg.h.
contains() [8/8]
template<typename T> bool cimg_library_suffixed::CImgList< T >::contains (const CImg< T > & img) const inline
Test if the list contains the image img.
Parameters
img Reference to image to test.
Definition at line 56179 of file CImg.h.
containsN()
template<typename T> bool cimg_library_suffixed::CImgList< T >::containsN (const int n) const inline
Test if list contains image with specified indice.
Parameters
n Index of the checked image.
Definition at line 56076 of file CImg.h.
containsNXYZC()
template<typename T> bool cimg_library_suffixed::CImgList< T >::containsNXYZC (const int n, const int x = 0, const int y = 0, const int z = 0, const int c = 0) const inline
Test if list contains one particular pixel location.
Parameters
n Index of the image whom checked pixel value belong to.
x X-coordinate of the checked pixel value.
y Y-coordinate of the checked pixel value.
z Z-coordinate of the checked pixel value.
c C-coordinate of the checked pixel value.
Definition at line 56066 of file CImg.h.
data() [1/2]
template<typename T> CImg<T>* cimg_library_suffixed::CImgList< T >::data () inline
Return pointer to the first image of the list.
Note
Images in a list are stored as a buffer of CImg<T>.
Definition at line 55556 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_hessian().
data() [2/2]
template<typename T> CImg<T>* cimg_library_suffixed::CImgList< T >::data (const unsigned int l) inline
Return pointer to the pos-th image of the list.
Parameters
pos Indice of the image element to access.
Note
list.data(n); is equivalent to list.data + n;.
Definition at line 55584 of file CImg.h.
display() [1/3]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::display (CImgDisplay & disp, const char axis = 'x', const float align = 0) const inline
Display the current CImgList instance in an existing CImgDisplay window (by reference).
Parameters
disp Reference to an existing CImgDisplay instance, where the current image list will be displayed.
axis Appending axis. Can be { 'x' | 'y' | 'z' | 'c' }.
align Appending alignmenet.
Note
This function displays the list images of the current CImgList instance into an existing CImgDisplay window. Images of the list are appended in a single temporarly image for visualization purposes. The function returns immediately.
Definition at line 58323 of file CImg.h.
display() [2/3]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::display (CImgDisplay & disp, const bool display_info, const char axis = 'x', const float align = 0, unsigned int *const XYZ = 0, const bool exit_on_anykey = false) const inline
Display the current CImgList instance in a new display window.
Parameters
disp Display window.
display_info Tells if image information are displayed on the standard output.
axis Alignment axis for images viewing.
align Apending alignment.
[in,out] XYZ Contains the XYZ coordinates at start / exit of the function.
exit_on_anykey Exit function when any key is pressed.
Note
This function opens a new window with a specific title and displays the list images of the current CImgList instance into it. Images of the list are appended in a single temporarly image for visualization purposes. The function returns when a key is pressed or the display window is closed by the user.
Definition at line 58341 of file CImg.h.
display() [3/3]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::display (const char *const title = 0, const bool display_info = true, const char axis = 'x', const float align = 0, unsigned int *const XYZ = 0, const bool exit_on_anykey = false) const inline
Display the current CImgList instance in a new display window.
Parameters
title Title of the opening display window.
display_info Tells if list information must be written on standard output.
axis Appending axis. Can be { 'x' | 'y' | 'z' | 'c' }.
align Appending alignment.
[in,out] XYZ Contains the XYZ coordinates at start / exit of the function.
exit_on_anykey Exit function when any key is pressed.
Definition at line 58357 of file CImg.h.
empty()
template<typename T> static CImgList<T>& cimg_library_suffixed::CImgList< T >::empty () inline static
Return a reference to an empty list.
Note
Can be used to define default values in a function taking a CImgList<T> as an argument.
void f(const CImgList<char>& list=CImgList<char>::empty());
Definition at line 55339 of file CImg.h.
erase()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::erase (const iterator iter) inline
Remove image pointed by iterator.
Parameters
iter Iterator pointing to the image to remove.
Definition at line 56851 of file CImg.h.
FFT() [1/2]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::FFT (const char axis, const bool invert = false) inline
Compute a 1d Fast Fourier Transform, along specified axis.
Parameters
axis Axis along which the Fourier transform is computed.
invert Tells if the direct (false) or inverse transform (true) is computed.
Definition at line 59529 of file CImg.h.
FFT() [2/2]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::FFT (const bool invert = false) inline
Compute a n-d Fast Fourier Transform.
Parameters
invert Tells if the direct (false) or inverse transform (true) is computed.
Definition at line 59550 of file CImg.h.
font()
template<typename T> static const CImgList<ucharT>& cimg_library_suffixed::CImgList< T >::font (const unsigned int font_height, const bool is_variable_width = true) inline static
Return a CImg pre-defined font with desired size.
Parameters
font_height Height of the desired font (exact match for 13,23,53,103).
is_variable_width Decide if the font has a variable (true) or fixed (false) width.
Definition at line 59453 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::draw_text().
get_append()
template<typename T> CImg<T> cimg_library_suffixed::CImgList< T >::get_append (const char axis, const float align = 0) const inline
Return a single image which is the appending of all images of the current CImgList instance.
Parameters
axis Appending axis. Can be { 'x' | 'y' | 'z' | 'c' }.
align Appending alignment.
Definition at line 56687 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::append(), cimg_library_suffixed::CImgDisplay::display(), cimg_library_suffixed::CImg< charT >::get_append(), cimg_library_suffixed::CImg< charT >::get_load_ffmpeg_external(), cimg_library_suffixed::CImg< charT >::get_load_gif_external(), cimg_library_suffixed::CImg< charT >::get_load_video(), cimg_library_suffixed::CImg< charT >::get_load_yuv(), cimg_library_suffixed::CImg< charT >::load_cimg(), and cimg_library_suffixed::CImg< charT >::load_parrec().
get_select() [1/2]
template<typename T> CImg<intT> cimg_library_suffixed::CImgList< T >::get_select (CImgDisplay & disp, const bool feature_type = true, const char axis = 'x', const float align = 0, const bool exit_on_anykey = false) const inline
Display a simple interactive interface to select images or sublists.
Parameters
disp Window instance to display selection and user interface.
feature_type Can be false to select a single image, or true to select a sublist.
axis Axis along whom images are appended for visualization.
align Alignment setting when images have not all the same size.
exit_on_anykey Exit function when any key is pressed.
Returns
A one-column vector containing the selected image indexes.
Definition at line 56871 of file CImg.h.
get_select() [2/2]
template<typename T> CImg<intT> cimg_library_suffixed::CImgList< T >::get_select (const char *const title, const bool feature_type = true, const char axis = 'x', const float align = 0, const bool exit_on_anykey = false) const inline
Display a simple interactive interface to select images or sublists.
Parameters
title Title of a new window used to display selection and user interface.
feature_type Can be false to select a single image, or true to select a sublist.
axis Axis along whom images are appended for visualization.
align Alignment setting when images have not all the same size.
exit_on_anykey Exit function when any key is pressed.
Returns
A one-column vector containing the selected image indexes.
Definition at line 56886 of file CImg.h.
get_serialize()
template<typename T> CImg<ucharT> cimg_library_suffixed::CImgList< T >::get_serialize (const bool is_compressed = false) const inline
Serialize a CImgList<T> instance into a raw CImg<unsigned char> buffer.
Parameters
is_compressed tells if zlib compression must be used for serialization (this requires 'cimg_use_zlib' been enabled).
Definition at line 59265 of file CImg.h.
get_shared()
template<typename T> CImgList<T> cimg_library_suffixed::CImgList< T >::get_shared () inline
Return a list with elements being shared copies of images in the list instance.
Note
list2 = list1.get_shared() is equivalent to list2.assign(list1,true).
Definition at line 55045 of file CImg.h.
get_shared_images()
template<typename T> CImgList<T> cimg_library_suffixed::CImgList< T >::get_shared_images (const unsigned int pos0, const unsigned int pos1) inline
Return a shared sublist.
Parameters
pos0 Starting index of the sublist.
pos1 Ending index of the sublist.
Definition at line 56659 of file CImg.h.
Referenced by cimg_library_suffixed::CImgList< charT >::display().
images()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::images (const unsigned int pos0, const unsigned int pos1) inline
Return a sublist.
Parameters
pos0 Starting index of the sublist.
pos1 Ending index of the sublist.
Definition at line 56638 of file CImg.h.
insert() [1/5]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::insert (const CImg< t > & img, const unsigned int pos = ~0U, const bool is_shared = false) inline
Insert a copy of the image img into the current image list, at position pos.
Parameters
img Image to insert a copy to the list.
pos Index of the insertion.
is_shared Tells if the inserted image is a shared copy of img or not.
Definition at line 56362 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::append_object3d(), cimg_library_suffixed::CImgList< charT >::font(), cimg_library_suffixed::CImg< charT >::get_gradient(), cimg_library_suffixed::CImgList< charT >::get_insert(), cimg_library_suffixed::CImg< charT >::get_load_off(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_serialize(), cimg_library_suffixed::CImg< charT >::move_to(), cimg_library_suffixed::CImgList< charT >::move_to(), and cimg_library_suffixed::CImgList< charT >::operator,().
insert() [2/5]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::insert (const unsigned int n, const unsigned int pos = ~0U) inline
Insert n empty images img into the current image list, at position pos.
Parameters
n Number of empty images to insert.
pos Index of the insertion.
Definition at line 56469 of file CImg.h.
insert() [3/5]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::insert (const unsigned int n, const CImg< t > & img, const unsigned int pos = ~0U, const bool is_shared = false) inline
Insert n copies of the image img into the current image list, at position pos.
Parameters
n Number of image copies to insert.
img Image to insert by copy.
pos Index of the insertion.
is_shared Tells if inserted images are shared copies of img or not.
Definition at line 56490 of file CImg.h.
insert() [4/5]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::insert (const CImgList< t > & list, const unsigned int pos = ~0U, const bool is_shared = false) inline
Insert a copy of the image list list into the current image list, starting from position pos.
Parameters
list Image list to insert.
pos Index of the insertion.
is_shared Tells if inserted images are shared copies of images of list or not.
Definition at line 56513 of file CImg.h.
insert() [5/5]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::insert (const unsigned int n, const CImgList< t > & list, const unsigned int pos = ~0U, const bool is_shared = false) inline
Insert n copies of the list list at position pos of the current list.
Parameters
n Number of list copies to insert.
list Image list to insert.
pos Index of the insertion.
is_shared Tells if inserted images are shared copies of images of list or not.
Definition at line 56534 of file CImg.h.
is_sameN() [1/2]
template<typename T> bool cimg_library_suffixed::CImgList< T >::is_sameN (const unsigned int size_n) const inline
Test if number of image elements is equal to specified value.
Parameters
size_n Number of image elements to test.
Definition at line 55946 of file CImg.h.
is_sameN() [2/2]
template<typename T> template<typename t > bool cimg_library_suffixed::CImgList< T >::is_sameN (const CImgList< t > & list) const inline
Test if number of image elements is equal between two images lists.
Parameters
list Input list to compare with.
Definition at line 55955 of file CImg.h.
is_sameNXYZC()
template<typename T> bool cimg_library_suffixed::CImgList< T >::is_sameNXYZC (const unsigned int n, const unsigned int dx, const unsigned int dy, const unsigned int dz, const unsigned int dc) const inline
Test if list dimensions match specified arguments.
Parameters
n Number of images in the list.
dx Checked image width.
dy Checked image height.
dz Checked image depth.
dc Checked image spectrum.
Definition at line 56052 of file CImg.h.
is_saveable()
template<typename T> static bool cimg_library_suffixed::CImgList< T >::is_saveable (const char *const filename) inline static
Tell if an image list can be saved as one single file.
Parameters
filename Filename, as a C-string.
Returns
true if the file format supports multiple images, false otherwise.
Definition at line 58561 of file CImg.h.
load()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load (const char *const filename) inline
Load a list from a file.
Parameters
filename Filename to read data from.
Definition at line 57135 of file CImg.h.
load_cimg() [1/3]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_cimg (const char *const filename) inline
Load a list from a .cimg file.
Parameters
filename Filename to read data from.
Definition at line 57263 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::load_cimg().
load_cimg() [2/3]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_cimg (std::FILE *const file) inline
Load a list from a .cimg file.
Parameters
file File to read data from.
Definition at line 57276 of file CImg.h.
load_cimg() [3/3]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_cimg (const char *const filename, const unsigned int n0, const unsigned int n1, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0, const unsigned int x1, const unsigned int y1, const unsigned int z1, const unsigned int c1) inline
Load a sublist list from a (non compressed) .cimg file.
Parameters
filename Filename to read data from.
n0 Starting index of images to read (~0U for max).
n1 Ending index of images to read (~0U for max).
x0 Starting X-coordinates of image regions to read.
y0 Starting Y-coordinates of image regions to read.
z0 Starting Z-coordinates of image regions to read.
c0 Starting C-coordinates of image regions to read.
x1 Ending X-coordinates of image regions to read (~0U for max).
y1 Ending Y-coordinates of image regions to read (~0U for max).
z1 Ending Z-coordinates of image regions to read (~0U for max).
c1 Ending C-coordinates of image regions to read (~0U for max).
Definition at line 57408 of file CImg.h.
load_ffmpeg_external()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_ffmpeg_external (const char *const filename) inline
Load an image from a video file using the external tool 'ffmpeg'.
Parameters
filename Filename to read data from.
Definition at line 58021 of file CImg.h.
load_gif_external()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_gif_external (const char *const filename) inline
Load gif file, using ImageMagick or GraphicsMagick's external tools.
Parameters
filename Filename to read data from.
Definition at line 58070 of file CImg.h.
load_gzip_external()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_gzip_external (const char *const filename) inline
Load a gzipped list, using external tool 'gunzip'.
Parameters
filename Filename to read data from.
Definition at line 58139 of file CImg.h.
load_off()
template<typename T> template<typename tf , typename tc > CImgList<T>& cimg_library_suffixed::CImgList< T >::load_off (const char *const filename, CImgList< tf > & primitives, CImgList< tc > & colors) inline
Load a 3d object from a .OFF file.
Parameters
filename Filename to read data from.
[out] primitives At return, contains the list of 3d object primitives.
[out] colors At return, contains the list of 3d object colors.
Returns
List of 3d object vertices.
Definition at line 58195 of file CImg.h.
load_parrec()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_parrec (const char *const filename) inline
Load a list from a PAR/REC (Philips) file.
Parameters
filename Filename to read data from.
Definition at line 57584 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::load_parrec().
load_tiff()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_tiff (const char *const filename, const unsigned int first_frame = 0, const unsigned int last_frame = ~0U, const unsigned int step_frame = 1, float *const voxel_size = 0, CImg< charT > *const description = 0) inline
Load images from a TIFF file.
Parameters
filename Filename to read data from.
first_frame Index of first image frame to read.
last_frame Index of last image frame to read.
step_frame Step applied between each frame.
[out] voxel_size Voxel size, as stored in the filename.
[out] description Description, as stored in the filename.
Definition at line 58216 of file CImg.h.
load_video()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_video (const char *const filename, const unsigned int first_frame = 0, const unsigned int last_frame = ~0U, const unsigned int step_frame = 1) inline
Load an image from a video file, using OpenCV library.
Parameters
filename Filename, as a C-string.
first_frame Index of the first frame to read.
last_frame Index of the last frame to read.
step_frame Step value for frame reading.
Note
If step_frame==0, the current video stream is forced to be released (without any frames read).
Definition at line 57864 of file CImg.h.
load_yuv()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::load_yuv (const char *const filename, const unsigned int size_x, const unsigned int size_y, const unsigned int chroma_subsampling = 444, const unsigned int first_frame = 0, const unsigned int last_frame = ~0U, const unsigned int step_frame = 1, const bool yuv2rgb = true) inline
Load a list from a YUV image sequence file.
Parameters
filename Filename to read data from.
size_x Width of the images.
size_y Height of the images.
chroma_subsampling Type of chroma subsampling. Can be { 420 | 422 | 444 }.
first_frame Index of first image frame to read.
last_frame Index of last image frame to read.
step_frame Step applied between each frame.
yuv2rgb Apply YUV to RGB transformation during reading.
Definition at line 57708 of file CImg.h.
max_min()
template<typename T> template<typename t > T& cimg_library_suffixed::CImgList< T >::max_min (t & min_val) inline
Return a reference to the minimum pixel value of the instance list and return the minimum value as well.
Parameters
[out] min_val Value of the minimum value found.
Definition at line 56308 of file CImg.h.
min_max() [1/2]
template<typename T> template<typename t > T& cimg_library_suffixed::CImgList< T >::min_max (t & max_val) inline
Return a reference to the minimum pixel value of the instance list and return the maximum vvalue as well.
Parameters
[out] max_val Value of the maximum value found.
Definition at line 56260 of file CImg.h.
min_max() [2/2]
template<typename T> template<typename t > const T& cimg_library_suffixed::CImgList< T >::min_max (t & max_val) const inline
Return a reference to the minimum pixel value of the instance list and return the maximum vvalue as well .
Parameters
[out] max_val Value of the maximum value found.
Definition at line 56284 of file CImg.h.
move_to() [1/2]
template<typename T> template<typename t > CImgList<t>& cimg_library_suffixed::CImgList< T >::move_to (CImgList< t > & list) inline
Transfer the content of the list instance to another list.
Parameters
list Destination list.
Note
When returning, the current list instance is empty and the initial content of list is destroyed.
Definition at line 55291 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::append(), cimg_library_suffixed::CImgList< charT >::assign(), cimg_library_suffixed::CImgList< charT >::crop_font(), cimg_library_suffixed::CImgList< charT >::images(), cimg_library_suffixed::CImg< charT >::load_cimg(), cimg_library_suffixed::CImgList< charT >::load_off(), cimg_library_suffixed::CImg< charT >::load_parrec(), cimg_library_suffixed::CImg< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImg< charT >::save_video(), and cimg_library_suffixed::CImgList< charT >::split().
move_to() [2/2]
template<typename T> template<typename t > CImgList<t>& cimg_library_suffixed::CImgList< T >::move_to (CImgList< t > & list, const unsigned int pos) inline
Transfer the content of the list instance at a specified position in another list.
Parameters
list Destination list.
pos Index of the insertion in the list.
Note
When returning, the list instance is empty and the initial content of list is preserved (only images indexes may be modified).
Definition at line 55309 of file CImg.h.
operator CImg< T > *()
template<typename T> cimg_library_suffixed::CImgList< T >::operator CImg< T > * () inline
Return pointer to the first image of the list.
Note
Images in a list are stored as a buffer of CImg<T>.
Definition at line 55406 of file CImg.h.
operator()() [1/3]
template<typename T> CImg<T>& cimg_library_suffixed::CImgList< T >::operator() (const unsigned int pos) inline
Return a reference to one image element of the list.
Parameters
pos Indice of the image element.
Definition at line 55361 of file CImg.h.
operator()() [2/3]
template<typename T> const CImg<T>& cimg_library_suffixed::CImgList< T >::operator() (const unsigned int pos) const inline
Return a reference to one image of the list.
Parameters
pos Indice of the image element.
Definition at line 55378 of file CImg.h.
operator()() [3/3]
template<typename T> T& cimg_library_suffixed::CImgList< T >::operator() (const unsigned int pos, const unsigned int x, const unsigned int y = 0, const unsigned int z = 0, const unsigned int c = 0) inline
Return a reference to one pixel value of one image of the list.
Parameters
pos Indice of the image element.
x X-coordinate of the pixel value.
y Y-coordinate of the pixel value.
z Z-coordinate of the pixel value.
c C-coordinate of the pixel value.
Note
list(n,x,y,z,c) is equivalent to list[n](x,y,z,c).
Definition at line 55391 of file CImg.h.
operator+()
template<typename T> CImgList<T> cimg_library_suffixed::CImgList< T >::operator+ () const inline
Return a non-shared copy of a list.
Note
+list is equivalent to CImgList<T>(list,false). It forces the copy to have non-shared elements.
Definition at line 55461 of file CImg.h.
operator,() [1/2]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::operator, (const CImg< t > & img) inline
Return a copy of the list instance, where image img has been inserted at the end.
Parameters
img Image inserted at the end of the instance copy.
Note
Define a convenient way to create temporary lists of images, as in the following code:
(img1,img2,img3,img4).display("My four images");
Definition at line 55474 of file CImg.h.
operator,() [2/2]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::operator, (const CImgList< t > & list) inline
Return a copy of the list instance, where all elements of input list list have been inserted at the end.
Parameters
list List inserted at the end of the instance copy.
Definition at line 55489 of file CImg.h.
operator<()
template<typename T> CImgList<T> cimg_library_suffixed::CImgList< T >::operator< (const char axis) const inline
Return list corresponding to the splitting of all images of the instance list along specified axis.
Parameters
axis Axis used for image splitting.
Note
list<'x' is equivalent to list.get_split('x').
Definition at line 55513 of file CImg.h.
operator=() [1/4]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::operator= (const CImg< t > & img) inline
Construct list from one image .
Parameters
img Input image to copy in the constructed list.
Note
list = img; is equivalent to list.assign(img);.
Definition at line 55421 of file CImg.h.
operator=() [2/4]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::operator= (const CImgList< t > & list) inline
Construct list from another list.
Parameters
list Input list to copy.
Note
list1 = list2 is equivalent to list1.assign(list2);.
Definition at line 55431 of file CImg.h.
operator=() [3/4]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::operator= (const char *const filename) inline
Construct list by reading the content of a file .
See also
CImgList(const char *const).
Definition at line 55444 of file CImg.h.
operator=() [4/4]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::operator= (const CImgDisplay & disp) inline
Construct list from the content of a display window .
See also
CImgList(const CImgDisplay&).
Definition at line 55452 of file CImg.h.
operator>()
template<typename T> CImg<T> cimg_library_suffixed::CImgList< T >::operator> (const char axis) const inline
Return image corresponding to the appending of all images of the instance list along specified axis.
Parameters
axis Appending axis. Can be { 'x' | 'y' | 'z' | 'c' }.
Note
list>'x' is equivalent to list.get_append('x').
Definition at line 55504 of file CImg.h.
pixel_type()
template<typename T> static const char* cimg_library_suffixed::CImgList< T >::pixel_type () inline static
Return the type of image pixel values as a C string.
Return a char* string containing the usual type name of the image pixel values (i.e. a stringified version of the template parameter T).
Note
The returned string may contain spaces (as in "unsigned char").
If the pixel type T does not correspond to a registered type, the string "unknown" is returned.
Definition at line 55532 of file CImg.h.
print()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::print (const char *const title = 0, const bool display_stats = true) const inline
Print information about the list on the standard output.
Parameters
title Label set to the information displayed.
display_stats Tells if image statistics must be computed and displayed.
Definition at line 58285 of file CImg.h.
push_back() [1/2]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::push_back (const CImg< t > & img) inline
Insert image at the end of the list.
Parameters
img Image to insert.
Definition at line 56802 of file CImg.h.
push_back() [2/2]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::push_back (const CImgList< t > & list) inline
Insert list at the end of the current list.
Parameters
list List to insert.
Definition at line 56820 of file CImg.h.
push_front() [1/2]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::push_front (const CImg< t > & img) inline
Insert image at the front of the list.
Parameters
img Image to insert.
Definition at line 56811 of file CImg.h.
push_front() [2/2]
template<typename T> template<typename t > CImgList<T>& cimg_library_suffixed::CImgList< T >::push_front (const CImgList< t > & list) inline
Insert list at the front of the current list.
Parameters
list List to insert.
Definition at line 56829 of file CImg.h.
remove() [1/2]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::remove (const unsigned int pos1, const unsigned int pos2) inline
Remove all images between from indexes.
Parameters
pos1 Starting index of the removal.
pos2 Ending index of the removal.
Definition at line 56554 of file CImg.h.
Referenced by cimg_library_suffixed::CImgList< charT >::get_remove(), and cimg_library_suffixed::CImg< charT >::sphere3d().
remove() [2/2]
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::remove (const unsigned int pos) inline
Remove image at index pos from the image list.
Parameters
pos Index of the image to remove.
Definition at line 56601 of file CImg.h.
save()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save (const char *const filename, const int number = -1, const unsigned int digits = 6) const inline
Save list into a file.
Parameters
filename Filename to write data to.
number When positive, represents an index added to the filename. Otherwise, no number is added.
digits Number of digits used for adding the number to the filename.
Definition at line 58479 of file CImg.h.
save_cimg() [1/4]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_cimg (const char *const filename, const bool is_compressed = false) const inline
Save list into a .cimg file.
Parameters
filename Filename to write data to.
is_compressed Tells if data compression must be enabled.
Definition at line 58720 of file CImg.h.
save_cimg() [2/4]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_cimg (std::FILE * file, const bool is_compressed = false) const inline
Save list into a .cimg file.
Parameters
file File to write data to.
is_compressed Tells if data compression must be enabled.
Definition at line 58782 of file CImg.h.
save_cimg() [3/4]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_cimg (const char *const filename, const unsigned int n0, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0) const inline
Insert the image instance into into an existing .cimg file, at specified coordinates.
Parameters
filename Filename to write data to.
n0 Starting index of images to write.
x0 Starting X-coordinates of image regions to write.
y0 Starting Y-coordinates of image regions to write.
z0 Starting Z-coordinates of image regions to write.
c0 Starting C-coordinates of image regions to write.
Definition at line 58910 of file CImg.h.
save_cimg() [4/4]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_cimg (std::FILE *const file, const unsigned int n0, const unsigned int x0, const unsigned int y0, const unsigned int z0, const unsigned int c0) const inline
Insert the image instance into into an existing .cimg file, at specified coordinates.
Parameters
file File to write data to.
n0 Starting index of images to write.
x0 Starting X-coordinates of image regions to write.
y0 Starting Y-coordinates of image regions to write.
z0 Starting Z-coordinates of image regions to write.
c0 Starting C-coordinates of image regions to write.
Definition at line 58926 of file CImg.h.
save_empty_cimg() [1/2]
template<typename T> static void cimg_library_suffixed::CImgList< T >::save_empty_cimg (const char *const filename, const unsigned int nb, const unsigned int dx, const unsigned int dy = 1, const unsigned int dz = 1, const unsigned int dc = 1) inline static
Save empty (non-compressed) .cimg file with specified dimensions.
Parameters
filename Filename to write data to.
nb Number of images to write.
dx Width of images in the written file.
dy Height of images in the written file.
dz Depth of images in the written file.
dc Spectrum of images in the written file.
Definition at line 58956 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::save_empty_cimg().
save_empty_cimg() [2/2]
template<typename T> static void cimg_library_suffixed::CImgList< T >::save_empty_cimg (std::FILE *const file, const unsigned int nb, const unsigned int dx, const unsigned int dy = 1, const unsigned int dz = 1, const unsigned int dc = 1) inline static
Save empty .cimg file with specified dimensions.
Parameters
file File to write data to.
nb Number of images to write.
dx Width of images in the written file.
dy Height of images in the written file.
dz Depth of images in the written file.
dc Spectrum of images in the written file.
Definition at line 58972 of file CImg.h.
save_ffmpeg_external()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_ffmpeg_external (const char *const filename, const unsigned int fps = 25, const char *const codec = 0, const unsigned int bitrate = 2048) const inline
Save image sequence, using the external tool 'ffmpeg'.
Parameters
filename Filename to write data to.
fps Number of frames per second.
codec Type of compression.
bitrate Output bitrate
Definition at line 59211 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::save_ffmpeg_external().
save_gif_external()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_gif_external (const char *const filename, const float fps = 25, const unsigned int nb_loops = 0) inline
Save image sequence as a GIF animated file.
Parameters
filename Filename to write data to.
fps Number of desired frames per second.
nb_loops Number of loops (0 for infinite looping).
Definition at line 58601 of file CImg.h.
save_gzip_external()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_gzip_external (const char *const filename) const inline
Save list as a gzipped file, using external tool 'gzip'.
Parameters
filename Filename to write data to.
Definition at line 59027 of file CImg.h.
save_tiff()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_tiff (const char *const filename, const unsigned int compression_type = 0, const float *const voxel_size = 0, const char *const description = 0, const bool use_bigtiff = true) const inline
Save list as a TIFF file.
Parameters
filename Filename to write data to.
compression_type Compression mode used to write data.
voxel_size Voxel size, to be stored in the filename.
description Description, to be stored in the filename.
use_bigtiff Allow to save big tiff files (>4Gb).
Definition at line 58987 of file CImg.h.
save_video()
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_video (const char *const filename, const unsigned int fps = 25, const char * codec = 0, const bool keep_open = false) const inline
Save image sequence, using the OpenCV library.
Parameters
filename Filename to write data to.
fps Number of frames per second.
codec Type of compression (See http://www.fourcc.org/codecs.php to see available codecs).
keep_open Tells if the video writer associated to the specified filename must be kept open or not (to allow frames to be added in the same file afterwards).
Definition at line 59086 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::save_video().
save_yuv() [1/2]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_yuv (const char *const filename = 0, const unsigned int chroma_subsampling = 444, const bool is_rgb = true) const inline
Save list as a YUV image sequence file.
Parameters
filename Filename to write data to.
chroma_subsampling Type of chroma subsampling. Can be { 420 | 422 | 444 }.
is_rgb Tells if the RGB to YUV conversion must be done for saving.
Definition at line 58653 of file CImg.h.
save_yuv() [2/2]
template<typename T> const CImgList<T>& cimg_library_suffixed::CImgList< T >::save_yuv (std::FILE *const file, const unsigned int chroma_subsampling = 444, const bool is_rgb = true) const inline
Save image sequence into a YUV file.
Parameters
file File to write data to.
chroma_subsampling Type of chroma subsampling. Can be { 420 | 422 | 444 }.
is_rgb Tells if the RGB to YUV conversion must be done for saving.
Definition at line 58665 of file CImg.h.
size()
template<typename T> unsigned int cimg_library_suffixed::CImgList< T >::size () const inline
Return the size of the list, i.e. the number of images contained in it.
Note
Similar to width() but returns result as an unsigned integer.
Definition at line 55548 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::draw_object3d(), cimg_library_suffixed::CImgList< charT >::get_crop_font(), cimg_library_suffixed::CImg< charT >::get_object3dtoCImg3d(), and cimg_library_suffixed::CImg< charT >::save_off().
split()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::split (const char axis, const int nb = -1) inline
Return a list where each image has been split along the specified axis.
Parameters
axis Axis to split images along.
nb Number of spliting parts for each image.
Definition at line 56786 of file CImg.h.
swap()
template<typename T> CImgList<T>& cimg_library_suffixed::CImgList< T >::swap (CImgList< T > & list) inline
Swap all fields between two list instances.
Parameters
list List to swap fields with.
Note
Can be used to exchange the content of two lists in a fast way.
Definition at line 55326 of file CImg.h.
Referenced by cimg_library_suffixed::CImgList< charT >::reverse().
width()
template<typename T> int cimg_library_suffixed::CImgList< T >::width () const inline
Return the size of the list, i.e. the number of images contained in it.
Note
Similar to size() but returns result as a (signed) integer.
Definition at line 55540 of file CImg.h.
Referenced by cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::draw_object3d(), cimg_library_suffixed::CImg< charT >::draw_text(), cimg_library_suffixed::CImg< charT >::get_object3dtoCImg3d(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImg< charT >::isoline3d(), cimg_library_suffixed::CImg< charT >::isosurface3d(), cimg_library_suffixed::CImg< charT >::save_off(), and cimg_library_suffixed::CImg< charT >::sphere3d().
Member Data Documentation
const
template<typename T> Y C C Z C const unsigned int const unsigned int const unsigned int dc cimg_library_suffixed::CImgList< T >::const
Initial value:
{
      bool res = true
Definition at line 56038 of file CImg.h.
The documentation for this struct was generated from the following file:
deps/CImg.h