jubilant-funicular: GLM_GTC_constants
GLM_GTC_constants
Stable extensions
Functions
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::epsilon ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::zero ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::half_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::three_over_two_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::quarter_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_two_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_over_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::four_over_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_over_root_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_root_two ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_half_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_two_pi ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_ln_four ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::e ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::euler ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_two ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_three ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_five ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_two ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_ten ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_ln_two ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::third ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_thirds ()
template<typename genType >
GLM_FUNC_DECL GLM_CONSTEXPR genType glm::golden_ratio ()
Detailed Description
Include <glm/gtc/constants.hpp> to use the features of this extension.
Provide a list of constants and precomputed useful values.
Function Documentation
e()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::e ()
#include <deps/glm/gtc/constants.hpp>
Return e constant.
See also
GLM_GTC_constants
Definition at line 117 of file constants.inl.
Referenced by cimg_library_suffixed::CImg< charT >::blur_anisotropic(), nta::CallbackManager::delay(), nta::CallbackManager::dequeue(), cimg_library_suffixed::CImg< charT >::det(), cimg_library_suffixed::CImg< charT >::diffusion_tensors(), nta::CallbackManager::dispatch(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::distance_eikonal(), cimg_library_suffixed::CImg< charT >::draw_ellipse(), cimg_library_suffixed::CImg< charT >::draw_gaussian(), cimg_library_suffixed::CImg< charT >::draw_object3d(), cimg_library_suffixed::CImg< charT >::draw_spline(), cimg_library_suffixed::CImg< charT >::eigen(), cimg_library_suffixed::CImg< charT >::get_displacement(), cimg_library_suffixed::CImg< charT >::get_patchmatch(), cimg_library_suffixed::CImg< charT >::get_pseudoinvert(), cimg_library_suffixed::CImg< charT >::get_SVD(), cimg_library_suffixed::CImg< charT >::invert(), cimg_library_suffixed::cimg::prand(), nta::CallbackManager::setInterval(), cimg_library_suffixed::CImg< charT >::solve_tridiagonal(), and cimg_library_suffixed::CImg< charT >::SVD().
epsilon()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::epsilon ()
#include <deps/glm/gtc/constants.hpp>
Return the epsilon constant for floating point types.
See also
GLM_GTC_constants
Definition at line 9 of file constants.inl.
Referenced by glm::intersectLineSphere(), glm::intersectLineTriangle(), glm::intersectRaySphere(), and cimg_library_suffixed::CImg< charT >::solve_tridiagonal().
euler()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::euler ()
#include <deps/glm/gtc/constants.hpp>
Return Euler's constant.
See also
GLM_GTC_constants
Definition at line 123 of file constants.inl.
four_over_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::four_over_pi ()
#include <deps/glm/gtc/constants.hpp>
Return 4 / pi.
See also
GLM_GTC_constants
Definition at line 81 of file constants.inl.
golden_ratio()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::golden_ratio ()
#include <deps/glm/gtc/constants.hpp>
Return the golden ratio constant.
See also
GLM_GTC_constants
Definition at line 177 of file constants.inl.
half_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::half_pi ()
#include <deps/glm/gtc/constants.hpp>
Return pi / 2.
See also
GLM_GTC_constants
Definition at line 45 of file constants.inl.
ln_ln_two()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_ln_two ()
#include <deps/glm/gtc/constants.hpp>
Return ln(ln(2)).
See also
GLM_GTC_constants
Definition at line 159 of file constants.inl.
ln_ten()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_ten ()
#include <deps/glm/gtc/constants.hpp>
Return ln(10).
See also
GLM_GTC_constants
Definition at line 153 of file constants.inl.
ln_two()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_two ()
#include <deps/glm/gtc/constants.hpp>
Return ln(2).
See also
GLM_GTC_constants
Definition at line 147 of file constants.inl.
one()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one ()
#include <deps/glm/gtc/constants.hpp>
Return 1.
See also
GLM_GTC_constants
Definition at line 21 of file constants.inl.
Referenced by cimg_library_suffixed::CImg< charT >::draw_triangle(), cimg_library_suffixed::CImg< charT >::get_select_graph(), and cimg_library_suffixed::cimg::info().
one_over_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_pi ()
#include <deps/glm/gtc/constants.hpp>
Return 1 / pi.
See also
GLM_GTC_constants
Definition at line 63 of file constants.inl.
one_over_root_two()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_root_two ()
#include <deps/glm/gtc/constants.hpp>
Return 1 / sqrt(2).
See also
GLM_GTC_constants
Definition at line 93 of file constants.inl.
one_over_two_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_two_pi ()
#include <deps/glm/gtc/constants.hpp>
Return 1 / (pi * 2).
See also
GLM_GTC_constants
Definition at line 69 of file constants.inl.
pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::pi ()
#include <deps/glm/gtc/constants.hpp>
Return the pi constant.
See also
GLM_GTC_constants
Definition at line 27 of file constants.inl.
Referenced by cimg_library_suffixed::cimg::system().
quarter_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::quarter_pi ()
#include <deps/glm/gtc/constants.hpp>
Return pi / 4.
See also
GLM_GTC_constants
Definition at line 57 of file constants.inl.
root_five()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_five ()
#include <deps/glm/gtc/constants.hpp>
Return sqrt(5).
See also
GLM_GTC_constants
Definition at line 141 of file constants.inl.
root_half_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_half_pi ()
#include <deps/glm/gtc/constants.hpp>
Return sqrt(pi / 2).
See also
GLM_GTC_constants
Definition at line 99 of file constants.inl.
root_ln_four()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_ln_four ()
#include <deps/glm/gtc/constants.hpp>
Return sqrt(ln(4)).
See also
GLM_GTC_constants
Definition at line 111 of file constants.inl.
root_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_pi ()
#include <deps/glm/gtc/constants.hpp>
Return square root of pi.
See also
GLM_GTC_constants
Definition at line 39 of file constants.inl.
root_three()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_three ()
#include <deps/glm/gtc/constants.hpp>
Return sqrt(3).
See also
GLM_GTC_constants
Definition at line 135 of file constants.inl.
root_two()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_two ()
#include <deps/glm/gtc/constants.hpp>
Return sqrt(2).
See also
GLM_GTC_constants
Definition at line 129 of file constants.inl.
root_two_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_two_pi ()
#include <deps/glm/gtc/constants.hpp>
Return sqrt(2 * pi).
See also
GLM_GTC_constants
Definition at line 105 of file constants.inl.
third()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::third ()
#include <deps/glm/gtc/constants.hpp>
Return 1 / 3.
See also
GLM_GTC_constants
Definition at line 165 of file constants.inl.
three_over_two_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::three_over_two_pi ()
#include <deps/glm/gtc/constants.hpp>
Return pi / 2 * 3.
See also
GLM_GTC_constants
Definition at line 51 of file constants.inl.
two_over_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_over_pi ()
#include <deps/glm/gtc/constants.hpp>
Return 2 / pi.
See also
GLM_GTC_constants
Definition at line 75 of file constants.inl.
two_over_root_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_over_root_pi ()
#include <deps/glm/gtc/constants.hpp>
Return 2 / sqrt(pi).
See also
GLM_GTC_constants
Definition at line 87 of file constants.inl.
two_pi()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_pi ()
#include <deps/glm/gtc/constants.hpp>
Return pi * 2.
See also
GLM_GTC_constants
Definition at line 33 of file constants.inl.
two_thirds()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_thirds ()
#include <deps/glm/gtc/constants.hpp>
Return 2 / 3.
See also
GLM_GTC_constants
Definition at line 171 of file constants.inl.
zero()
template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::zero ()
#include <deps/glm/gtc/constants.hpp>
Return 0.
See also
GLM_GTC_constants
Definition at line 15 of file constants.inl.