jubilant-funicular: nta::utils::Semaphore Class Reference
nta::utils::Semaphore Class Reference
#include <ThreadPool.h>
Public Member Functions
Semaphore (int value=0)
Constructs Semaphore with given value.
void wait ()
Halts until value of Semaphore is > 0.
void signal ()
Increments value of Semaphore.
Semaphore (const Semaphore &)=delete
const Semaphore & operator= (const Semaphore &)=delete
Private Attributes
std::mutex m_mutex
Thread safety stuff.
std::condition_variable_any m_cv
int m_value
The number of resources available.
Detailed Description
Definition at line 17 of file ThreadPool.h.
Constructor & Destructor Documentation
Semaphore() [1/2]
nta::utils::Semaphore::Semaphore (int value = 0)
Constructs Semaphore with given value.
Definition at line 5 of file Semaphore.cpp.
Semaphore() [2/2]
nta::utils::Semaphore::Semaphore (const Semaphore &) delete
Member Function Documentation
operator=()
const Semaphore& nta::utils::Semaphore::operator= (const Semaphore &) delete
signal()
void nta::utils::Semaphore::signal ()
Increments value of Semaphore.
Definition at line 12 of file Semaphore.cpp.
Referenced by nta::utils::ThreadPool::schedule(), nta::utils::ThreadPool::worker_func(), and nta::utils::ThreadPool::~ThreadPool().
wait()
void nta::utils::Semaphore::wait ()
Halts until value of Semaphore is > 0.
Definition at line 7 of file Semaphore.cpp.
Referenced by nta::utils::ThreadPool::dispatcher(), and nta::utils::ThreadPool::getAvailableWorker().
Member Data Documentation
m_cv
std::condition_variable_any nta::utils::Semaphore::m_cv private
Definition at line 21 of file ThreadPool.h.
Referenced by signal(), and wait().
m_mutex
std::mutex nta::utils::Semaphore::m_mutex private
Thread safety stuff.
Definition at line 20 of file ThreadPool.h.
Referenced by signal(), and wait().
m_value
int nta::utils::Semaphore::m_value private
The number of resources available.
Definition at line 23 of file ThreadPool.h.
Referenced by signal(), and wait().
The documentation for this class was generated from the following files:
include/nta/ThreadPool.h
src/Semaphore.cpp