jubilant-funicular: Angle and Trigonometry Functions
Angle and Trigonometry Functions
Core features
Functions
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL GLM_CONSTEXPR vec< L, T, Q > glm::radians (vec< L, T, Q > const &degrees)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL GLM_CONSTEXPR vec< L, T, Q > glm::degrees (vec< L, T, Q > const &radians)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::sin (vec< L, T, Q > const &angle)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::cos (vec< L, T, Q > const &angle)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::tan (vec< L, T, Q > const &angle)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::asin (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::acos (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::atan (vec< L, T, Q > const &y, vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::atan (vec< L, T, Q > const &y_over_x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::sinh (vec< L, T, Q > const &angle)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::cosh (vec< L, T, Q > const &angle)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::tanh (vec< L, T, Q > const &angle)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::asinh (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::acosh (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::atanh (vec< L, T, Q > const &x)
Detailed Description
Include <glm/trigonometric.hpp> to use these core features.
Function parameters specified as angle are assumed to be in units of radians. In no case will any of these functions result in a divide by zero error. If the divisor of a ratio is 0, then results will be undefined.
These all operate component-wise. The description is per component.
Function Documentation
acos()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::acos (vec< L, T, Q > const & x)
#include <deps/glm/trigonometric.hpp>
Arc cosine. Returns an angle whose sine is x. The range of values returned by this function is [0, PI]. Results are undefined if |x| > 1.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL acos man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 80 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::acos(), glm::orientation(), and cimg_library_suffixed::CImg< charT >::RGBtoHSI().
acosh()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::acosh (vec< L, T, Q > const & x)
#include <deps/glm/trigonometric.hpp>
Arc hyperbolic cosine; returns the non-negative inverse of cosh. Results are undefined if x < 1.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL acosh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 170 of file func_trigonometric.inl.
asin()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::asin (vec< L, T, Q > const & x)
#include <deps/glm/trigonometric.hpp>
Arc sine. Returns an angle whose sine is x. The range of values returned by this function is [-PI/2, PI/2]. Results are undefined if |x| > 1.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL asin man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 71 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::asin(), cimg_library_suffixed::CImg< charT >::display_object3d(), and cimg_library_suffixed::CImg< charT >::get_select().
asinh()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::asinh (vec< L, T, Q > const & x)
#include <deps/glm/trigonometric.hpp>
Arc hyperbolic sine; returns the inverse of sinh.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL asinh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 149 of file func_trigonometric.inl.
atan() [1/2]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::atan (vec< L, T, Q > const & y, vec< L, T, Q > const & x)
#include <deps/glm/trigonometric.hpp>
Arc tangent. Returns an angle whose tangent is y/x. The signs of x and y are used to determine what quadrant the angle is in. The range of values returned by this function is [-PI, PI]. Results are undefined if x and y are both 0.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL atan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 95 of file func_trigonometric.inl.
atan() [2/2]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::atan (vec< L, T, Q > const & y_over_x)
#include <deps/glm/trigonometric.hpp>
Arc tangent. Returns an angle whose tangent is y_over_x. The range of values returned by this function is [-PI/2, PI/2].
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL atan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 103 of file func_trigonometric.inl.
atanh()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::atanh (vec< L, T, Q > const & x)
#include <deps/glm/trigonometric.hpp>
Arc hyperbolic tangent; returns the inverse of tanh. Results are undefined if abs(x) >= 1.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL atanh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 191 of file func_trigonometric.inl.
cos()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::cos (vec< L, T, Q > const & angle)
#include <deps/glm/trigonometric.hpp>
The standard trigonometric cosine function. The values returned by this function will range from [-1, 1].
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL cos man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 53 of file func_trigonometric.inl.
Referenced by nta::DebugBatch::addLine(), cimg_library_suffixed::CImg< charT >::blur_anisotropic(), cimg_library_suffixed::CImg< charT >::cone3d(), cimg_library_suffixed::CImg< charT >::cos(), cimg_library_suffixed::CImg< charT >::cylinder3d(), cimg_library_suffixed::CImg< charT >::draw_ellipse(), glm::euclidean(), glm::eulerAngleX(), glm::eulerAngleXY(), glm::eulerAngleXYZ(), glm::eulerAngleY(), glm::eulerAngleYX(), glm::eulerAngleYXZ(), glm::eulerAngleZ(), cimg_library_suffixed::CImg< charT >::FFT(), cimg_library_suffixed::CImg< charT >::get_rotate(), nta::Camera2D::getTranslationMatrix(), cimg_library_suffixed::CImg< charT >::HSItoRGB(), glm::orientate2(), glm::orientate3(), nta::Primitive::Primitive(), glm::rotate(), glm::rotateNormalizedAxis(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), cimg_library_suffixed::CImg< charT >::rotation_matrix(), cimg_library_suffixed::CImg< charT >::torus3d(), and glm::yawPitchRoll().
cosh()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::cosh (vec< L, T, Q > const & angle)
#include <deps/glm/trigonometric.hpp>
Returns the hyperbolic cosine function, (exp(x) + exp(-x)) / 2
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL cosh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 121 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::cosh().
degrees()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL GLM_CONSTEXPR vec<L, T, Q> glm::degrees (vec< L, T, Q > const & radians)
#include <deps/glm/trigonometric.hpp>
Converts radians to degrees and returns the result.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL degrees man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 35 of file func_trigonometric.inl.
radians()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL GLM_CONSTEXPR vec<L, T, Q> glm::radians (vec< L, T, Q > const & degrees)
#include <deps/glm/trigonometric.hpp>
Converts degrees to radians and returns the result.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL radians man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 20 of file func_trigonometric.inl.
sin()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::sin (vec< L, T, Q > const & angle)
#include <deps/glm/trigonometric.hpp>
The standard trigonometric sine function. The values returned by this function will range from [-1, 1].
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL sin man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 44 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::blur_anisotropic(), cimg_library_suffixed::CImg< charT >::cone3d(), cimg_library_suffixed::CImg< charT >::cylinder3d(), cimg_library_suffixed::CImg< charT >::draw_ellipse(), glm::euclidean(), glm::eulerAngleX(), glm::eulerAngleXY(), glm::eulerAngleXYZ(), glm::eulerAngleY(), glm::eulerAngleYX(), glm::eulerAngleYXZ(), glm::eulerAngleZ(), cimg_library_suffixed::CImg< charT >::FFT(), cimg_library_suffixed::CImg< charT >::get_CMYKtoRGB(), cimg_library_suffixed::CImg< charT >::get_rotate(), nta::Camera2D::getTranslationMatrix(), glm::orientate2(), glm::orientate3(), nta::Primitive::Primitive(), glm::rotate(), glm::rotateNormalizedAxis(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), cimg_library_suffixed::CImg< charT >::rotation_matrix(), cimg_library_suffixed::CImg< charT >::sin(), cimg_library_suffixed::cimg::sinc(), cimg_library_suffixed::CImg< charT >::torus3d(), and glm::yawPitchRoll().
sinh()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::sinh (vec< L, T, Q > const & angle)
#include <deps/glm/trigonometric.hpp>
Returns the hyperbolic sine function, (exp(x) - exp(-x)) / 2
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL sinh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 112 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::sinh().
tan()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::tan (vec< L, T, Q > const & angle)
#include <deps/glm/trigonometric.hpp>
The standard trigonometric tangent function.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL tan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 62 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::tan().
tanh()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::tanh (vec< L, T, Q > const & angle)
#include <deps/glm/trigonometric.hpp>
Returns the hyperbolic tangent function, sinh(angle) / cosh(angle)
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL tanh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 130 of file func_trigonometric.inl.
Referenced by cimg_library_suffixed::CImg< charT >::tanh().