jubilant-funicular: nta::FontMap Class Reference
nta::FontMap Class Reference
represents the organization of a texture containing the characters
#include <SpriteFont.h>
Classes
struct CharRect
a rectangle representing the location of a char in the FontMap
Public Member Functions
FontMap ()
constructor and destructor
~FontMap ()
glm::vec2 getBoundingDimensions () const
returns the dimensions of the rectangle that contains the FontMap
void addRect (char c, crvec2 dimensions)
adds a rectangle and associates it with c (replacing any preexisting rectangle)
void position ()
positions map so that the topleft is at (0,0)
Public Attributes
friend SpriteFont
Private Member Functions
bool isOverlapping (const CharRect &rect) const
returns whether or not rect is overlapping with any existing CharRect
Private Attributes
CharRect * m_rects = nullptr
the rectangles making up the FontMap
Detailed Description
represents the organization of a texture containing the characters
Definition at line 23 of file SpriteFont.h.
Constructor & Destructor Documentation
FontMap()
nta::FontMap::FontMap ()
constructor and destructor
Definition at line 7 of file FontMap.cpp.
~FontMap()
nta::FontMap::~FontMap ()
Definition at line 13 of file FontMap.cpp.
Member Function Documentation
addRect()
void nta::FontMap::addRect (char c, crvec2 dimensions)
adds a rectangle and associates it with c (replacing any preexisting rectangle)
Definition at line 39 of file FontMap.cpp.
Referenced by nta::SpriteFont::SpriteFont().
getBoundingDimensions()
glm::vec2 nta::FontMap::getBoundingDimensions () const
returns the dimensions of the rectangle that contains the FontMap
Definition at line 16 of file FontMap.cpp.
Referenced by nta::SpriteFont::SpriteFont().
isOverlapping()
bool nta::FontMap::isOverlapping (const CharRect & rect) const private
returns whether or not rect is overlapping with any existing CharRect
Definition at line 26 of file FontMap.cpp.
Referenced by addRect().
position()
void nta::FontMap::position ()
positions map so that the topleft is at (0,0)
Definition at line 64 of file FontMap.cpp.
Referenced by nta::SpriteFont::SpriteFont().
Member Data Documentation
m_rects
CharRect* nta::FontMap::m_rects = nullptr private
the rectangles making up the FontMap
Definition at line 37 of file SpriteFont.h.
Referenced by addRect(), FontMap(), getBoundingDimensions(), isOverlapping(), position(), nta::SpriteFont::SpriteFont(), and ~FontMap().
SpriteFont
friend nta::FontMap::SpriteFont
Definition at line 49 of file SpriteFont.h.
The documentation for this class was generated from the following files:
include/nta/SpriteFont.h
src/FontMap.cpp