jubilant-funicular: Common functions
Common functions
Core features
Functions
template<typename genType >
GLM_FUNC_DECL genType glm::abs (genType x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::abs (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::sign (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::floor (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::trunc (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::round (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::roundEven (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::ceil (vec< L, T, Q > const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::fract (genType x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::fract (vec< L, T, Q > const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::mod (genType x, genType y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::mod (vec< L, T, Q > const &x, T y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::mod (vec< L, T, Q > const &x, vec< L, T, Q > const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::modf (genType x, genType &i)
template<typename genType >
GLM_FUNC_DECL genType glm::min (genType x, genType y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::min (vec< L, T, Q > const &x, T y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::min (vec< L, T, Q > const &x, vec< L, T, Q > const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::max (genType x, genType y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::max (vec< L, T, Q > const &x, T y)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::max (vec< L, T, Q > const &x, vec< L, T, Q > const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::clamp (genType x, genType minVal, genType maxVal)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::clamp (vec< L, T, Q > const &x, T minVal, T maxVal)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::clamp (vec< L, T, Q > const &x, vec< L, T, Q > const &minVal, vec< L, T, Q > const &maxVal)
template<typename genTypeT , typename genTypeU >
GLM_FUNC_DECL genTypeT glm::mix (genTypeT x, genTypeT y, genTypeU a)
template<length_t L, typename T , typename U , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::mix (vec< L, T, Q > const &x, vec< L, T, Q > const &y, vec< L, U, Q > const &a)
template<length_t L, typename T , typename U , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::mix (vec< L, T, Q > const &x, vec< L, T, Q > const &y, U a)
template<typename genType >
GLM_FUNC_DECL genType glm::step (genType edge, genType x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::step (T edge, vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::step (vec< L, T, Q > const &edge, vec< L, T, Q > const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::smoothstep (genType edge0, genType edge1, genType x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::smoothstep (T edge0, T edge1, vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::smoothstep (vec< L, T, Q > const &edge0, vec< L, T, Q > const &edge1, vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, bool, Q > glm::isnan (vec< L, T, Q > const &x)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, bool, Q > glm::isinf (vec< L, T, Q > const &x)
GLM_FUNC_DECL int glm::floatBitsToInt (float const &v)
template<length_t L, qualifier Q>
GLM_FUNC_DECL vec< L, int, Q > glm::floatBitsToInt (vec< L, float, Q > const &v)
GLM_FUNC_DECL uint glm::floatBitsToUint (float const &v)
template<length_t L, qualifier Q>
GLM_FUNC_DECL vec< L, uint, Q > glm::floatBitsToUint (vec< L, float, Q > const &v)
GLM_FUNC_DECL float glm::intBitsToFloat (int const &v)
template<length_t L, qualifier Q>
GLM_FUNC_DECL vec< L, float, Q > glm::intBitsToFloat (vec< L, int, Q > const &v)
GLM_FUNC_DECL float glm::uintBitsToFloat (uint const &v)
template<length_t L, qualifier Q>
GLM_FUNC_DECL vec< L, float, Q > glm::uintBitsToFloat (vec< L, uint, Q > const &v)
template<typename genType >
GLM_FUNC_DECL genType glm::fma (genType const &a, genType const &b, genType const &c)
template<typename genType , typename genIType >
GLM_FUNC_DECL genType glm::frexp (genType const &x, genIType &exp)
template<typename genType , typename genIType >
GLM_FUNC_DECL genType glm::ldexp (genType const &x, genIType const &exp)
Detailed Description
Include <glm/common.hpp> to use these core features.
These all operate component-wise. The description is per component.
Function Documentation
abs() [1/2]
template<typename genType > GLM_FUNC_DECL genType glm::abs (genType x)
#include <deps/glm/common.hpp>
Returns x if x >= 0; otherwise, it returns -x.
Template Parameters
genType floating-point or signed integer; scalar or vector types.
See also
GLSL abs man page
GLSL 4.20.8 specification, section 8.3 Common Functions
qualifier
Referenced by cimg_library_suffixed::cimg::abs(), nta::SpriteBatch::addGlyph(), and nta::SpriteFont::drawText().
abs() [2/2]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::abs (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns x if x >= 0; otherwise, it returns -x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or signed integer scalar types
Q Value from qualifier enum
See also
GLSL abs man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 315 of file func_common.inl.
ceil()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::ceil (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns a value equal to the nearest integer that is greater than or equal to x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL ceil man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 418 of file func_common.inl.
Referenced by cimg_library_suffixed::cimg::round().
clamp() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::clamp (genType x, genType minVal, genType maxVal)
#include <deps/glm/common.hpp>
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
GLSL clamp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 543 of file func_common.inl.
clamp() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::clamp (vec< L, T, Q > const & x, T minVal, T maxVal)
#include <deps/glm/common.hpp>
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or integer scalar types
Q Value from qualifier enum
See also
GLSL clamp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 550 of file func_common.inl.
clamp() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::clamp (vec< L, T, Q > const & x, vec< L, T, Q > const & minVal, vec< L, T, Q > const & maxVal)
#include <deps/glm/common.hpp>
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or integer scalar types
Q Value from qualifier enum
See also
GLSL clamp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 557 of file func_common.inl.
floatBitsToInt() [1/2]
GLM_FUNC_QUALIFIER int glm::floatBitsToInt (float const & v)
#include <deps/glm/common.hpp>
Returns a signed integer value representing the encoding of a floating-point value. The floating-point value's bit-level representation is preserved.
See also
GLSL floatBitsToInt man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 703 of file func_common.inl.
floatBitsToInt() [2/2]
template<length_t L, qualifier Q> GLM_FUNC_DECL vec<L, int, Q> glm::floatBitsToInt (vec< L, float, Q > const & v)
#include <deps/glm/common.hpp>
Returns a signed integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
Q Value from qualifier enum
See also
GLSL floatBitsToInt man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 717 of file func_common.inl.
floatBitsToUint() [1/2]
GLM_FUNC_QUALIFIER uint glm::floatBitsToUint (float const & v)
#include <deps/glm/common.hpp>
Returns a unsigned integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
See also
GLSL floatBitsToUint man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 722 of file func_common.inl.
floatBitsToUint() [2/2]
template<length_t L, qualifier Q> GLM_FUNC_DECL vec<L, uint, Q> glm::floatBitsToUint (vec< L, float, Q > const & v)
#include <deps/glm/common.hpp>
Returns a unsigned integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
Q Value from qualifier enum
See also
GLSL floatBitsToUint man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 736 of file func_common.inl.
floor()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::floor (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns a value equal to the nearest integer that is less then or equal to x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL floor man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 345 of file func_common.inl.
Referenced by cimg_library_suffixed::CImg< charT >::HSVtoRGB(), cimg_library_suffixed::cimg::log2(), cimg_library_suffixed::cimg::mod(), and cimg_library_suffixed::cimg::round().
fma()
template<typename genType > GLM_FUNC_DECL genType glm::fma (genType const & a, genType const & b, genType const & c)
#include <deps/glm/common.hpp>
Computes and returns a * b + c.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL fma man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 780 of file func_common.inl.
fract() [1/2]
template<typename genType > GLM_FUNC_DECL genType glm::fract (genType x)
#include <deps/glm/common.hpp>
Return x - floor(x).
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL fract man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 426 of file func_common.inl.
fract() [2/2]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::fract (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Return x - floor(x).
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL fract man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 432 of file func_common.inl.
frexp()
template<typename genType , typename genIType > GLM_FUNC_DECL genType glm::frexp (genType const & x, genIType & exp)
#include <deps/glm/common.hpp>
Splits x into a floating-point significand in the range [0.5, 1.0) and an integral exponent of two, such that: x = significand * exp(2, exponent)
The significand is returned by the function and the exponent is returned in the parameter exp. For a floating-point value of zero, the significant and exponent are both zero. For a floating-point value that is an infinity or is not a number, the results are undefined.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL frexp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
intBitsToFloat() [1/2]
GLM_FUNC_QUALIFIER float glm::intBitsToFloat (int const & v)
#include <deps/glm/common.hpp>
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
See also
GLSL intBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 741 of file func_common.inl.
intBitsToFloat() [2/2]
template<length_t L, qualifier Q> GLM_FUNC_DECL vec<L, float, Q> glm::intBitsToFloat (vec< L, int, Q > const & v)
#include <deps/glm/common.hpp>
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
Q Value from qualifier enum
See also
GLSL intBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 755 of file func_common.inl.
isinf()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, bool, Q> glm::isinf (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns true if x holds a positive infinity or negative infinity representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no infinity representations.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL isinf man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 693 of file func_common.inl.
isnan()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, bool, Q> glm::isnan (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns true if x holds a NaN (not a number) representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no NaN representations.
/!\ When using compiler fast math, this function may fail.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL isnan man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 651 of file func_common.inl.
ldexp()
template<typename genType , typename genIType > GLM_FUNC_DECL genType glm::ldexp (genType const & x, genIType const & exp)
#include <deps/glm/common.hpp>
Builds a floating-point number from x and the corresponding integral exponent of two in exp, returning: significand * exp(2, exponent)
If this product is too large to be represented in the floating-point type, the result is undefined.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL ldexp man page;
GLSL 4.20.8 specification, section 8.3 Common Functions
max() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::max (genType x, genType y)
#include <deps/glm/common.hpp>
Returns y if x < y; otherwise, it returns x.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
GLSL max man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 23 of file func_common.inl.
Referenced by cimg_library_suffixed::CImg< charT >::_correlate(), nta::SpriteBatch::addGlyph(), cimg_library_suffixed::CImgList< charT >::assign(), glm::associatedMax(), cimg_library_suffixed::CImg< charT >::autocrop(), cimg_library_suffixed::CImg< charT >::blur_bilateral(), cimg_library_suffixed::cimg::cbrt(), cimg_library_suffixed::CImgList< charT >::CImgList(), cimg_library_suffixed::cimg::dialog(), cimg_library_suffixed::CImg< charT >::diffusion_tensors(), cimg_library_suffixed::CImg< charT >::dilate(), cimg_library_suffixed::CImgDisplay::display(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_graph(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::distance_eikonal(), cimg_library_suffixed::CImg< charT >::draw_ellipse(), cimg_library_suffixed::CImg< charT >::draw_fill(), cimg_library_suffixed::CImg< charT >::draw_gaussian(), cimg_library_suffixed::CImg< charT >::draw_image(), cimg_library_suffixed::CImg< charT >::draw_line(), cimg_library_suffixed::CImg< charT >::draw_mandelbrot(), cimg_library_suffixed::CImg< charT >::draw_object3d(), cimg_library_suffixed::CImg< charT >::draw_point(), cimg_library_suffixed::CImg< charT >::draw_polygon(), cimg_library_suffixed::CImg< charT >::draw_quiver(), cimg_library_suffixed::CImg< charT >::draw_rectangle(), cimg_library_suffixed::CImg< charT >::draw_triangle(), nta::SpriteFont::drawText(), cimg_library_suffixed::CImg< charT >::eval(), cimg_library_suffixed::CImgList< charT >::font(), cimg_library_suffixed::CImgList< charT >::get_append(), cimg_library_suffixed::CImg< charT >::get_blur_guided(), cimg_library_suffixed::CImg< charT >::get_blur_median(), cimg_library_suffixed::CImg< charT >::get_dilate(), cimg_library_suffixed::CImg< charT >::get_distance_eikonal(), cimg_library_suffixed::CImg< charT >::get_erode(), cimg_library_suffixed::CImg< charT >::get_identity_matrix(), cimg_library_suffixed::CImgList< charT >::get_load_cimg(), cimg_library_suffixed::CImg< charT >::get_load_dlm(), cimg_library_suffixed::CImg< charT >::get_patchmatch(), cimg_library_suffixed::CImg< charT >::get_pseudoinvert(), cimg_library_suffixed::CImg< charT >::get_resize(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), cimg_library_suffixed::CImg< charT >::get_select_graph(), nta::FontMap::getBoundingDimensions(), cimg_library_suffixed::CImg< charT >::identity_matrix(), cimg_library_suffixed::CImg< charT >::load_tiff(), cimg_library_suffixed::CImgList< charT >::load_video(), cimg_library_suffixed::cimg::max(), cimg_library_suffixed::CImg< charT >::max(), nta::Random::randBool(), cimg_library_suffixed::CImgList< charT >::save_gif_external(), and cimg_library_suffixed::CImg< charT >::SVD().
max() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::max (vec< L, T, Q > const & x, T y)
#include <deps/glm/common.hpp>
Returns y if x < y; otherwise, it returns x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or integer scalar types
Q Value from qualifier enum
See also
GLSL max man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 529 of file func_common.inl.
max() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::max (vec< L, T, Q > const & x, vec< L, T, Q > const & y)
#include <deps/glm/common.hpp>
Returns y if x < y; otherwise, it returns x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or integer scalar types
Q Value from qualifier enum
See also
GLSL max man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 536 of file func_common.inl.
min() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::min (genType x, genType y)
#include <deps/glm/common.hpp>
Returns y if y < x; otherwise, it returns x.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
GLSL min man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 15 of file func_common.inl.
Referenced by nta::SpriteBatch::addGlyph(), glm::associatedMin(), cimg_library_suffixed::CImg< charT >::autocrop(), cimg_library_suffixed::cimg::cbrt(), cimg_library_suffixed::CImg< charT >::display(), cimg_library_suffixed::CImgList< charT >::display(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::dot(), cimg_library_suffixed::CImg< charT >::draw_graph(), cimg_library_suffixed::CImg< charT >::draw_object3d(), cimg_library_suffixed::CImg< charT >::draw_plasma(), cimg_library_suffixed::CImg< charT >::draw_polygon(), cimg_library_suffixed::CImg< charT >::draw_text(), cimg_library_suffixed::CImg< charT >::draw_triangle(), nta::SpriteFont::drawText(), cimg_library_suffixed::CImg< charT >::erode(), cimg_library_suffixed::CImg< charT >::fill(), cimg_library_suffixed::CImg< charT >::get_blur_median(), cimg_library_suffixed::CImg< charT >::get_CImg3dtoobject3d(), cimg_library_suffixed::CImg< charT >::get_displacement(), cimg_library_suffixed::CImg< charT >::get_distance_eikonal(), cimg_library_suffixed::CImg< charT >::get_load_bmp(), cimg_library_suffixed::CImgList< charT >::get_load_cimg(), cimg_library_suffixed::CImg< charT >::get_load_pnm(), cimg_library_suffixed::CImg< charT >::get_load_rgb(), cimg_library_suffixed::CImg< charT >::get_load_rgba(), cimg_library_suffixed::CImg< charT >::get_object3dtoCImg3d(), cimg_library_suffixed::CImg< charT >::get_patchmatch(), cimg_library_suffixed::CImg< charT >::get_resize(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), nta::FontMap::getBoundingDimensions(), cimg_library_suffixed::CImgList< charT >::load_video(), cimg_library_suffixed::cimg::min(), cimg_library_suffixed::CImg< charT >::min(), cimg_library_suffixed::CImg< charT >::quantize(), cimg_library_suffixed::CImg< charT >::rand(), nta::Random::randBool(), nta::Random::randFloat(), nta::Random::randInt(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_pnk(), cimg_library_suffixed::CImg< charT >::save_pnm(), cimg_library_suffixed::CImgList< charT >::save_video(), cimg_library_suffixed::CImg< charT >::set_vector_at(), cimg_library_suffixed::CImgDisplay::snapshot(), and cimg_library_suffixed::CImg< charT >::SVD().
min() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::min (vec< L, T, Q > const & x, T y)
#include <deps/glm/common.hpp>
Returns y if y < x; otherwise, it returns x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or integer scalar types
Q Value from qualifier enum
See also
GLSL min man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 515 of file func_common.inl.
min() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::min (vec< L, T, Q > const & x, vec< L, T, Q > const & y)
#include <deps/glm/common.hpp>
Returns y if y < x; otherwise, it returns x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point or integer scalar types
Q Value from qualifier enum
See also
GLSL min man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 522 of file func_common.inl.
mix()
template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT glm::mix (genTypeT x, genTypeT y, genTypeU a)
#include <deps/glm/common.hpp>
If genTypeU is a floating scalar or vector: Returns x * (1.0 - a) + y * a, i.e., the linear blend of x and y using the floating-point value a. The value for a is not restricted to the range [0, 1].
If genTypeU is a boolean scalar or vector: Selects which vector each returned component comes from. For a component of 'a' that is false, the corresponding component of 'x' is returned. For a component of 'a' that is true, the corresponding component of 'y' is returned. Components of 'x' and 'y' that are not selected are allowed to be invalid floating point values and will have no effect on the results. Thus, this provides different functionality than genType mix(genType x, genType y, genType(a)) where a is a Boolean vector.
See also
GLSL mix man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Parameters
[in] x Value to interpolate.
[in] y Value to interpolate.
[in] a Interpolant.
Template Parameters
genTypeT Floating point scalar or vector.
genTypeU Floating point or boolean scalar or vector. It can't be a vector if it is the length of genTypeT.
#include <glm/glm.hpp>
...
float a;
bool b;
glm::dvec3 e;
glm::dvec3 f;
glm::vec4 g;
glm::vec4 h;
...
glm::vec4 r = glm::mix(g, h, a); // Interpolate with a floating-point scalar two vectors.
glm::vec4 s = glm::mix(g, h, b); // Returns g or h;
glm::dvec3 t = glm::mix(e, f, a); // Types of the third parameter is not required to match with the first and the second.
glm::vec4 u = glm::mix(g, h, r); // Interpolations can be perform per component with a vector for the last parameter.
Definition at line 564 of file func_common.inl.
mod()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::mod (vec< L, T, Q > const & x, vec< L, T, Q > const & y)
#include <deps/glm/common.hpp>
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types, include glm/gtc/integer for integer scalar types support
Q Value from qualifier enum
See also
GLSL mod man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 458 of file func_common.inl.
modf()
template<typename genType > GLM_FUNC_DECL genType glm::modf (genType x, genType & i)
#include <deps/glm/common.hpp>
Returns the fractional part of x and sets i to the integer part (as a whole number floating point value). Both the return value and the output parameter will have the same sign as x.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL modf man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 465 of file func_common.inl.
round()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::round (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns a value equal to the nearest integer to x. The fraction 0.5 will round in a direction chosen by the implementation, presumably the direction that is fastest. This includes the possibility that round(x) returns the same value as roundEven(x) for all values of x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL round man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 359 of file func_common.inl.
Referenced by cimg_library_suffixed::cimg::log2(), and cimg_library_suffixed::cimg::round().
roundEven()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::roundEven (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns a value equal to the nearest integer to x. A fractional part of 0.5 will round toward the nearest even integer. (Both 3.5 and 4.5 for x will return 4.0.)
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL roundEven man page
GLSL 4.20.8 specification, section 8.3 Common Functions
New round to even technique
Definition at line 409 of file func_common.inl.
sign()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::sign (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns 1.0 if x > 0, 0.0 if x == 0, or -1.0 if x < 0.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL sign man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 333 of file func_common.inl.
Referenced by nta::InputManager::update().
smoothstep()
template<typename genType > GLM_FUNC_DECL genType glm::smoothstep (genType edge0, genType edge1, genType x)
#include <deps/glm/common.hpp>
Returns 0.0 if x <= edge0 and 1.0 if x >= edge1 and performs smooth Hermite interpolation between 0 and 1 when edge0 < x < edge1. This is useful in cases where you would want a threshold function with a smooth transition. This is equivalent to: genType t; t = clamp ((x - edge0) / (edge1 - edge0), 0, 1); return t * t * (3 - 2 * t); Results are undefined if edge0 >= edge1.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL smoothstep man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 602 of file func_common.inl.
step() [1/3]
template<typename genType > GLM_FUNC_DECL genType glm::step (genType edge, genType x)
#include <deps/glm/common.hpp>
Returns 0.0 if x < edge, otherwise it returns 1.0 for each component of a genType.
See also
GLSL step man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 583 of file func_common.inl.
Referenced by cimg_library_suffixed::CImg< charT >::draw_fill(), cimg_library_suffixed::CImg< charT >::load_camera(), and cimg_library_suffixed::CImgList< charT >::load_video().
step() [2/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::step (T edge, vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns 0.0 if x < edge, otherwise it returns 1.0.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL step man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 589 of file func_common.inl.
step() [3/3]
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::step (vec< L, T, Q > const & edge, vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns 0.0 if x < edge, otherwise it returns 1.0.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL step man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 595 of file func_common.inl.
trunc()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::trunc (vec< L, T, Q > const & x)
#include <deps/glm/common.hpp>
Returns a value equal to the nearest integer to x whose absolute value is not larger than the absolute value of x.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
T Floating-point scalar types
Q Value from qualifier enum
See also
GLSL trunc man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 352 of file func_common.inl.
uintBitsToFloat() [1/2]
GLM_FUNC_QUALIFIER float glm::uintBitsToFloat (uint const & v)
#include <deps/glm/common.hpp>
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
See also
GLSL uintBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 760 of file func_common.inl.
uintBitsToFloat() [2/2]
template<length_t L, qualifier Q> GLM_FUNC_DECL vec<L, float, Q> glm::uintBitsToFloat (vec< L, uint, Q > const & v)
#include <deps/glm/common.hpp>
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
Template Parameters
L Integer between 1 and 4 included that qualify the dimension of the vector
Q Value from qualifier enum
See also
GLSL uintBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 774 of file func_common.inl.