jubilant-funicular: nta::SystemManager Class Reference
nta::SystemManager Class Reference
Manages "System" stuff, whatever that means.
#include <SystemManager.h>
Static Public Member Functions
static GLSLProgram * getGLSLProgram (crstring progPath)
static GLSLProgram * getGLSLProgram (crstring name, crstring vert, crstring frag)
static Window * getWindow (crstring windowTitle, int width=640, int height=480, int flags=0)
Gets a Window with specified title, width, height, and flags.
static Window * getWindow (crstring windowTitle, int flags)
static void destroy ()
Destorys the manager, freeing all necessary data.
Static Private Attributes
static std::map< std::string, GLSLProgram * > m_glslMap
Collection of GLSLProgram.
static std::map< std::string, Window * > m_windowMap
Collection of Window.
Detailed Description
Manages "System" stuff, whatever that means.
Definition at line 11 of file SystemManager.h.
Member Function Documentation
destroy()
void nta::SystemManager::destroy () static
Destorys the manager, freeing all necessary data.
Definition at line 29 of file SystemManager.cpp.
Referenced by nta::cleanup(), and getWindow().
getGLSLProgram() [1/2]
GLSLProgram * nta::SystemManager::getGLSLProgram (crstring progPath) static
Gets GLSLProgram at specified path Assumes vertex shader is (progPath + ".vert") and fragment shader is (progPath + ".frag")
Definition at line 7 of file SystemManager.cpp.
getGLSLProgram() [2/2]
GLSLProgram * nta::SystemManager::getGLSLProgram (crstring name, crstring vert, crstring frag) static
Gets GLSLProgram, specifying explicitly where the vertex and fragment shaders are. Uses name as the key in the map
Definition at line 14 of file SystemManager.cpp.
getWindow() [1/2]
Window * nta::SystemManager::getWindow (crstring windowTitle, int width = 640, int height = 480, int flags = 0) static
Gets a Window with specified title, width, height, and flags.
Definition at line 21 of file SystemManager.cpp.
Referenced by getWindow(), nta::ScreenManager::ScreenManager(), and nta::Screen::setWindow().
getWindow() [2/2]
static Window* nta::SystemManager::getWindow (crstring windowTitle, int flags) inline static
Definition at line 28 of file SystemManager.h.
Member Data Documentation
m_glslMap
std::map< std::string, GLSLProgram * > nta::SystemManager::m_glslMap static private
Collection of GLSLProgram.
Definition at line 14 of file SystemManager.h.
Referenced by destroy(), and getGLSLProgram().
m_windowMap
std::map< std::string, Window * > nta::SystemManager::m_windowMap static private
Collection of Window.
Definition at line 16 of file SystemManager.h.
Referenced by destroy(), and getWindow().
The documentation for this class was generated from the following files:
include/nta/SystemManager.h
src/SystemManager.cpp