jubilant-funicular: nta::FPSLimiter Class Reference
nta::FPSLimiter Class Reference
used to cap the fps of the program at a specific value
#include <FPSLimiter.h>
Public Member Functions
FPSLimiter ()
constructor and destructor
~FPSLimiter ()
void setMaxFPS (float maxFPS)
sets maximum allowed fps
float getFPS () const
gets most recently calculated fps
long double end ()
ends fps calculations, delaying if necessary to cap fps
Public Member Functions inherited from nta::Timer
Timer ()
constructor and destructor
virtual ~Timer ()
virtual void begin ()
begins timer
virtual long double end () const
return time since beginning of timer in nanoseconds
Private Attributes
float m_fps
most recently calculated fps
float m_maxFPS
maximum allowed fps
Additional Inherited Members
Protected Attributes inherited from nta::Timer
std::chrono::time_point< std::chrono::high_resolution_clock, std::chrono::nanoseconds > m_startPoint
Detailed Description
used to cap the fps of the program at a specific value
Definition at line 8 of file FPSLimiter.h.
Constructor & Destructor Documentation
FPSLimiter()
nta::FPSLimiter::FPSLimiter ()
constructor and destructor
Definition at line 7 of file FPSLimiter.cpp.
~FPSLimiter()
nta::FPSLimiter::~FPSLimiter ()
Definition at line 9 of file FPSLimiter.cpp.
Member Function Documentation
end()
long double nta::FPSLimiter::end ()
ends fps calculations, delaying if necessary to cap fps
Definition at line 18 of file FPSLimiter.cpp.
Referenced by nta::ScreenManager::run().
getFPS()
float nta::FPSLimiter::getFPS () const
gets most recently calculated fps
Definition at line 15 of file FPSLimiter.cpp.
Referenced by nta::ScreenManager::getFPS().
setMaxFPS()
void nta::FPSLimiter::setMaxFPS (float maxFPS)
sets maximum allowed fps
Definition at line 12 of file FPSLimiter.cpp.
Referenced by nta::ScreenManager::ScreenManager().
Member Data Documentation
m_fps
float nta::FPSLimiter::m_fps private
most recently calculated fps
Definition at line 11 of file FPSLimiter.h.
Referenced by end(), getFPS(), and ~FPSLimiter().
m_maxFPS
float nta::FPSLimiter::m_maxFPS private
maximum allowed fps
Definition at line 13 of file FPSLimiter.h.
Referenced by end(), setMaxFPS(), and ~FPSLimiter().
The documentation for this class was generated from the following files:
include/nta/FPSLimiter.h
src/FPSLimiter.cpp