jubilant-funicular: cimg_library_suffixed::cimg Namespace Reference
cimg_library_suffixed::cimg Namespace Reference
Contains low-level functions and variables of the Library.
Classes
struct last
struct Mutex_info
struct superset
struct superset2
struct superset3
struct superset< bool, char >
struct superset< bool, cimg_int64 >
struct superset< bool, cimg_uint64 >
struct superset< bool, double >
struct superset< bool, float >
struct superset< bool, int >
struct superset< bool, short >
struct superset< bool, signed char >
struct superset< bool, unsigned char >
struct superset< bool, unsigned int >
struct superset< bool, unsigned short >
struct superset< char, cimg_int64 >
struct superset< char, cimg_uint64 >
struct superset< char, double >
struct superset< char, float >
struct superset< char, int >
struct superset< char, short >
struct superset< char, signed char >
struct superset< char, unsigned char >
struct superset< char, unsigned int >
struct superset< char, unsigned short >
struct superset< cimg_int64, double >
struct superset< cimg_int64, float >
struct superset< cimg_uint64, char >
struct superset< cimg_uint64, cimg_int64 >
struct superset< cimg_uint64, double >
struct superset< cimg_uint64, float >
struct superset< cimg_uint64, int >
struct superset< cimg_uint64, short >
struct superset< cimg_uint64, signed char >
struct superset< float, double >
struct superset< int, cimg_int64 >
struct superset< int, cimg_uint64 >
struct superset< int, double >
struct superset< int, float >
struct superset< int, unsigned int >
struct superset< short, cimg_int64 >
struct superset< short, cimg_uint64 >
struct superset< short, double >
struct superset< short, float >
struct superset< short, int >
struct superset< short, unsigned int >
struct superset< short, unsigned short >
struct superset< signed char, char >
struct superset< signed char, cimg_int64 >
struct superset< signed char, cimg_uint64 >
struct superset< signed char, double >
struct superset< signed char, float >
struct superset< signed char, int >
struct superset< signed char, short >
struct superset< signed char, unsigned char >
struct superset< signed char, unsigned int >
struct superset< signed char, unsigned short >
struct superset< unsigned char, char >
struct superset< unsigned char, cimg_int64 >
struct superset< unsigned char, cimg_uint64 >
struct superset< unsigned char, double >
struct superset< unsigned char, float >
struct superset< unsigned char, int >
struct superset< unsigned char, short >
struct superset< unsigned char, signed char >
struct superset< unsigned char, unsigned int >
struct superset< unsigned char, unsigned short >
struct superset< unsigned int, char >
struct superset< unsigned int, cimg_int64 >
struct superset< unsigned int, cimg_uint64 >
struct superset< unsigned int, double >
struct superset< unsigned int, float >
struct superset< unsigned int, int >
struct superset< unsigned int, short >
struct superset< unsigned int, signed char >
struct superset< unsigned short, char >
struct superset< unsigned short, cimg_int64 >
struct superset< unsigned short, cimg_uint64 >
struct superset< unsigned short, double >
struct superset< unsigned short, float >
struct superset< unsigned short, int >
struct superset< unsigned short, short >
struct superset< unsigned short, signed char >
struct superset< unsigned short, unsigned int >
struct type
struct type< bool >
struct type< char >
struct type< cimg_int64 >
struct type< cimg_uint64 >
struct type< double >
struct type< float >
struct type< int >
struct type< long double >
struct type< short >
struct type< signed char >
struct type< unsigned char >
struct type< unsigned int >
struct type< unsigned short >
Functions
std::FILE * output (std::FILE *file)
Get/set default output stream for the library messages.
void info ()
Print information about environement variables.
template<typename T >
void unused (const T &,...)
Avoid warning messages due to unused parameters. Do nothing actually.
int mutex (const unsigned int n, const int lock_mode=1)
unsigned int & _exception_mode (const unsigned int value, const bool is_set)
FILE * _stdin (const bool throw_exception=true)
FILE * _stdout (const bool throw_exception=true)
FILE * _stderr (const bool throw_exception=true)
unsigned int & exception_mode (const unsigned int mode)
Set current exception mode.
unsigned int & exception_mode ()
Return current exception mode.
unsigned int & _openmp_mode (const unsigned int value, const bool is_set)
Set current openmp mode.
unsigned int & openmp_mode (const unsigned int mode)
unsigned int & openmp_mode ()
Return current openmp mode.
int dialog (const char *const title, const char *const msg, const char *const button1_label, const char *const button2_label, const char *const button3_label, const char *const button4_label, const char *const button5_label, const char *const button6_label, const bool is_centered)
Display a simple dialog box, and wait for the user's response .
double eval (const char *const expression, const double x, const double y, const double z, const double c)
Evaluate math expression.
Mutex_info & Mutex_attr ()
unsigned int nb_cpus ()
void warn (const char *const format,...)
Display a warning message on the default output stream.
int system (const char *const command, const char *const module_name=0, const bool is_verbose=false)
template<typename T >
T & temporary (const T &)
Return a reference to a temporary variable of type T.
template<typename T >
void swap (T &a, T &b)
Exchange values of variables a and b.
template<typename T1 , typename T2 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2)
Exchange values of variables (a1,a2) and (b1,b2).
template<typename T1 , typename T2 , typename T3 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3)
Exchange values of variables (a1,a2,a3) and (b1,b2,b3).
template<typename T1 , typename T2 , typename T3 , typename T4 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4)
Exchange values of variables (a1,a2,...,a4) and (b1,b2,...,b4).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5)
Exchange values of variables (a1,a2,...,a5) and (b1,b2,...,b5).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5, T6 &a6, T6 &b6)
Exchange values of variables (a1,a2,...,a6) and (b1,b2,...,b6).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5, T6 &a6, T6 &b6, T7 &a7, T7 &b7)
Exchange values of variables (a1,a2,...,a7) and (b1,b2,...,b7).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5, T6 &a6, T6 &b6, T7 &a7, T7 &b7, T8 &a8, T8 &b8)
Exchange values of variables (a1,a2,...,a8) and (b1,b2,...,b8).
bool endianness ()
Return the endianness of the current architecture.
template<typename T >
void invert_endianness (T *const buffer, const cimg_ulong size)
Reverse endianness of all elements in a memory buffer.
template<typename T >
T & invert_endianness (T &a)
Reverse endianness of a single variable.
unsigned int float2uint (const float f)
float uint2float (const unsigned int u)
cimg_ulong time ()
Return the value of a system timer, with a millisecond precision.
cimg_ulong tictoc (const bool is_tic)
cimg_ulong tic ()
Start tic/toc timer for time measurement between code instructions.
cimg_ulong toc ()
End tic/toc timer and displays elapsed time from last call to tic().
void sleep (const unsigned int milliseconds)
Sleep for a given numbers of milliseconds.
unsigned int _wait (const unsigned int milliseconds, cimg_ulong &timer)
cimg_long wait (const unsigned int milliseconds)
Wait for a given number of milliseconds since the last call to wait().
unsigned int srand ()
unsigned int srand (const unsigned int seed)
double rand (const double val_min, const double val_max)
Return a random variable uniformely distributed between [val_min,val_max].
double rand (const double val_max=1)
Return a random variable uniformely distributed between [0,val_max].
double grand ()
Return a random variable following a gaussian distribution and a standard deviation of 1.
unsigned int prand (const double z)
Return a random variable following a Poisson distribution of parameter z.
template<typename T , typename t >
T cut (const T &val, const t &val_min, const t &val_max)
Cut (i.e. clamp) value in specified interval.
template<typename T >
T rol (const T &a, const unsigned int n=1)
Bitwise-rotate value on the left.
float rol (const float a, const unsigned int n=1)
double rol (const double a, const unsigned int n=1)
double rol (const long double a, const unsigned int n=1)
template<typename T >
T ror (const T &a, const unsigned int n=1)
Bitwise-rotate value on the right.
float ror (const float a, const unsigned int n=1)
double ror (const double a, const unsigned int n=1)
double ror (const long double a, const unsigned int n=1)
template<typename T >
T abs (const T &a)
Return absolute value of a value.
bool abs (const bool a)
int abs (const unsigned char a)
int abs (const unsigned short a)
int abs (const unsigned int a)
int abs (const int a)
cimg_int64 abs (const cimg_uint64 a)
double abs (const double a)
float abs (const float a)
template<typename T >
T sqr (const T &val)
Return square of a value.
int xln (const int x)
Return 1 + log_10(x) of a value x.
template<typename t >
t min (const t &a, const t &b, const t &c)
Return the minimum between three values.
template<typename t >
t min (const t &a, const t &b, const t &c, const t &d)
Return the minimum between four values.
template<typename t >
t max (const t &a, const t &b, const t &c)
Return the maximum between three values.
template<typename t >
t max (const t &a, const t &b, const t &c, const t &d)
Return the maximum between four values.
template<typename T >
T sign (const T &x)
Return the sign of a value.
template<typename T >
cimg_ulong nearest_pow2 (const T &x)
Return the nearest power of 2 higher than given value.
double sinc (const double x)
Return the sinc of a given value.
template<typename T >
T mod (const T &x, const T &m)
Return the modulo of a value.
int mod (const bool x, const bool m)
int mod (const unsigned char x, const unsigned char m)
int mod (const char x, const char m)
int mod (const unsigned short x, const unsigned short m)
int mod (const short x, const short m)
int mod (const unsigned int x, const unsigned int m)
int mod (const int x, const int m)
cimg_int64 mod (const cimg_uint64 x, const cimg_uint64 m)
cimg_int64 mod (const cimg_int64 x, const cimg_int64 m)
template<typename T >
T minmod (const T &a, const T &b)
Return the min-mod of two values.
double log2 (const double x)
Return base-2 logarithm of a value.
template<typename T >
T round (const T &x)
template<typename T >
T round (const T &x, const double y, const int rounding_type=0)
Return rounded value.
template<typename T >
double cbrt (const T &x)
Return x^(1/3).
template<typename T >
T median (T val0, T val1)
template<typename T >
T median (T val0, T val1, T val2)
template<typename T >
T median (T val0, T val1, T val2, T val3, T val4)
template<typename T >
T median (T val0, T val1, T val2, T val3, T val4, T val5, T val6)
template<typename T >
T median (T val0, T val1, T val2, T val3, T val4, T val5, T val6, T val7, T val8)
template<typename T >
T median (T val0, T val1, T val2, T val3, T val4, T val5, T val6, T val7, T val8, T val9, T val10, T val11, T val12)
template<typename T >
T median (T val0, T val1, T val2, T val3, T val4, T val5, T val6, T val7, T val8, T val9, T val10, T val11, T val12, T val13, T val14, T val15, T val16, T val17, T val18, T val19, T val20, T val21, T val22, T val23, T val24)
template<typename T >
T median (T val0, T val1, T val2, T val3, T val4, T val5, T val6, T val7, T val8, T val9, T val10, T val11, T val12, T val13, T val14, T val15, T val16, T val17, T val18, T val19, T val20, T val21, T val22, T val23, T val24, T val25, T val26, T val27, T val28, T val29, T val30, T val31, T val32, T val33, T val34, T val35, T val36, T val37, T val38, T val39, T val40, T val41, T val42, T val43, T val44, T val45, T val46, T val47, T val48)
template<typename T >
T hypot (const T x, const T y)
Return sqrt(x^2 + y^2).
template<typename T >
T hypot (const T x, const T y, const T z)
template<typename T >
T _hypot (const T x, const T y)
double factorial (const int n)
Return the factorial of n.
double permutations (const int k, const int n, const bool with_order)
Return the number of permutations of k objects in a set of n objects.
double _fibonacci (int exp)
double fibonacci (const int n)
Calculate fibonacci number.
long gcd (long a, long b)
Calculate greatest common divisor.
char lowercase (const char x)
Convert ascii character to lower case.
double lowercase (const double x)
void lowercase (char *const str)
Convert C-string to lower case.
char uppercase (const char x)
Convert ascii character to upper case.
double uppercase (const double x)
void uppercase (char *const str)
Convert C-string to upper case.
double atof (const char *const str)
Read value in a C-string.
int strncasecmp (const char *const str1, const char *const str2, const int l)
Compare the first l characters of two C-strings, ignoring the case.
int strcasecmp (const char *const str1, const char *const str2)
Compare two C-strings, ignoring the case.
char * strellipsize (char *const str, const unsigned int l=64, const bool is_ending=true)
Ellipsize a string.
char * strellipsize (const char *const str, char *const res, const unsigned int l=64, const bool is_ending=true)
Ellipsize a string.
bool strpare (char *const str, const char delimiter, const bool is_symmetric, const bool is_iterative)
Remove delimiters on the start and/or end of a C-string.
bool strpare (char *const str, const bool is_symmetric, const bool is_iterative)
Remove white spaces on the start and/or end of a C-string.
void strwindows_reserved (char *const str, const char c='_')
Replace reserved characters (for Windows filename) by another character.
void strunescape (char *const str)
Replace escape sequences in C-strings by their binary ascii values.
const char * strbuffersize (const cimg_ulong size)
const char * stros ()
const char * basename (const char *const s, const char separator=cimg_file_separator)
Return the basename of a filename.
const char * filenamerand ()
void winformat_string (char *const str)
std::FILE * win_fopen (const char *const path, const char *const mode)
std::FILE * fopen (const char *const path, const char *const mode)
Open a file.
int fclose (std::FILE *file)
Close a file.
int fseek (FILE *stream, cimg_long offset, int origin)
Version of 'fseek()' that supports >=64bits offsets everywhere (for Windows).
cimg_long ftell (FILE *stream)
Version of 'ftell()' that supports >=64bits offsets everywhere (for Windows).
bool is_directory (const char *const path)
Check if a path is a directory.
bool is_file (const char *const path)
Check if a path is a file.
cimg_int64 fsize (const char *const filename)
Get file size.
template<typename T >
int fdate (const char *const path, T *attr, const unsigned int nb_attr)
Get last write time of a given file or directory (multiple-attributes version).
int fdate (const char *const path, unsigned int attr)
Get last write time of a given file or directory (single-attribute version).
template<typename T >
int date (T *attr, const unsigned int nb_attr)
Get current local time (multiple-attributes version).
int date (unsigned int attr)
Get current local time (single-attribute version).
const char * temporary_path (const char *const user_path, const bool reinit_path)
Get/set path to store temporary files.
const char * imagemagick_path (const char *const user_path, const bool reinit_path)
Get/set path to the Program Files/ directory (Windows only).
const char * graphicsmagick_path (const char *const user_path, const bool reinit_path)
Get/set path to the GraphicsMagick's gm binary.
const char * medcon_path (const char *const user_path, const bool reinit_path)
Get/set path to the XMedcon's medcon binary.
const char * ffmpeg_path (const char *const user_path, const bool reinit_path)
Get/set path to the FFMPEG's ffmpeg binary.
const char * gzip_path (const char *const user_path, const bool reinit_path)
Get/set path to the gzip binary.
const char * gunzip_path (const char *const user_path, const bool reinit_path)
Get/set path to the gunzip binary.
const char * dcraw_path (const char *const user_path, const bool reinit_path)
Get/set path to the dcraw binary.
const char * wget_path (const char *const user_path, const bool reinit_path)
Get/set path to the wget binary.
const char * curl_path (const char *const user_path, const bool reinit_path)
Get/set path to the curl binary.
const char * split_filename (const char *const filename, char *const body=0)
Split filename into two C-strings body and extension.
char * number_filename (const char *const filename, const int number, const unsigned int digits, char *const str)
Generate a numbered version of a filename.
template<typename T >
size_t fread (T *const ptr, const size_t nmemb, std::FILE *stream)
Read data from file.
template<typename T >
size_t fwrite (const T *ptr, const size_t nmemb, std::FILE *stream)
Write data to file.
void fempty (std::FILE *const file, const char *const filename)
Create an empty file.
const char * ftype (std::FILE *const file, const char *const filename)
Try to guess format from an image file.
char * load_network (const char *const url, char *const filename_local, const unsigned int timeout, const bool try_fallback, const char *const referer)
Load file from network as a local temporary file.
const char * option (const char *const name, const int argc, const char *const *const argv, const char *const defaut, const char *const usage, const bool reset_static)
Return options specified on the command line.
const char * option (const char *const name, const int argc, const char *const *const argv, const char *const defaut, const char *const usage=0)
bool option (const char *const name, const int argc, const char *const *const argv, const bool defaut, const char *const usage=0)
int option (const char *const name, const int argc, const char *const *const argv, const int defaut, const char *const usage=0)
char option (const char *const name, const int argc, const char *const *const argv, const char defaut, const char *const usage=0)
float option (const char *const name, const int argc, const char *const *const argv, const float defaut, const char *const usage=0)
double option (const char *const name, const int argc, const char *const *const argv, const double defaut, const char *const usage=0)
int _sort_files (const void *a, const void *b)
CImgList< char > files (const char *const path, const bool is_pattern=false, const unsigned int mode=2, const bool include_path=false)
Return list of files/directories in specified directory.
template<typename t >
int dialog (const char *const title, const char *const msg, const char *const button1_label, const char *const button2_label, const char *const button3_label, const char *const button4_label, const char *const button5_label, const char *const button6_label, const CImg< t > &logo, const bool is_centered=false)
Display a simple dialog box, and wait for the user's response.
template<typename t >
CImg< typename cimg::superset< double, t >::type > eval (const char *const expression, const CImg< t > &xyzc)
Variables
static const char t_normal [] = { 0 }
static const char *const t_black = cimg::t_normal
static const char *const *const t_red = cimg::t_normal
static const char *const *const *const t_green = cimg::t_normal
static const char *const *const *const *const t_yellow = cimg::t_normal
static const char *const *const *const *const *const t_blue = cimg::t_normal
static const char *const *const *const *const *const *const t_magenta = cimg::t_normal
static const char *const *const *const *const *const *const *const t_cyan = cimg::t_normal
static const char *const *const *const *const *const *const *const *const t_white = cimg::t_normal
static const char *const *const *const *const *const *const *const *const *const t_bold = cimg::t_normal
static const char *const *const *const *const *const *const *const *const *const *const t_underscore = cimg::t_normal
const unsigned int keyESC = 1U
Keycode for the ESC key (architecture-dependent).
const unsigned int keyF1 = 2U
Keycode for the F1 key (architecture-dependent).
const unsigned int keyF2 = 3U
Keycode for the F2 key (architecture-dependent).
const unsigned int keyF3 = 4U
Keycode for the F3 key (architecture-dependent).
const unsigned int keyF4 = 5U
Keycode for the F4 key (architecture-dependent).
const unsigned int keyF5 = 6U
Keycode for the F5 key (architecture-dependent).
const unsigned int keyF6 = 7U
Keycode for the F6 key (architecture-dependent).
const unsigned int keyF7 = 8U
Keycode for the F7 key (architecture-dependent).
const unsigned int keyF8 = 9U
Keycode for the F8 key (architecture-dependent).
const unsigned int keyF9 = 10U
Keycode for the F9 key (architecture-dependent).
const unsigned int keyF10 = 11U
Keycode for the F10 key (architecture-dependent).
const unsigned int keyF11 = 12U
Keycode for the F11 key (architecture-dependent).
const unsigned int keyF12 = 13U
Keycode for the F12 key (architecture-dependent).
const unsigned int keyPAUSE = 14U
Keycode for the PAUSE key (architecture-dependent).
const unsigned int key1 = 15U
Keycode for the 1 key (architecture-dependent).
const unsigned int key2 = 16U
Keycode for the 2 key (architecture-dependent).
const unsigned int key3 = 17U
Keycode for the 3 key (architecture-dependent).
const unsigned int key4 = 18U
Keycode for the 4 key (architecture-dependent).
const unsigned int key5 = 19U
Keycode for the 5 key (architecture-dependent).
const unsigned int key6 = 20U
Keycode for the 6 key (architecture-dependent).
const unsigned int key7 = 21U
Keycode for the 7 key (architecture-dependent).
const unsigned int key8 = 22U
Keycode for the 8 key (architecture-dependent).
const unsigned int key9 = 23U
Keycode for the 9 key (architecture-dependent).
const unsigned int key0 = 24U
Keycode for the 0 key (architecture-dependent).
const unsigned int keyBACKSPACE = 25U
Keycode for the BACKSPACE key (architecture-dependent).
const unsigned int keyINSERT = 26U
Keycode for the INSERT key (architecture-dependent).
const unsigned int keyHOME = 27U
Keycode for the HOME key (architecture-dependent).
const unsigned int keyPAGEUP = 28U
Keycode for the PAGEUP key (architecture-dependent).
const unsigned int keyTAB = 29U
Keycode for the TAB key (architecture-dependent).
const unsigned int keyQ = 30U
Keycode for the Q key (architecture-dependent).
const unsigned int keyW = 31U
Keycode for the W key (architecture-dependent).
const unsigned int keyE = 32U
Keycode for the E key (architecture-dependent).
const unsigned int keyR = 33U
Keycode for the R key (architecture-dependent).
const unsigned int keyT = 34U
Keycode for the T key (architecture-dependent).
const unsigned int keyY = 35U
Keycode for the Y key (architecture-dependent).
const unsigned int keyU = 36U
Keycode for the U key (architecture-dependent).
const unsigned int keyI = 37U
Keycode for the I key (architecture-dependent).
const unsigned int keyO = 38U
Keycode for the O key (architecture-dependent).
const unsigned int keyP = 39U
Keycode for the P key (architecture-dependent).
const unsigned int keyDELETE = 40U
Keycode for the DELETE key (architecture-dependent).
const unsigned int keyEND = 41U
Keycode for the END key (architecture-dependent).
const unsigned int keyPAGEDOWN = 42U
Keycode for the PAGEDOWN key (architecture-dependent).
const unsigned int keyCAPSLOCK = 43U
Keycode for the CAPSLOCK key (architecture-dependent).
const unsigned int keyA = 44U
Keycode for the A key (architecture-dependent).
const unsigned int keyS = 45U
Keycode for the S key (architecture-dependent).
const unsigned int keyD = 46U
Keycode for the D key (architecture-dependent).
const unsigned int keyF = 47U
Keycode for the F key (architecture-dependent).
const unsigned int keyG = 48U
Keycode for the G key (architecture-dependent).
const unsigned int keyH = 49U
Keycode for the H key (architecture-dependent).
const unsigned int keyJ = 50U
Keycode for the J key (architecture-dependent).
const unsigned int keyK = 51U
Keycode for the K key (architecture-dependent).
const unsigned int keyL = 52U
Keycode for the L key (architecture-dependent).
const unsigned int keyENTER = 53U
Keycode for the ENTER key (architecture-dependent).
const unsigned int keySHIFTLEFT = 54U
Keycode for the SHIFTLEFT key (architecture-dependent).
const unsigned int keyZ = 55U
Keycode for the Z key (architecture-dependent).
const unsigned int keyX = 56U
Keycode for the X key (architecture-dependent).
const unsigned int keyC = 57U
Keycode for the C key (architecture-dependent).
const unsigned int keyV = 58U
Keycode for the V key (architecture-dependent).
const unsigned int keyB = 59U
Keycode for the B key (architecture-dependent).
const unsigned int keyN = 60U
Keycode for the N key (architecture-dependent).
const unsigned int keyM = 61U
Keycode for the M key (architecture-dependent).
const unsigned int keySHIFTRIGHT = 62U
Keycode for the SHIFTRIGHT key (architecture-dependent).
const unsigned int keyARROWUP = 63U
Keycode for the ARROWUP key (architecture-dependent).
const unsigned int keyCTRLLEFT = 64U
Keycode for the CTRLLEFT key (architecture-dependent).
const unsigned int keyAPPLEFT = 65U
Keycode for the APPLEFT key (architecture-dependent).
const unsigned int keyALT = 66U
Keycode for the ALT key (architecture-dependent).
const unsigned int keySPACE = 67U
Keycode for the SPACE key (architecture-dependent).
const unsigned int keyALTGR = 68U
Keycode for the ALTGR key (architecture-dependent).
const unsigned int keyAPPRIGHT = 69U
Keycode for the APPRIGHT key (architecture-dependent).
const unsigned int keyMENU = 70U
Keycode for the MENU key (architecture-dependent).
const unsigned int keyCTRLRIGHT = 71U
Keycode for the CTRLRIGHT key (architecture-dependent).
const unsigned int keyARROWLEFT = 72U
Keycode for the ARROWLEFT key (architecture-dependent).
const unsigned int keyARROWDOWN = 73U
Keycode for the ARROWDOWN key (architecture-dependent).
const unsigned int keyARROWRIGHT = 74U
Keycode for the ARROWRIGHT key (architecture-dependent).
const unsigned int keyPAD0 = 75U
Keycode for the PAD0 key (architecture-dependent).
const unsigned int keyPAD1 = 76U
Keycode for the PAD1 key (architecture-dependent).
const unsigned int keyPAD2 = 77U
Keycode for the PAD2 key (architecture-dependent).
const unsigned int keyPAD3 = 78U
Keycode for the PAD3 key (architecture-dependent).
const unsigned int keyPAD4 = 79U
Keycode for the PAD4 key (architecture-dependent).
const unsigned int keyPAD5 = 80U
Keycode for the PAD5 key (architecture-dependent).
const unsigned int keyPAD6 = 81U
Keycode for the PAD6 key (architecture-dependent).
const unsigned int keyPAD7 = 82U
Keycode for the PAD7 key (architecture-dependent).
const unsigned int keyPAD8 = 83U
Keycode for the PAD8 key (architecture-dependent).
const unsigned int keyPAD9 = 84U
Keycode for the PAD9 key (architecture-dependent).
const unsigned int keyPADADD = 85U
Keycode for the PADADD key (architecture-dependent).
const unsigned int keyPADSUB = 86U
Keycode for the PADSUB key (architecture-dependent).
const unsigned int keyPADMUL = 87U
Keycode for the PADMUL key (architecture-dependent).
const unsigned int keyPADDIV = 88U
Keycode for the PADDDIV key (architecture-dependent).
const double PI = 3.14159265358979323846
Value of the mathematical constant PI.
static const char *const data_font12x13
static const char *const data_font20x23
static const char *const data_font47x53
static const char *const _data_font90x103 []
static const unsigned char logo40x38 [4576]
Detailed Description
Contains low-level functions and variables of the Library.
Most of the functions and variables within this namespace are used by the library for low-level operations. You may use them to access specific const values or environment variables internally used by .
Warning
Never write using namespace cimg_library::cimg; in your source code. Lot of functions in the cimg:: namespace have the same names as standard C functions that may be defined in the global namespace ::.
Class Documentation
cimg_library_suffixed::cimg::last
struct cimg_library_suffixed::cimg::last
template<typename t1, typename t2>
struct cimg_library_suffixed::cimg::last< t1, t2 >
Definition at line 2979 of file CImg.h.
Class Members
typedef t2 type
cimg_library_suffixed::cimg::superset
struct cimg_library_suffixed::cimg::superset
template<typename T, typename t>
struct cimg_library_suffixed::cimg::superset< T, t >
Definition at line 2879 of file CImg.h.
Class Members
typedef T type
cimg_library_suffixed::cimg::superset2
struct cimg_library_suffixed::cimg::superset2
template<typename t1, typename t2, typename t3>
struct cimg_library_suffixed::cimg::superset2< t1, t2, t3 >
Definition at line 2971 of file CImg.h.
Class Members
typedef superset< t1, typename
superset< t2, t3 >::type >
::type type
cimg_library_suffixed::cimg::superset3
struct cimg_library_suffixed::cimg::superset3
template<typename t1, typename t2, typename t3, typename t4>
struct cimg_library_suffixed::cimg::superset3< t1, t2, t3, t4 >
Definition at line 2975 of file CImg.h.
Class Members
typedef superset< t1, typename
superset2< t2, t3, t4 >::type >
::type type
cimg_library_suffixed::cimg::superset< bool, char >
struct cimg_library_suffixed::cimg::superset< bool, char >
template<>
struct cimg_library_suffixed::cimg::superset< bool, char >
Definition at line 2881 of file CImg.h.
Class Members
typedef char type
cimg_library_suffixed::cimg::superset< bool, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< bool, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< bool, cimg_int64 >
Definition at line 2888 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< bool, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< bool, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< bool, cimg_uint64 >
Definition at line 2887 of file CImg.h.
Class Members
typedef cimg_uint64 type
cimg_library_suffixed::cimg::superset< bool, double >
struct cimg_library_suffixed::cimg::superset< bool, double >
template<>
struct cimg_library_suffixed::cimg::superset< bool, double >
Definition at line 2890 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< bool, float >
struct cimg_library_suffixed::cimg::superset< bool, float >
template<>
struct cimg_library_suffixed::cimg::superset< bool, float >
Definition at line 2889 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< bool, int >
struct cimg_library_suffixed::cimg::superset< bool, int >
template<>
struct cimg_library_suffixed::cimg::superset< bool, int >
Definition at line 2886 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< bool, short >
struct cimg_library_suffixed::cimg::superset< bool, short >
template<>
struct cimg_library_suffixed::cimg::superset< bool, short >
Definition at line 2884 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< bool, signed char >
struct cimg_library_suffixed::cimg::superset< bool, signed char >
template<>
struct cimg_library_suffixed::cimg::superset< bool, signed char >
Definition at line 2882 of file CImg.h.
Class Members
typedef signed char type
cimg_library_suffixed::cimg::superset< bool, unsigned char >
struct cimg_library_suffixed::cimg::superset< bool, unsigned char >
template<>
struct cimg_library_suffixed::cimg::superset< bool, unsigned char >
Definition at line 2880 of file CImg.h.
Class Members
typedef unsigned char type
cimg_library_suffixed::cimg::superset< bool, unsigned int >
struct cimg_library_suffixed::cimg::superset< bool, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< bool, unsigned int >
Definition at line 2885 of file CImg.h.
Class Members
typedef unsigned int type
cimg_library_suffixed::cimg::superset< bool, unsigned short >
struct cimg_library_suffixed::cimg::superset< bool, unsigned short >
template<>
struct cimg_library_suffixed::cimg::superset< bool, unsigned short >
Definition at line 2883 of file CImg.h.
Class Members
typedef unsigned short type
cimg_library_suffixed::cimg::superset< char, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< char, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< char, cimg_int64 >
Definition at line 2918 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< char, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< char, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< char, cimg_uint64 >
Definition at line 2917 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< char, double >
struct cimg_library_suffixed::cimg::superset< char, double >
template<>
struct cimg_library_suffixed::cimg::superset< char, double >
Definition at line 2920 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< char, float >
struct cimg_library_suffixed::cimg::superset< char, float >
template<>
struct cimg_library_suffixed::cimg::superset< char, float >
Definition at line 2919 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< char, int >
struct cimg_library_suffixed::cimg::superset< char, int >
template<>
struct cimg_library_suffixed::cimg::superset< char, int >
Definition at line 2916 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< char, short >
struct cimg_library_suffixed::cimg::superset< char, short >
template<>
struct cimg_library_suffixed::cimg::superset< char, short >
Definition at line 2914 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< char, signed char >
struct cimg_library_suffixed::cimg::superset< char, signed char >
template<>
struct cimg_library_suffixed::cimg::superset< char, signed char >
Definition at line 2912 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< char, unsigned char >
struct cimg_library_suffixed::cimg::superset< char, unsigned char >
template<>
struct cimg_library_suffixed::cimg::superset< char, unsigned char >
Definition at line 2911 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< char, unsigned int >
struct cimg_library_suffixed::cimg::superset< char, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< char, unsigned int >
Definition at line 2915 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< char, unsigned short >
struct cimg_library_suffixed::cimg::superset< char, unsigned short >
template<>
struct cimg_library_suffixed::cimg::superset< char, unsigned short >
Definition at line 2913 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< cimg_int64, double >
struct cimg_library_suffixed::cimg::superset< cimg_int64, double >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_int64, double >
Definition at line 2958 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< cimg_int64, float >
struct cimg_library_suffixed::cimg::superset< cimg_int64, float >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_int64, float >
Definition at line 2957 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< cimg_uint64, char >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, char >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, char >
Definition at line 2950 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< cimg_uint64, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, cimg_int64 >
Definition at line 2954 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< cimg_uint64, double >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, double >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, double >
Definition at line 2956 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< cimg_uint64, float >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, float >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, float >
Definition at line 2955 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< cimg_uint64, int >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, int >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, int >
Definition at line 2953 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< cimg_uint64, short >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, short >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, short >
Definition at line 2952 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< cimg_uint64, signed char >
struct cimg_library_suffixed::cimg::superset< cimg_uint64, signed char >
template<>
struct cimg_library_suffixed::cimg::superset< cimg_uint64, signed char >
Definition at line 2951 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< float, double >
struct cimg_library_suffixed::cimg::superset< float, double >
template<>
struct cimg_library_suffixed::cimg::superset< float, double >
Definition at line 2959 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< int, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< int, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< int, cimg_int64 >
Definition at line 2947 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< int, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< int, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< int, cimg_uint64 >
Definition at line 2946 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< int, double >
struct cimg_library_suffixed::cimg::superset< int, double >
template<>
struct cimg_library_suffixed::cimg::superset< int, double >
Definition at line 2949 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< int, float >
struct cimg_library_suffixed::cimg::superset< int, float >
template<>
struct cimg_library_suffixed::cimg::superset< int, float >
Definition at line 2948 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< int, unsigned int >
struct cimg_library_suffixed::cimg::superset< int, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< int, unsigned int >
Definition at line 2945 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< short, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< short, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< short, cimg_int64 >
Definition at line 2934 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< short, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< short, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< short, cimg_uint64 >
Definition at line 2933 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< short, double >
struct cimg_library_suffixed::cimg::superset< short, double >
template<>
struct cimg_library_suffixed::cimg::superset< short, double >
Definition at line 2936 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< short, float >
struct cimg_library_suffixed::cimg::superset< short, float >
template<>
struct cimg_library_suffixed::cimg::superset< short, float >
Definition at line 2935 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< short, int >
struct cimg_library_suffixed::cimg::superset< short, int >
template<>
struct cimg_library_suffixed::cimg::superset< short, int >
Definition at line 2932 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< short, unsigned int >
struct cimg_library_suffixed::cimg::superset< short, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< short, unsigned int >
Definition at line 2931 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< short, unsigned short >
struct cimg_library_suffixed::cimg::superset< short, unsigned short >
template<>
struct cimg_library_suffixed::cimg::superset< short, unsigned short >
Definition at line 2930 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< signed char, char >
struct cimg_library_suffixed::cimg::superset< signed char, char >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, char >
Definition at line 2902 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< signed char, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< signed char, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, cimg_int64 >
Definition at line 2908 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< signed char, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< signed char, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, cimg_uint64 >
Definition at line 2907 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< signed char, double >
struct cimg_library_suffixed::cimg::superset< signed char, double >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, double >
Definition at line 2910 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< signed char, float >
struct cimg_library_suffixed::cimg::superset< signed char, float >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, float >
Definition at line 2909 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< signed char, int >
struct cimg_library_suffixed::cimg::superset< signed char, int >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, int >
Definition at line 2906 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< signed char, short >
struct cimg_library_suffixed::cimg::superset< signed char, short >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, short >
Definition at line 2904 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< signed char, unsigned char >
struct cimg_library_suffixed::cimg::superset< signed char, unsigned char >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, unsigned char >
Definition at line 2901 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< signed char, unsigned int >
struct cimg_library_suffixed::cimg::superset< signed char, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, unsigned int >
Definition at line 2905 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< signed char, unsigned short >
struct cimg_library_suffixed::cimg::superset< signed char, unsigned short >
template<>
struct cimg_library_suffixed::cimg::superset< signed char, unsigned short >
Definition at line 2903 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< unsigned char, char >
struct cimg_library_suffixed::cimg::superset< unsigned char, char >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, char >
Definition at line 2891 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< unsigned char, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< unsigned char, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, cimg_int64 >
Definition at line 2898 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned char, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< unsigned char, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, cimg_uint64 >
Definition at line 2897 of file CImg.h.
Class Members
typedef cimg_uint64 type
cimg_library_suffixed::cimg::superset< unsigned char, double >
struct cimg_library_suffixed::cimg::superset< unsigned char, double >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, double >
Definition at line 2900 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< unsigned char, float >
struct cimg_library_suffixed::cimg::superset< unsigned char, float >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, float >
Definition at line 2899 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< unsigned char, int >
struct cimg_library_suffixed::cimg::superset< unsigned char, int >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, int >
Definition at line 2896 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< unsigned char, short >
struct cimg_library_suffixed::cimg::superset< unsigned char, short >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, short >
Definition at line 2894 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< unsigned char, signed char >
struct cimg_library_suffixed::cimg::superset< unsigned char, signed char >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, signed char >
Definition at line 2892 of file CImg.h.
Class Members
typedef short type
cimg_library_suffixed::cimg::superset< unsigned char, unsigned int >
struct cimg_library_suffixed::cimg::superset< unsigned char, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, unsigned int >
Definition at line 2895 of file CImg.h.
Class Members
typedef unsigned int type
cimg_library_suffixed::cimg::superset< unsigned char, unsigned short >
struct cimg_library_suffixed::cimg::superset< unsigned char, unsigned short >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned char, unsigned short >
Definition at line 2893 of file CImg.h.
Class Members
typedef unsigned short type
cimg_library_suffixed::cimg::superset< unsigned int, char >
struct cimg_library_suffixed::cimg::superset< unsigned int, char >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, char >
Definition at line 2937 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned int, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< unsigned int, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, cimg_int64 >
Definition at line 2942 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned int, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< unsigned int, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, cimg_uint64 >
Definition at line 2941 of file CImg.h.
Class Members
typedef cimg_uint64 type
cimg_library_suffixed::cimg::superset< unsigned int, double >
struct cimg_library_suffixed::cimg::superset< unsigned int, double >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, double >
Definition at line 2944 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< unsigned int, float >
struct cimg_library_suffixed::cimg::superset< unsigned int, float >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, float >
Definition at line 2943 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< unsigned int, int >
struct cimg_library_suffixed::cimg::superset< unsigned int, int >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, int >
Definition at line 2940 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned int, short >
struct cimg_library_suffixed::cimg::superset< unsigned int, short >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, short >
Definition at line 2939 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned int, signed char >
struct cimg_library_suffixed::cimg::superset< unsigned int, signed char >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned int, signed char >
Definition at line 2938 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned short, char >
struct cimg_library_suffixed::cimg::superset< unsigned short, char >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, char >
Definition at line 2921 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< unsigned short, cimg_int64 >
struct cimg_library_suffixed::cimg::superset< unsigned short, cimg_int64 >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, cimg_int64 >
Definition at line 2927 of file CImg.h.
Class Members
typedef cimg_int64 type
cimg_library_suffixed::cimg::superset< unsigned short, cimg_uint64 >
struct cimg_library_suffixed::cimg::superset< unsigned short, cimg_uint64 >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, cimg_uint64 >
Definition at line 2926 of file CImg.h.
Class Members
typedef cimg_uint64 type
cimg_library_suffixed::cimg::superset< unsigned short, double >
struct cimg_library_suffixed::cimg::superset< unsigned short, double >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, double >
Definition at line 2929 of file CImg.h.
Class Members
typedef double type
cimg_library_suffixed::cimg::superset< unsigned short, float >
struct cimg_library_suffixed::cimg::superset< unsigned short, float >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, float >
Definition at line 2928 of file CImg.h.
Class Members
typedef float type
cimg_library_suffixed::cimg::superset< unsigned short, int >
struct cimg_library_suffixed::cimg::superset< unsigned short, int >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, int >
Definition at line 2925 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< unsigned short, short >
struct cimg_library_suffixed::cimg::superset< unsigned short, short >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, short >
Definition at line 2923 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< unsigned short, signed char >
struct cimg_library_suffixed::cimg::superset< unsigned short, signed char >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, signed char >
Definition at line 2922 of file CImg.h.
Class Members
typedef int type
cimg_library_suffixed::cimg::superset< unsigned short, unsigned int >
struct cimg_library_suffixed::cimg::superset< unsigned short, unsigned int >
template<>
struct cimg_library_suffixed::cimg::superset< unsigned short, unsigned int >
Definition at line 2924 of file CImg.h.
Class Members
typedef unsigned int type
Function Documentation
_openmp_mode()
unsigned int& cimg_library_suffixed::cimg::_openmp_mode (const unsigned int value, const bool is_set) inline
Set current openmp mode.
The way openmp-based methods are handled by can be changed dynamically, using this function.
Parameters
mode Desired openmp mode. Possible values are:
0: Never parallelize.
1: Always parallelize.
2: Adaptive parallelization mode (default behavior).
Definition at line 2361 of file CImg.h.
Referenced by openmp_mode().
atof()
double cimg_library_suffixed::cimg::atof (const char *const str) inline
Read value in a C-string.
Parameters
str C-string containing the float value to read.
Returns
Read value.
Note
Same as std::atof() extended to manage the retrieval of fractions from C-strings, as in "1/2".
Definition at line 5915 of file CImg.h.
Referenced by option().
curl_path()
const char * cimg_library_suffixed::cimg::curl_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the curl binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the curl binary.
Definition at line 60212 of file CImg.h.
Referenced by date(), and load_network().
date() [1/2]
template<typename T > int cimg_library_suffixed::cimg::date (T * attr, const unsigned int nb_attr) inline
Get current local time (multiple-attributes version).
Parameters
[in,out] attr Type of requested time attributes. Can be { 0=year | 1=month | 2=day | 3=day of week | 4=hour | 5=minute | 6=second } Replaced by read attributes after return (or -1 if an error occured).
nb_attr Number of attributes to read/write.
Returns
Latest read attribute.
Definition at line 6323 of file CImg.h.
Referenced by date().
date() [2/2]
int cimg_library_suffixed::cimg::date (unsigned int attr) inline
Get current local time (single-attribute version).
Parameters
attr Type of requested time attribute. Can be { 0=year | 1=month | 2=day | 3=day of week | 4=hour | 5=minute | 6=second }
Returns
Specified attribute or -1 if an error occured.
Definition at line 6356 of file CImg.h.
dcraw_path()
const char * cimg_library_suffixed::cimg::dcraw_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the dcraw binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the dcraw binary.
Definition at line 60140 of file CImg.h.
Referenced by date(), and cimg_library_suffixed::CImg< charT >::load_dcraw_external().
dialog()
template<typename t > int cimg_library_suffixed::cimg::dialog (const char *const title, const char *const msg, const char *const button1_label, const char *const button2_label, const char *const button3_label, const char *const button4_label, const char *const button5_label, const char *const button6_label, const CImg< t > & logo, const bool is_centered = false) inline
Display a simple dialog box, and wait for the user's response.
Parameters
title Title of the dialog window.
msg Main message displayed inside the dialog window.
button1_label Label of the 1st button.
button2_label Label of the 2nd button (0 to hide button).
button3_label Label of the 3rd button (0 to hide button).
button4_label Label of the 4th button (0 to hide button).
button5_label Label of the 5th button (0 to hide button).
button6_label Label of the 6th button (0 to hide button).
logo Image logo displayed at the left of the main message.
is_centered Tells if the dialog window must be centered on the screen.
Returns
Indice of clicked button (from 0 to 5), or -1 if the dialog window has been closed by the user.
Note
Up to 6 buttons can be defined in the dialog window.
The function returns when a user clicked one of the button or closed the dialog window.
If a button text is set to 0, the corresponding button (and the followings) will not appear in the dialog box. At least one button must be specified.
Definition at line 60637 of file CImg.h.
endianness()
bool cimg_library_suffixed::cimg::endianness () inline
Return the endianness of the current architecture.
Returns
false for Little Endian or true for Big Endian.
Definition at line 4948 of file CImg.h.
Referenced by cimg_library_suffixed::CImgList< charT >::get_load_cimg(), cimg_library_suffixed::CImg< charT >::get_load_inr(), cimg_library_suffixed::CImg< charT >::get_load_pfm(), cimg_library_suffixed::CImg< charT >::get_load_png(), cimg_library_suffixed::CImgList< charT >::get_serialize(), cimg_library_suffixed::CImgList< charT >::get_unserialize(), info(), cimg_library_suffixed::CImgList< charT >::load_parrec(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_inr(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_png(), and cimg_library_suffixed::CImg< charT >::save_pnm().
eval()
double cimg_library_suffixed::cimg::eval (const char *const expression, const double x, const double y, const double z, const double c) inline
Evaluate math expression.
Parameters
expression C-string describing the formula to evaluate.
x Value of the pre-defined variable x.
y Value of the pre-defined variable y.
z Value of the pre-defined variable z.
c Value of the pre-defined variable c.
Returns
Result of the formula evaluation.
Note
Set expression to 0 to keep evaluating the last specified expression.
Example
const double
res1 = cimg::eval("cos(x)^2 + sin(y)^2",2,2),  // will return '1'.
res2 = cimg::eval(0,1,1);                    // will return '1' too.
Definition at line 60811 of file CImg.h.
Referenced by openmp_mode().
exception_mode() [1/2]
unsigned int& cimg_library_suffixed::cimg::exception_mode (const unsigned int mode) inline
Set current exception mode.
The way error messages are handled by can be changed dynamically, using this function.
Parameters
mode Desired exception mode. Possible values are:
0: Hide library messages (quiet mode).
1: Print library messages on the console.
2: Display library messages on a dialog window.
3: Do as 1 + add extra debug warnings (slow down the code!).
4: Do as 2 + add extra debug warnings (slow down the code!).
Definition at line 2341 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::fill(), ftype(), cimg_library_suffixed::CImgList< charT >::get_reverse_object3d(), cimg_library_suffixed::CImg< charT >::load(), cimg_library_suffixed::CImgList< charT >::load(), cimg_library_suffixed::CImg< charT >::load_dcraw_external(), cimg_library_suffixed::CImgList< charT >::load_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), load_network(), cimg_library_suffixed::CImg< charT >::load_other(), cimg_library_suffixed::CImg< charT >::operator=(), and cimg_library_suffixed::CImg< charT >::save_other().
exception_mode() [2/2]
unsigned int& cimg_library_suffixed::cimg::exception_mode () inline
Return current exception mode.
Note
By default, return the value of configuration macro cimg_verbosity
Definition at line 2349 of file CImg.h.
fclose()
int cimg_library_suffixed::cimg::fclose (std::FILE * file) inline
Close a file.
Parameters
file File to close.
Returns
0 if file has been closed properly, something else otherwise.
Note
Same as std::fclose() but display a warning message if the file has not been closed properly.
Definition at line 6185 of file CImg.h.
Referenced by curl_path(), dcraw_path(), cimg_library_suffixed::CImg< charT >::display_object3d(), fempty(), ffmpeg_path(), cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImg< charT >::get_load_ascii(), cimg_library_suffixed::CImg< charT >::get_load_bmp(), cimg_library_suffixed::CImgList< charT >::get_load_cimg(), cimg_library_suffixed::CImg< charT >::get_load_dlm(), cimg_library_suffixed::CImg< charT >::get_load_inr(), cimg_library_suffixed::CImg< charT >::get_load_jpeg(), cimg_library_suffixed::CImg< charT >::get_load_off(), cimg_library_suffixed::CImg< charT >::get_load_pandore(), cimg_library_suffixed::CImg< charT >::get_load_pfm(), cimg_library_suffixed::CImg< charT >::get_load_png(), cimg_library_suffixed::CImg< charT >::get_load_pnm(), cimg_library_suffixed::CImg< charT >::get_load_raw(), cimg_library_suffixed::CImg< charT >::get_load_rgb(), cimg_library_suffixed::CImg< charT >::get_load_rgba(), cimg_library_suffixed::CImgList< charT >::get_load_yuv(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::CImgList< charT >::get_select(), cimg_library_suffixed::CImg< charT >::get_select_graph(), graphicsmagick_path(), gunzip_path(), gzip_path(), imagemagick_path(), cimg_library_suffixed::CImg< charT >::load_dcraw_external(), cimg_library_suffixed::CImgList< charT >::load_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), cimg_library_suffixed::CImg< charT >::load_medcon_external(), load_network(), cimg_library_suffixed::CImgList< charT >::load_parrec(), medcon_path(), cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImg< charT >::save_ascii(), cimg_library_suffixed::CImg< charT >::save_bmp(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_cpp(), cimg_library_suffixed::CImg< charT >::save_dlm(), cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::save_gif_external(), cimg_library_suffixed::CImg< charT >::save_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), cimg_library_suffixed::CImgList< charT >::save_gzip_external(), cimg_library_suffixed::CImg< charT >::save_imagemagick_external(), cimg_library_suffixed::CImg< charT >::save_inr(), cimg_library_suffixed::CImg< charT >::save_jpeg(), cimg_library_suffixed::CImg< charT >::save_medcon_external(), cimg_library_suffixed::CImg< charT >::save_off(), cimg_library_suffixed::CImg< charT >::save_pandore(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_png(), cimg_library_suffixed::CImg< charT >::save_pnk(), cimg_library_suffixed::CImg< charT >::save_pnm(), cimg_library_suffixed::CImg< charT >::save_raw(), cimg_library_suffixed::CImg< charT >::save_rgb(), cimg_library_suffixed::CImg< charT >::save_rgba(), cimg_library_suffixed::CImgList< charT >::save_yuv(), temporary_path(), and wget_path().
fdate() [1/2]
template<typename T > int cimg_library_suffixed::cimg::fdate (const char *const path, T * attr, const unsigned int nb_attr) inline
Get last write time of a given file or directory (multiple-attributes version).
Parameters
path Specified path to get attributes from.
[in,out] attr Type of requested time attributes. Can be { 0=year | 1=month | 2=day | 3=day of week | 4=hour | 5=minute | 6=second } Replaced by read attributes after return (or -1 if an error occured).
nb_attr Number of attributes to read/write.
Returns
Latest read attribute.
Definition at line 6265 of file CImg.h.
Referenced by fdate().
fdate() [2/2]
int cimg_library_suffixed::cimg::fdate (const char *const path, unsigned int attr) inline
Get last write time of a given file or directory (single-attribute version).
Parameters
path Specified path to get attributes from.
attr Type of requested time attributes. Can be { 0=year | 1=month | 2=day | 3=day of week | 4=hour | 5=minute | 6=second }
Returns
Specified attribute or -1 if an error occured.
Definition at line 6309 of file CImg.h.
fempty()
void cimg_library_suffixed::cimg::fempty (std::FILE *const file, const char *const filename) inline
Create an empty file.
Parameters
file Input file (can be 0 if filename is set).
filename Filename, as a C-string (can be 0 if file is set).
Definition at line 6486 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImg< charT >::save_bmp(), cimg_library_suffixed::CImg< charT >::save_dlm(), cimg_library_suffixed::CImg< charT >::save_exr(), cimg_library_suffixed::CImg< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImg< charT >::save_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), cimg_library_suffixed::CImg< charT >::save_imagemagick_external(), cimg_library_suffixed::CImg< charT >::save_inr(), cimg_library_suffixed::CImg< charT >::save_jpeg(), cimg_library_suffixed::CImg< charT >::save_magick(), cimg_library_suffixed::CImg< charT >::save_medcon_external(), cimg_library_suffixed::CImg< charT >::save_minc2(), cimg_library_suffixed::CImg< charT >::save_other(), cimg_library_suffixed::CImg< charT >::save_pandore(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_png(), cimg_library_suffixed::CImg< charT >::save_pnk(), cimg_library_suffixed::CImg< charT >::save_pnm(), cimg_library_suffixed::CImg< charT >::save_raw(), cimg_library_suffixed::CImg< charT >::save_rgb(), cimg_library_suffixed::CImg< charT >::save_rgba(), cimg_library_suffixed::CImg< charT >::save_tiff(), cimg_library_suffixed::CImgList< charT >::save_tiff(), and cimg_library_suffixed::CImgList< charT >::save_yuv().
ffmpeg_path()
const char * cimg_library_suffixed::cimg::ffmpeg_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the FFMPEG's ffmpeg binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the ffmpeg binary.
Definition at line 60032 of file CImg.h.
Referenced by date(), cimg_library_suffixed::CImgList< charT >::load_ffmpeg_external(), and cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external().
files()
CImgList<char> cimg_library_suffixed::cimg::files (const char *const path, const bool is_pattern = false, const unsigned int mode = 2, const bool include_path = false) inline
Return list of files/directories in specified directory.
Parameters
path Path to the directory. Set to 0 for current directory.
is_pattern Tell if specified path has a matching pattern in it.
mode Output type, can be primary { 0=files only | 1=folders only | 2=files + folders }.
include_path Tell if path must be included in resulting filenames.
Returns
A list of filenames.
Definition at line 60256 of file CImg.h.
fopen()
std::FILE* cimg_library_suffixed::cimg::fopen (const char *const path, const char *const mode) inline
Open a file.
Parameters
path Path of the filename to open.
mode C-string describing the opening mode.
Returns
Opened file.
Note
Same as std::fopen() but throw a CImgIOException when the specified file cannot be opened, instead of returning 0.
Definition at line 6154 of file CImg.h.
Referenced by fempty(), cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImg< charT >::get_load_ascii(), cimg_library_suffixed::CImg< charT >::get_load_bmp(), cimg_library_suffixed::CImgList< charT >::get_load_cimg(), cimg_library_suffixed::CImg< charT >::get_load_dlm(), cimg_library_suffixed::CImg< charT >::get_load_inr(), cimg_library_suffixed::CImg< charT >::get_load_jpeg(), cimg_library_suffixed::CImg< charT >::get_load_off(), cimg_library_suffixed::CImg< charT >::get_load_pandore(), cimg_library_suffixed::CImg< charT >::get_load_pfm(), cimg_library_suffixed::CImg< charT >::get_load_png(), cimg_library_suffixed::CImg< charT >::get_load_pnm(), cimg_library_suffixed::CImg< charT >::get_load_raw(), cimg_library_suffixed::CImg< charT >::get_load_rgb(), cimg_library_suffixed::CImg< charT >::get_load_rgba(), cimg_library_suffixed::CImgList< charT >::get_load_yuv(), cimg_library_suffixed::CImg< charT >::load_dcraw_external(), cimg_library_suffixed::CImgList< charT >::load_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), cimg_library_suffixed::CImg< charT >::load_medcon_external(), load_network(), cimg_library_suffixed::CImg< charT >::load_other(), cimg_library_suffixed::CImgList< charT >::load_parrec(), cimg_library_suffixed::CImgList< charT >::load_video(), cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImg< charT >::save_ascii(), cimg_library_suffixed::CImg< charT >::save_bmp(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_cpp(), cimg_library_suffixed::CImg< charT >::save_dlm(), cimg_library_suffixed::CImg< charT >::save_inr(), cimg_library_suffixed::CImg< charT >::save_jpeg(), cimg_library_suffixed::CImg< charT >::save_medcon_external(), cimg_library_suffixed::CImg< charT >::save_off(), cimg_library_suffixed::CImg< charT >::save_pandore(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_png(), cimg_library_suffixed::CImg< charT >::save_pnk(), cimg_library_suffixed::CImg< charT >::save_pnm(), cimg_library_suffixed::CImg< charT >::save_raw(), cimg_library_suffixed::CImg< charT >::save_rgb(), cimg_library_suffixed::CImg< charT >::save_rgba(), and cimg_library_suffixed::CImgList< charT >::save_yuv().
fread()
template<typename T > size_t cimg_library_suffixed::cimg::fread (T *const ptr, const size_t nmemb, std::FILE * stream) inline
Read data from file.
Parameters
[out] ptr Pointer to memory buffer that will contain the binary data read from file.
nmemb Number of elements to read.
stream File to read data from.
Returns
Number of read elements.
Note
Same as std::fread() but may display warning message if all elements could not be read.
Definition at line 6434 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImg< charT >::get_load_bmp(), cimg_library_suffixed::CImg< charT >::get_load_pandore(), cimg_library_suffixed::CImg< charT >::get_load_pfm(), cimg_library_suffixed::CImg< charT >::get_load_png(), cimg_library_suffixed::CImg< charT >::get_load_pnm(), cimg_library_suffixed::CImg< charT >::get_load_raw(), cimg_library_suffixed::CImg< charT >::get_load_rgb(), cimg_library_suffixed::CImg< charT >::get_load_rgba(), and cimg_library_suffixed::CImgList< charT >::load_parrec().
fsize()
cimg_int64 cimg_library_suffixed::cimg::fsize (const char *const filename) inline
Get file size.
Parameters
filename Specified filename to get size from.
Returns
File size or '-1' if file does not exist.
Definition at line 6246 of file CImg.h.
ftype()
const char * cimg_library_suffixed::cimg::ftype (std::FILE *const file, const char *const filename) inline
Try to guess format from an image file.
Parameters
file Input file (can be 0 if filename is set).
filename Filename, as a C-string (can be 0 if file is set).
Returns
C-string containing the guessed file format, or 0 if nothing has been guessed.
Definition at line 60371 of file CImg.h.
Referenced by fempty(), cimg_library_suffixed::CImg< charT >::load(), and cimg_library_suffixed::CImgList< charT >::load().
fwrite()
template<typename T > size_t cimg_library_suffixed::cimg::fwrite (const T * ptr, const size_t nmemb, std::FILE * stream) inline
Write data to file.
Parameters
ptr Pointer to memory buffer containing the binary data to write on file.
nmemb Number of elements to write.
[out] stream File to write data on.
Returns
Number of written elements.
Note
Similar to std::fwrite but may display warning messages if all elements could not be written.
Definition at line 6462 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImg< charT >::save_bmp(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_inr(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_pnk(), cimg_library_suffixed::CImg< charT >::save_pnm(), cimg_library_suffixed::CImg< charT >::save_raw(), cimg_library_suffixed::CImg< charT >::save_rgb(), cimg_library_suffixed::CImg< charT >::save_rgba(), and cimg_library_suffixed::CImgList< charT >::save_yuv().
graphicsmagick_path()
const char * cimg_library_suffixed::cimg::graphicsmagick_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the GraphicsMagick's gm binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the gm binary.
Definition at line 59874 of file CImg.h.
Referenced by date(), info(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_graphicsmagick_external(), and cimg_library_suffixed::CImg< charT >::save_graphicsmagick_external().
gunzip_path()
const char * cimg_library_suffixed::cimg::gunzip_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the gunzip binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the gunzip binary.
Definition at line 60104 of file CImg.h.
Referenced by date(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), and load_network().
gzip_path()
const char * cimg_library_suffixed::cimg::gzip_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the gzip binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the gzip binary.
Definition at line 60068 of file CImg.h.
Referenced by date(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), and cimg_library_suffixed::CImgList< charT >::save_gzip_external().
imagemagick_path()
const char * cimg_library_suffixed::cimg::imagemagick_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the Program Files/ directory (Windows only).
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the program files.Get/set path to the ImageMagick's convert binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the convert binary.
Definition at line 59762 of file CImg.h.
Referenced by date(), info(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), cimg_library_suffixed::CImgList< charT >::save_gif_external(), and cimg_library_suffixed::CImg< charT >::save_imagemagick_external().
info()
void cimg_library_suffixed::cimg::info () inline
Print information about environement variables.
Note
Output is done on the default output stream.
Definition at line 6594 of file CImg.h.
invert_endianness() [1/2]
template<typename T > void cimg_library_suffixed::cimg::invert_endianness (T *const buffer, const cimg_ulong size) inline
Reverse endianness of all elements in a memory buffer.
Parameters
[in,out] buffer Memory buffer whose endianness must be reversed.
size Number of buffer elements to reverse.
Definition at line 4959 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImg< charT >::get_load_pandore(), cimg_library_suffixed::CImg< charT >::get_load_pfm(), cimg_library_suffixed::CImg< charT >::get_load_png(), cimg_library_suffixed::CImg< charT >::get_load_raw(), cimg_library_suffixed::CImgList< charT >::get_serialize(), invert_endianness(), cimg_library_suffixed::CImg< charT >::invert_endianness(), cimg_library_suffixed::CImgList< charT >::load_parrec(), cimg_library_suffixed::CImg< charT >::load_raw(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_png(), and cimg_library_suffixed::CImg< charT >::save_pnm().
invert_endianness() [2/2]
template<typename T > T& cimg_library_suffixed::cimg::invert_endianness (T & a) inline
Reverse endianness of a single variable.
Parameters
[in,out] a Variable to reverse.
Returns
Reference to reversed variable.
Definition at line 4999 of file CImg.h.
is_directory()
bool cimg_library_suffixed::cimg::is_directory (const char *const path) inline
Check if a path is a directory.
Parameters
path Specified path to test.
Definition at line 6216 of file CImg.h.
Referenced by files(), cimg_library_suffixed::CImg< charT >::get_load_raw(), and is_file().
is_file()
bool cimg_library_suffixed::cimg::is_file (const char *const path) inline
Check if a path is a file.
Parameters
path Specified path to test.
Definition at line 6233 of file CImg.h.
load_network()
char * cimg_library_suffixed::cimg::load_network (const char *const url, char *const filename_local, const unsigned int timeout, const bool try_fallback, const char *const referer) inline
Load file from network as a local temporary file.
Parameters
url URL of the filename, as a C-string.
[out] filename_local C-string containing the path to a local copy of filename.
timeout Maximum time (in seconds) authorized for downloading the file from the URL.
try_fallback When using libcurl, tells using system calls as fallbacks in case of libcurl failure.
referer Referer used, as a C-string.
Returns
Value of filename_local.
Note
Use the libcurl library, or the external binaries wget or curl to perform the download.
Definition at line 60431 of file CImg.h.
Referenced by fempty(), cimg_library_suffixed::CImg< charT >::load(), and cimg_library_suffixed::CImgList< charT >::load().
medcon_path()
const char * cimg_library_suffixed::cimg::medcon_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the XMedcon's medcon binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the medcon binary.
Definition at line 59983 of file CImg.h.
Referenced by date(), info(), cimg_library_suffixed::CImg< charT >::load_medcon_external(), and cimg_library_suffixed::CImg< charT >::save_medcon_external().
minmod()
template<typename T > T cimg_library_suffixed::cimg::minmod (const T & a, const T & b) inline
Return the min-mod of two values.
Note
minmod(a,b) is defined to be:
minmod(a,b) = min(a,b), if a and b have the same sign.
minmod(a,b) = 0, if a and b have different signs.
Definition at line 5391 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::sharpen().
mod()
template<typename T > T cimg_library_suffixed::cimg::mod (const T & x, const T & m) inline
Return the modulo of a value.
Parameters
x Input value.
m Modulo value.
Note
This modulo function accepts negative and floating-points modulo numbers, as well as variables of any type.
Definition at line 5348 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::blur_anisotropic(), cimg_library_suffixed::CImg< charT >::draw_grid(), cimg_library_suffixed::CImg< charT >::draw_plasma(), cimg_library_suffixed::CImg< charT >::get_crop(), cimg_library_suffixed::CImg< charT >::get_resize(), cimg_library_suffixed::CImg< charT >::get_rotate(), cimg_library_suffixed::CImg< charT >::get_warp(), cimg_library_suffixed::CImg< charT >::HSItoRGB(), cimg_library_suffixed::CImg< charT >::HSLtoRGB(), cimg_library_suffixed::CImg< charT >::HSVtoRGB(), cimg_library_suffixed::CImg< charT >::operator%=(), cimg_library_suffixed::CImg< charT >::rotate(), and cimg_library_suffixed::CImg< charT >::shift().
output()
std::FILE * cimg_library_suffixed::cimg::output (std::FILE * file) inline
Get/set default output stream for the library messages.
Parameters
file Desired output stream. Set to 0 to get the currently used output stream only.
Returns
Currently used output stream.
Definition at line 4781 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::eval(), info(), load_network(), option(), cimg_library_suffixed::CImg< charT >::print(), and cimg_library_suffixed::CImgList< charT >::print().
round()
template<typename T > T cimg_library_suffixed::cimg::round (const T & x, const double y, const int rounding_type = 0) inline
Return rounded value.
Parameters
x Value to be rounded.
y Rounding precision.
rounding_type Type of rounding operation (0 = nearest, -1 = backward, 1 = forward).
Returns
Rounded value, having the same type as input value x.
Definition at line 5414 of file CImg.h.
sleep()
void cimg_library_suffixed::cimg::sleep (const unsigned int milliseconds) inline
Sleep for a given numbers of milliseconds.
Parameters
milliseconds Number of milliseconds to wait for.
Note
This function frees the CPU ressources during the sleeping time. It can be used to temporize your program properly, without wasting CPU time.
Definition at line 5067 of file CImg.h.
Referenced by cimg_library_suffixed::CImgDisplay::snapshot().
split_filename()
const char* cimg_library_suffixed::cimg::split_filename (const char *const filename, char *const body = 0) inline
Split filename into two C-strings body and extension.
filename and body must not overlap!
Definition at line 6400 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImgList< charT >::is_saveable(), cimg_library_suffixed::CImg< charT >::load(), cimg_library_suffixed::CImgList< charT >::load(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), cimg_library_suffixed::CImg< charT >::load_medcon_external(), load_network(), cimg_library_suffixed::CImgList< charT >::load_parrec(), cimg_library_suffixed::CImg< charT >::save(), cimg_library_suffixed::CImgList< charT >::save(), cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), cimg_library_suffixed::CImgList< charT >::save_gzip_external(), and cimg_library_suffixed::CImg< charT >::save_medcon_external().
strcasecmp()
int cimg_library_suffixed::cimg::strcasecmp (const char *const str1, const char *const str2) inline
Compare two C-strings, ignoring the case.
Parameters
str1 C-string.
str2 C-string.
Returns
0 if the two strings are equal, something else otherwise.
Note
This function has to be defined since it is not provided by all C++-compilers (not ANSI).
Definition at line 5943 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::get_hessian(), cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImgList< charT >::is_saveable(), cimg_library_suffixed::CImg< charT >::load(), cimg_library_suffixed::CImgList< charT >::load(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), option(), cimg_library_suffixed::CImg< charT >::save(), cimg_library_suffixed::CImgList< charT >::save(), cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), cimg_library_suffixed::CImgList< charT >::save_gzip_external(), and cimg_library_suffixed::CImg< charT >::save_inr().
strellipsize() [1/2]
char* cimg_library_suffixed::cimg::strellipsize (char *const str, const unsigned int l = 64, const bool is_ending = true) inline
Ellipsize a string.
Parameters
str C-string.
l Max number of characters.
is_ending Tell if the dots are placed at the end or at the center of the ellipsized string.
Definition at line 5957 of file CImg.h.
Referenced by cimg_library_suffixed::CImgList< charT >::display().
strellipsize() [2/2]
char* cimg_library_suffixed::cimg::strellipsize (const char *const str, char *const res, const unsigned int l = 64, const bool is_ending = true) inline
Ellipsize a string.
Parameters
str C-string.
res output C-string.
l Max number of characters.
is_ending Tell if the dots are placed at the end or at the center of the ellipsized string.
Definition at line 5979 of file CImg.h.
strncasecmp()
int cimg_library_suffixed::cimg::strncasecmp (const char *const str1, const char *const str2, const int l) inline
Compare the first l characters of two C-strings, ignoring the case.
Parameters
str1 C-string.
str2 C-string.
l Number of characters to compare.
Returns
0 if the two strings are equal, something else otherwise.
Note
This function has to be defined since it is not provided by all C++-compilers (not ANSI).
Definition at line 5928 of file CImg.h.
Referenced by cimg_library_suffixed::CImgList< charT >::get_load_cimg(), cimg_library_suffixed::CImg< charT >::get_load_inr(), cimg_library_suffixed::CImg< charT >::get_load_off(), cimg_library_suffixed::CImg< charT >::get_load_pandore(), cimg_library_suffixed::CImgList< charT >::get_unserialize(), cimg_library_suffixed::CImg< charT >::load(), cimg_library_suffixed::CImgList< charT >::load(), load_network(), cimg_library_suffixed::CImg< charT >::save_analyze(), cimg_library_suffixed::CImgList< charT >::save_cimg(), and strcasecmp().
strpare()
bool cimg_library_suffixed::cimg::strpare (char *const str, const char delimiter, const bool is_symmetric, const bool is_iterative) inline
Remove delimiters on the start and/or end of a C-string.
Parameters
[in,out] str C-string to work with (modified at output).
delimiter Delimiter character code to remove.
is_symmetric Tells if the removal is done only if delimiters are symmetric (both at the beginning and the end of s).
is_iterative Tells if the removal is done if several iterations are possible.
Returns
true if delimiters have been removed, false otherwise.
Definition at line 6005 of file CImg.h.
strunescape()
void cimg_library_suffixed::cimg::strunescape (char *const str) inline
Replace escape sequences in C-strings by their binary ascii values.
Parameters
[in,out] str C-string to work with (modified at output).
Definition at line 6053 of file CImg.h.
strwindows_reserved()
void cimg_library_suffixed::cimg::strwindows_reserved (char *const str, const char c = '_') inline
Replace reserved characters (for Windows filename) by another character.
Parameters
[in,out] str C-string to work with (modified at output).
[in] c Replacement character.
Definition at line 6042 of file CImg.h.
Referenced by load_network().
system()
int cimg_library_suffixed::cimg::system (const char *const command, const char *const module_name = 0, const bool is_verbose = false) inline
Parameters
command C-string containing the command line to execute.
module_name Module name.
Returns
Status value of the executed command, whose meaning is OS-dependent.
Note
This function is similar to std::system() but it does not open an extra console windows on Windows-based systems.
Definition at line 4851 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::load_dcraw_external(), cimg_library_suffixed::CImgList< charT >::load_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), cimg_library_suffixed::CImg< charT >::load_medcon_external(), load_network(), cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::save_gif_external(), cimg_library_suffixed::CImg< charT >::save_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), cimg_library_suffixed::CImgList< charT >::save_gzip_external(), cimg_library_suffixed::CImg< charT >::save_imagemagick_external(), and cimg_library_suffixed::CImg< charT >::save_medcon_external().
temporary_path()
const char * cimg_library_suffixed::cimg::temporary_path (const char *const user_path, const bool reinit_path) inline
Get/set path to store temporary files.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path where temporary files can be saved.
Definition at line 59674 of file CImg.h.
Referenced by date(), info(), cimg_library_suffixed::CImg< charT >::load_dcraw_external(), cimg_library_suffixed::CImgList< charT >::load_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::load_gif_external(), cimg_library_suffixed::CImg< charT >::load_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::load_gzip_external(), cimg_library_suffixed::CImgList< charT >::load_gzip_external(), cimg_library_suffixed::CImg< charT >::load_imagemagick_external(), load_network(), cimg_library_suffixed::CImgList< charT >::save_ffmpeg_external(), cimg_library_suffixed::CImgList< charT >::save_gif_external(), cimg_library_suffixed::CImg< charT >::save_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::save_gzip_external(), cimg_library_suffixed::CImgList< charT >::save_gzip_external(), and cimg_library_suffixed::CImg< charT >::save_imagemagick_external().
tic()
cimg_ulong cimg_library_suffixed::cimg::tic () inline
Start tic/toc timer for time measurement between code instructions.
Returns
Current value of the timer (same value as time()).
Definition at line 5049 of file CImg.h.
time()
cimg_ulong cimg_library_suffixed::cimg::time () inline
Return the value of a system timer, with a millisecond precision.
Note
The timer does not necessarily starts from 0.
Definition at line 5028 of file CImg.h.
Referenced by cimg_library_suffixed::CImgDisplay::frames_per_second(), load_network(), sleep(), and wait().
toc()
cimg_ulong cimg_library_suffixed::cimg::toc () inline
End tic/toc timer and displays elapsed time from last call to tic().
Returns
Time elapsed (in ms) since last call to tic().
Definition at line 5057 of file CImg.h.
wait()
cimg_long cimg_library_suffixed::cimg::wait (const unsigned int milliseconds) inline
Wait for a given number of milliseconds since the last call to wait().
Parameters
milliseconds Number of milliseconds to wait for.
Returns
Number of milliseconds elapsed since the last call to wait().
Note
Same as sleep() with a waiting time computed with regard to the last call of wait(). It may be used to temporize your program properly, without wasting CPU time.
Definition at line 5097 of file CImg.h.
Referenced by cimg_library_suffixed::CImgDisplay::snapshot(), and cimg_library_suffixed::CImgDisplay::wait().
warn()
void cimg_library_suffixed::cimg::warn (const char *const format, ...) inline
Display a warning message on the default output stream.
Parameters
format C-string containing the format of the message, as with std::printf().
Note
If configuration macro cimg_strict_warnings is set, this function throws a CImgWarningException instead.
Warning
As the first argument is a format string, it is highly recommended to write
cimg::warn("%s",warning_message);
instead of
cimg::warn(warning_message);
if warning_message can be arbitrary, to prevent nasty memory access.
Definition at line 4826 of file CImg.h.
Referenced by cimg_library_suffixed::CImg< charT >::assign(), cimg_library_suffixed::CImg< charT >::const_empty(), cimg_library_suffixed::CImg< charT >::data(), cimg_library_suffixed::CImgList< charT >::data(), cimg_library_suffixed::CImg< charT >::eigen(), fclose(), cimg_library_suffixed::CImgList< charT >::FFT(), fread(), fwrite(), cimg_library_suffixed::CImg< charT >::get_load_analyze(), cimg_library_suffixed::CImg< charT >::get_load_ascii(), cimg_library_suffixed::CImg< charT >::get_load_jpeg(), cimg_library_suffixed::CImg< charT >::get_load_off(), cimg_library_suffixed::CImg< charT >::get_load_pfm(), cimg_library_suffixed::CImg< charT >::get_load_pnm(), cimg_library_suffixed::CImgList< charT >::get_load_yuv(), cimg_library_suffixed::CImgList< charT >::get_serialize(), cimg_library_suffixed::CImg< charT >::invert(), cimg_library_suffixed::CImg< charT >::load_tiff(), cimg_library_suffixed::CImgList< charT >::load_tiff(), cimg_library_suffixed::CImgList< charT >::load_video(), cimg_library_suffixed::CImgList< charT >::operator()(), cimg_library_suffixed::CImg< charT >::save_bmp(), cimg_library_suffixed::CImgList< charT >::save_cimg(), cimg_library_suffixed::CImg< charT >::save_dlm(), cimg_library_suffixed::CImg< charT >::save_exr(), cimg_library_suffixed::CImg< charT >::save_graphicsmagick_external(), cimg_library_suffixed::CImg< charT >::save_imagemagick_external(), cimg_library_suffixed::CImg< charT >::save_jpeg(), cimg_library_suffixed::CImg< charT >::save_magick(), cimg_library_suffixed::CImg< charT >::save_other(), cimg_library_suffixed::CImg< charT >::save_pfm(), cimg_library_suffixed::CImg< charT >::save_png(), cimg_library_suffixed::CImg< charT >::save_pnk(), cimg_library_suffixed::CImg< charT >::save_pnm(), cimg_library_suffixed::CImg< charT >::save_rgb(), cimg_library_suffixed::CImg< charT >::save_rgba(), cimg_library_suffixed::CImgList< charT >::save_video(), cimg_library_suffixed::CImgDisplay::snapshot(), cimg_library_suffixed::CImg< charT >::solve(), and cimg_library_suffixed::CImg< charT >::symmetric_eigen().
wget_path()
const char * cimg_library_suffixed::cimg::wget_path (const char *const user_path, const bool reinit_path) inline
Get/set path to the wget binary.
Parameters
user_path Specified path, or 0 to get the path currently used.
reinit_path Force path to be recalculated (may take some time).
Returns
Path containing the wget binary.
Definition at line 60176 of file CImg.h.
Referenced by date(), and load_network().
Variable Documentation
logo40x38
const unsigned char cimg_library_suffixed::cimg::logo40x38[4576] static
Initial value:
= {
      177,200,200,200,3,123,123,0,36,200,200,200,1,123,123,0,2,255,255,0,1,189,189,189,1,0,0,0,34,200,200,200,
      1,123,123,0,4,255,255,0,1,189,189,189,1,0,0,0,1,123,123,123,32,200,200,200,1,123,123,0,5,255,255,0,1,0,0,
      0,2,123,123,123,30,200,200,200,1,123,123,0,6,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,29,200,200,200,
      1,123,123,0,7,255,255,0,1,0,0,0,2,123,123,123,28,200,200,200,1,123,123,0,8,255,255,0,1,189,189,189,1,0,0,0,
      2,123,123,123,27,200,200,200,1,123,123,0,9,255,255,0,1,0,0,0,2,123,123,123,26,200,200,200,1,123,123,0,10,255,
      255,0,1,189,189,189,1,0,0,0,2,123,123,123,25,200,200,200,1,123,123,0,3,255,255,0,1,189,189,189,3,0,0,0,1,189,
      189,189,3,255,255,0,1,0,0,0,2,123,123,123,24,200,200,200,1,123,123,0,4,255,255,0,5,0,0,0,3,255,255,0,1,189,
      189,189,1,0,0,0,2,123,123,123,23,200,200,200,1,123,123,0,4,255,255,0,5,0,0,0,4,255,255,0,1,0,0,0,2,123,123,123,
      22,200,200,200,1,123,123,0,5,255,255,0,5,0,0,0,4,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,21,200,200,200,
      1,123,123,0,5,255,255,0,5,0,0,0,5,255,255,0,1,0,0,0,2,123,123,123,20,200,200,200,1,123,123,0,6,255,255,0,5,0,0,
      0,5,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,19,200,200,200,1,123,123,0,6,255,255,0,1,123,123,0,3,0,0,0,1,
      123,123,0,6,255,255,0,1,0,0,0,2,123,123,123,18,200,200,200,1,123,123,0,7,255,255,0,1,189,189,189,3,0,0,0,1,189,
      189,189,6,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,17,200,200,200,1,123,123,0,8,255,255,0,3,0,0,0,8,255,255,
      0,1,0,0,0,2,123,123,123,16,200,200,200,1,123,123,0,9,255,255,0,1,123,123,0,1,0,0,0,1,123,123,0,8,255,255,0,1,189,
      189,189,1,0,0,0,2,123,123,123,15,200,200,200,1,123,123,0,9,255,255,0,1,189,189,189,1,0,0,0,1,189,189,189,9,255,
      255,0,1,0,0,0,2,123,123,123,14,200,200,200,1,123,123,0,11,255,255,0,1,0,0,0,10,255,255,0,1,189,189,189,1,0,0,0,2,
      123,123,123,13,200,200,200,1,123,123,0,23,255,255,0,1,0,0,0,2,123,123,123,12,200,200,200,1,123,123,0,11,255,255,0,
      1,189,189,189,2,0,0,0,1,189,189,189,9,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,11,200,200,200,1,123,123,0,11,
      255,255,0,4,0,0,0,10,255,255,0,1,0,0,0,2,123,123,123,10,200,200,200,1,123,123,0,12,255,255,0,4,0,0,0,10,255,255,0,
      1,189,189,189,1,0,0,0,2,123,123,123,9,200,200,200,1,123,123,0,12,255,255,0,1,189,189,189,2,0,0,0,1,189,189,189,11,
      255,255,0,1,0,0,0,2,123,123,123,9,200,200,200,1,123,123,0,27,255,255,0,1,0,0,0,3,123,123,123,8,200,200,200,1,123,
      123,0,26,255,255,0,1,189,189,189,1,0,0,0,3,123,123,123,9,200,200,200,1,123,123,0,24,255,255,0,1,189,189,189,1,0,0,
      0,4,123,123,123,10,200,200,200,1,123,123,0,24,0,0,0,5,123,123,123,12,200,200,200,27,123,123,123,14,200,200,200,25,
      123,123,123,86,200,200,200,91,49,124,118,124,71,32,124,95,49,56,114,52,82,121,0 }
Definition at line 4750 of file CImg.h.