jubilant-funicular: nta::Result< T > Class Template Reference
nta::Result< T > Class Template Reference
#include <Errors.h>
Public Member Functions
Result (const Result &other)
Public copy constructor.
~Result ()
Public destructor.
bool is_err () const
Is this an Error.
bool is_ok () const
Is this normal data.
T get_data () const
Get the data (only use if is_ok() returns true)
Error get_err () const
Get the Error (only use if is_err() returns true)
T get_data_or (T optb) const
Tries getting data, returning a default value if this is an error.
Static Public Member Functions
static Result new_ok (const T &data)
static Result new_err (const Error &err)
Private Member Functions
Result ()
Private constructor (use new_ok or new_err)
Private Attributes
union {
T data
Error err
};
The data or error held by this Result.
bool is_err_variant
Whether or not an error occured.
Detailed Description
template<typename T>
class nta::Result< T >
Used for returning data when an error could potentially occur
Todo:
Use Result type everywhere it needs to be used
Definition at line 74 of file Errors.h.
Constructor & Destructor Documentation
Result() [1/2]
template<typename T> nta::Result< T >::Result () inline private
Private constructor (use new_ok or new_err)
Definition at line 77 of file Errors.h.
Result() [2/2]
template<typename T> nta::Result< T >::Result (const Result< T > & other) inline
Public copy constructor.
Definition at line 88 of file Errors.h.
~Result()
template<typename T> nta::Result< T >::~Result () inline
Public destructor.
Definition at line 97 of file Errors.h.
Member Function Documentation
get_data()
template<typename T> T nta::Result< T >::get_data () const inline
Get the data (only use if is_ok() returns true)
Definition at line 121 of file Errors.h.
Referenced by nta::ResourceManager::getTexture().
get_data_or()
template<typename T> T nta::Result< T >::get_data_or (T optb) const inline
Tries getting data, returning a default value if this is an error.
Definition at line 137 of file Errors.h.
get_err()
template<typename T> Error nta::Result< T >::get_err () const inline
Get the Error (only use if is_err() returns true)
Definition at line 129 of file Errors.h.
is_err()
template<typename T> bool nta::Result< T >::is_err () const inline
Is this an Error.
Definition at line 117 of file Errors.h.
is_ok()
template<typename T> bool nta::Result< T >::is_ok () const inline
Is this normal data.
Definition at line 119 of file Errors.h.
Referenced by nta::ResourceManager::getTexture().
new_err()
template<typename T> static Result nta::Result< T >::new_err (const Error & err) inline static
Create new Result holding an Error This takes ownership of the err passed in
Definition at line 109 of file Errors.h.
Referenced by nta::ResourceManager::getFile(), and nta::ImageLoader::readImage().
new_ok()
template<typename T> static Result nta::Result< T >::new_ok (const T & data) inline static
Create new Result holding normal data This takes ownership of the data passed in
Definition at line 100 of file Errors.h.
Referenced by nta::ResourceManager::getFile(), nta::ResourceManager::getTexture(), and nta::ImageLoader::readImage().
Member Data Documentation
@5
union { ... }
The data or error held by this Result.
is_err_variant
template<typename T> bool nta::Result< T >::is_err_variant private
Whether or not an error occured.
Definition at line 85 of file Errors.h.
Referenced by nta::Result< T >::new_err(), nta::Result< T >::new_ok(), and nta::Result< T >::Result().
The documentation for this class was generated from the following file:
include/nta/Errors.h