jubilant-funicular: Exponential functions
Exponential functions
Core features
Functions
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::pow (vec< L, T, Q > const &base, vec< L, T, Q > const &exponent)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::exp (vec< L, T, Q > const &v)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::log (vec< L, T, Q > const &v)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::exp2 (vec< L, T, Q > const &v)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::log2 (vec< L, T, Q > const &v)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::sqrt (vec< L, T, Q > const &v)
template<length_t L, typename T , qualifier Q>
GLM_FUNC_DECL vec< L, T, Q > glm::inversesqrt (vec< L, T, Q > const &v)
Detailed Description
Include <glm/exponential.hpp> to use these core features.
These all operate component-wise. The description is per component.
Function Documentation
exp()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::exp (vec< L, T, Q > const & v)
#include <deps/glm/exponential.hpp>
Returns the natural exponentiation of x, i.e., e^x.
Parameters
v exp function is defined for input values of v defined in the range (inf-, inf+) in the limit of the type qualifier.
Template Parameters
L An integer between 1 and 4 included that qualify the dimension of the vector.
T Floating-point scalar types.
See also
GLSL exp man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 80 of file func_exponential.inl.
Referenced by cimg_library_suffixed::CImg< charT >::deriche(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::draw_gaussian(), cimg_library_suffixed::CImg< charT >::exp(), glm::gauss(), cimg_library_suffixed::CImg< charT >::get_blur_patch(), cimg_library_suffixed::cimg::permutations(), and cimg_library_suffixed::cimg::prand().
exp2()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::exp2 (vec< L, T, Q > const & v)
#include <deps/glm/exponential.hpp>
Returns 2 raised to the v power.
Parameters
v exp2 function is defined for input values of v defined in the range (inf-, inf+) in the limit of the type qualifier.
Template Parameters
L An integer between 1 and 4 included that qualify the dimension of the vector.
T Floating-point scalar types.
See also
GLSL exp2 man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 107 of file func_exponential.inl.
inversesqrt()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::inversesqrt (vec< L, T, Q > const & v)
#include <deps/glm/exponential.hpp>
Returns the reciprocal of the positive square root of v.
Parameters
v inversesqrt function is defined for input values of v defined in the range [0, inf+) in the limit of the type qualifier.
Template Parameters
L An integer between 1 and 4 included that qualify the dimension of the vector.
T Floating-point scalar types.
See also
GLSL inversesqrt man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 142 of file func_exponential.inl.
log()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::log (vec< L, T, Q > const & v)
#include <deps/glm/exponential.hpp>
Returns the natural logarithm of v, i.e., returns the value y which satisfies the equation x = e^y. Results are undefined if v <= 0.
Parameters
v log function is defined for input values of v defined in the range (0, inf+) in the limit of the type qualifier.
Template Parameters
L An integer between 1 and 4 included that qualify the dimension of the vector.
T Floating-point scalar types.
See also
GLSL log man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 88 of file func_exponential.inl.
Referenced by nta::GLSLProgram::compileShader(), cimg_library_suffixed::CImg< charT >::draw_mandelbrot(), cimg_library_suffixed::CImg< charT >::get_displacement(), cimg_library_suffixed::cimg::grand(), nta::GLSLProgram::linkShaders(), cimg_library_suffixed::CImg< charT >::log(), and cimg_library_suffixed::cimg::log2().
log2()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::log2 (vec< L, T, Q > const & v)
#include <deps/glm/exponential.hpp>
Returns the base 2 log of x, i.e., returns the value y, which satisfies the equation x = 2 ^ y.
Parameters
v log2 function is defined for input values of v defined in the range (0, inf+) in the limit of the type qualifier.
Template Parameters
L An integer between 1 and 4 included that qualify the dimension of the vector.
T Floating-point scalar types.
See also
GLSL log2 man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 120 of file func_exponential.inl.
pow()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::pow (vec< L, T, Q > const & base, vec< L, T, Q > const & exponent)
#include <deps/glm/exponential.hpp>
Returns 'base' raised to the power 'exponent'.
Parameters
base Floating point value. pow function is defined for input values of 'base' defined in the range (inf-, inf+) in the limit of the type qualifier.
exponent Floating point value representing the 'exponent'.
See also
GLSL pow man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 72 of file func_exponential.inl.
Referenced by cimg_library_suffixed::cimg::cbrt(), cimg_library_suffixed::CImg< charT >::draw_axes(), cimg_library_suffixed::CImg< charT >::draw_ellipse(), nta::FPSLimiter::end(), cimg_library_suffixed::CImg< charT >::get_displacement(), cimg_library_suffixed::CImg< charT >::get_norm(), cimg_library_suffixed::CImg< charT >::get_pow(), cimg_library_suffixed::CImg< charT >::get_select_graph(), cimg_library_suffixed::CImg< charT >::pow(), cimg_library_suffixed::CImg< charT >::RGBtosRGB(), cimg_library_suffixed::CImg< charT >::sharpen(), and cimg_library_suffixed::CImg< charT >::sRGBtoRGB().
sqrt()
template<length_t L, typename T , qualifier Q> GLM_FUNC_DECL vec<L, T, Q> glm::sqrt (vec< L, T, Q > const & v)
#include <deps/glm/exponential.hpp>
Returns the positive square root of v.
Parameters
v sqrt function is defined for input values of v defined in the range [0, inf+) in the limit of the type qualifier.
Template Parameters
L An integer between 1 and 4 included that qualify the dimension of the vector.
T Floating-point scalar types.
See also
GLSL sqrt man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 128 of file func_exponential.inl.
Referenced by cimg_library_suffixed::CImg< charT >::_correlate(), nta::DebugBatch::addLine(), cimg_library_suffixed::CImg< charT >::blur_anisotropic(), cimg_library_suffixed::CImg< charT >::display_object3d(), cimg_library_suffixed::CImg< charT >::draw_ellipse(), cimg_library_suffixed::CImg< charT >::eigen(), glm::gauss(), cimg_library_suffixed::CImg< charT >::get_displacement(), cimg_library_suffixed::CImg< charT >::get_distance_dijkstra(), cimg_library_suffixed::CImg< charT >::get_distance_eikonal(), cimg_library_suffixed::CImg< charT >::get_gradient(), cimg_library_suffixed::CImg< charT >::get_haar(), cimg_library_suffixed::CImg< charT >::get_matrix_at(), cimg_library_suffixed::CImg< charT >::get_norm(), cimg_library_suffixed::CImg< charT >::get_select(), cimg_library_suffixed::cimg::grand(), cimg_library_suffixed::cimg::hypot(), cimg_library_suffixed::CImg< charT >::magnitude(), cimg_library_suffixed::CImg< charT >::noise(), cimg_library_suffixed::CImg< charT >::normalize(), cimg_library_suffixed::cimg::permutations(), cimg_library_suffixed::CImg< charT >::pow(), cimg_library_suffixed::cimg::prand(), nta::Primitive::Primitive(), cimg_library_suffixed::CImg< charT >::PSNR(), glm::radialGradient(), cimg_library_suffixed::CImg< charT >::RGBtoHSI(), cimg_library_suffixed::CImg< charT >::rotation_matrix(), cimg_library_suffixed::CImg< charT >::sphere3d(), cimg_library_suffixed::CImg< charT >::sqrt(), cimg_library_suffixed::CImg< charT >::SVD(), cimg_library_suffixed::CImg< charT >::variance_mean(), and cimg_library_suffixed::CImg< charT >::variance_noise().