jubilant-funicular: nta::PrimitiveBatch Class Reference
nta::PrimitiveBatch Class Reference
represents a collection of primitives to be drawn
#include <PrimitiveBatch.h>
Public Member Functions
PrimitiveBatch ()
constructor and destructor
~PrimitiveBatch ()
int numPrimitives () const
returns number of primitives to be rendered
void init ()
initializes the batch
void begin ()
begins collection of primitive
void end ()
ends collection of primitive and prepares for rendering
void addPrimitive (Primitive *primitive)
adds a primitive to the batch
void addPrimitive (const std::initializer_list< Vertex2D > &vertices, GLuint textureID=-1, float depth=NTA_DEFAULT_DEPTH)
template<class Iterator >
void addPrimitive (Iterator first, Iterator last, GLuint textureID=-1, float depth=NTA_DEFAULT_DEPTH)
void addPrimitive (std::size_t numSides, crvec2 center=glm::vec2(0), float sideLength=1.0, crvec4 color=glm::vec4(1), float orientation=0., float depth=NTA_DEFAULT_DEPTH)
void render () const
renders the primitives
Private Member Functions
void createVertexArrayObject ()
creates vertex array object
void createRenderBatches ()
creates render batches
void sortPrimitives ()
sorts primitives
GLenum toPrimitiveType (unsigned int numVertices) const
return primitive to be drawn
Static Private Member Functions
static bool compareTexture (Primitive *lhs, Primitive *rhs)
comparers used for sorting
static bool comparePrimitive (Primitive *lhs, Primitive *rhs)
static bool compareDepth (Primitive *lhs, Primitive *rhs)
Private Attributes
std::vector< Primitive * > m_primitives
std::vector< RenderBatch > m_renderBatches
the render batches used to draw the primitives
GLuint m_vao = 0
ids for the vertex buffer object and vertex array object used for rendering
GLuint m_vbo = 0
Detailed Description
represents a collection of primitives to be drawn
Definition at line 46 of file PrimitiveBatch.h.
Constructor & Destructor Documentation
PrimitiveBatch()
nta::PrimitiveBatch::PrimitiveBatch ()
constructor and destructor
Definition at line 6 of file PrimitiveBatch.cpp.
~PrimitiveBatch()
nta::PrimitiveBatch::~PrimitiveBatch ()
Definition at line 8 of file PrimitiveBatch.cpp.
Member Function Documentation
addPrimitive() [1/4]
void nta::PrimitiveBatch::addPrimitive (Primitive * primitive)
adds a primitive to the batch
Definition at line 137 of file PrimitiveBatch.cpp.
addPrimitive() [2/4]
void nta::PrimitiveBatch::addPrimitive (const std::initializer_list< Vertex2D > & vertices, GLuint textureID = -1, float depth = NTA_DEFAULT_DEPTH)
Definition at line 140 of file PrimitiveBatch.cpp.
addPrimitive() [3/4]
template<class Iterator > void nta::PrimitiveBatch::addPrimitive (Iterator first, Iterator last, GLuint textureID = -1, float depth = NTA_DEFAULT_DEPTH)
Definition at line 96 of file PrimitiveBatch.h.
addPrimitive() [4/4]
void nta::PrimitiveBatch::addPrimitive (std::size_t numSides, crvec2 center = glm::vec2(0), float sideLength = 1.0, crvec4 color = glm::vec4(1), float orientation = 0., float depth = NTA_DEFAULT_DEPTH)
Definition at line 144 of file PrimitiveBatch.cpp.
begin()
void nta::PrimitiveBatch::begin ()
begins collection of primitive
Definition at line 45 of file PrimitiveBatch.cpp.
Referenced by sortPrimitives().
compareDepth()
bool nta::PrimitiveBatch::compareDepth (Primitive * lhs, Primitive * rhs) static private
Definition at line 77 of file PrimitiveBatch.cpp.
Referenced by sortPrimitives().
comparePrimitive()
bool nta::PrimitiveBatch::comparePrimitive (Primitive * lhs, Primitive * rhs) static private
Definition at line 83 of file PrimitiveBatch.cpp.
Referenced by sortPrimitives().
compareTexture()
bool nta::PrimitiveBatch::compareTexture (Primitive * lhs, Primitive * rhs) static private
comparers used for sorting
Definition at line 80 of file PrimitiveBatch.cpp.
Referenced by sortPrimitives().
createRenderBatches()
void nta::PrimitiveBatch::createRenderBatches () private
creates render batches
Todo:
Render all Primitives using trianges since
Definition at line 86 of file PrimitiveBatch.cpp.
Referenced by end().
createVertexArrayObject()
void nta::PrimitiveBatch::createVertexArrayObject () private
creates vertex array object
Definition at line 27 of file PrimitiveBatch.cpp.
Referenced by init().
end()
void nta::PrimitiveBatch::end ()
ends collection of primitive and prepares for rendering
Definition at line 52 of file PrimitiveBatch.cpp.
init()
void nta::PrimitiveBatch::init ()
initializes the batch
Definition at line 24 of file PrimitiveBatch.cpp.
numPrimitives()
int nta::PrimitiveBatch::numPrimitives () const
returns number of primitives to be rendered
Definition at line 21 of file PrimitiveBatch.cpp.
render()
void nta::PrimitiveBatch::render () const
renders the primitives
Definition at line 148 of file PrimitiveBatch.cpp.
sortPrimitives()
void nta::PrimitiveBatch::sortPrimitives () private
sorts primitives
Definition at line 56 of file PrimitiveBatch.cpp.
Referenced by end().
toPrimitiveType()
GLenum nta::PrimitiveBatch::toPrimitiveType (unsigned int numVertices) const private
return primitive to be drawn
Definition at line 128 of file PrimitiveBatch.cpp.
Referenced by createRenderBatches().
Member Data Documentation
m_primitives
std::vector<Primitive*> nta::PrimitiveBatch::m_primitives private
the primitives to be drawn
Todo:
store primitives on the stack
Definition at line 62 of file PrimitiveBatch.h.
Referenced by addPrimitive(), begin(), createRenderBatches(), numPrimitives(), sortPrimitives(), and ~PrimitiveBatch().
m_renderBatches
std::vector<RenderBatch> nta::PrimitiveBatch::m_renderBatches private
the render batches used to draw the primitives
Definition at line 64 of file PrimitiveBatch.h.
Referenced by begin(), createRenderBatches(), render(), and ~PrimitiveBatch().
m_vao
GLuint nta::PrimitiveBatch::m_vao = 0 private
ids for the vertex buffer object and vertex array object used for rendering
Definition at line 66 of file PrimitiveBatch.h.
Referenced by createVertexArrayObject(), render(), and ~PrimitiveBatch().
m_vbo
GLuint nta::PrimitiveBatch::m_vbo = 0 private
Definition at line 67 of file PrimitiveBatch.h.
Referenced by createRenderBatches(), createVertexArrayObject(), and ~PrimitiveBatch().
The documentation for this class was generated from the following files:
include/nta/PrimitiveBatch.h
src/PrimitiveBatch.cpp