jubilant-funicular: nta::utils::IDFactory< T > Class Template Reference
nta::utils::IDFactory< T > Class Template Reference
Class for generating unique (integral) IDs.
#include <IDFactory.h>
Public Member Functions
IDFactory ()
void clear ()
Resets this to a new IDFactory.
void reset ()
Resets this to a new IDFactory.
T gen_id ()
Generates a new, unused ID.
void free_id (T id)
void free (T id)
calls free_id
std::size_t get_count () const
Returns the number of active ids.
T operator() ()
Calls (and returns) gen_id.
Private Attributes
std::stack< T > m_free
IDs that were previously active but have since been freed.
T m_last_id
The smallest id that has never been assigned.
Detailed Description
template<typename T>
class nta::utils::IDFactory< T >
Class for generating unique (integral) IDs.
Definition at line 14 of file IDFactory.h.
Constructor & Destructor Documentation
IDFactory()
template<typename T> nta::utils::IDFactory< T >::IDFactory () inline
Definition at line 21 of file IDFactory.h.
Member Function Documentation
clear()
template<typename T> void nta::utils::IDFactory< T >::clear () inline
Resets this to a new IDFactory.
Definition at line 23 of file IDFactory.h.
Referenced by nta::utils::IDFactory< Entity >::reset().
free()
template<typename T> void nta::utils::IDFactory< T >::free (T id) inline
calls free_id
Definition at line 34 of file IDFactory.h.
free_id()
template<typename T> void nta::utils::IDFactory< T >::free_id (T id)
Marks an id as free so that it can be reused
id must not already be free
Definition at line 55 of file IDFactory.h.
Referenced by nta::utils::IDFactory< Entity >::free(), and nta::utils::IDFactory< Entity >::reset().
gen_id()
template<typename T > T nta::utils::IDFactory< T >::gen_id ()
Generates a new, unused ID.
Definition at line 44 of file IDFactory.h.
Referenced by nta::utils::IDFactory< Entity >::operator()(), and nta::utils::IDFactory< Entity >::reset().
get_count()
template<typename T> std::size_t nta::utils::IDFactory< T >::get_count () const inline
Returns the number of active ids.
Definition at line 37 of file IDFactory.h.
operator()()
template<typename T> T nta::utils::IDFactory< T >::operator() () inline
Calls (and returns) gen_id.
Definition at line 40 of file IDFactory.h.
reset()
template<typename T> void nta::utils::IDFactory< T >::reset () inline
Resets this to a new IDFactory.
Definition at line 25 of file IDFactory.h.
Member Data Documentation
m_free
template<typename T> std::stack<T> nta::utils::IDFactory< T >::m_free private
IDs that were previously active but have since been freed.
Definition at line 17 of file IDFactory.h.
Referenced by nta::utils::IDFactory< Entity >::free_id(), and nta::utils::IDFactory< Entity >::gen_id().
m_last_id
template<typename T> T nta::utils::IDFactory< T >::m_last_id private
The smallest id that has never been assigned.
Definition at line 19 of file IDFactory.h.
Referenced by nta::utils::IDFactory< Entity >::gen_id().
The documentation for this class was generated from the following file:
include/nta/IDFactory.h