jubilant-funicular: nta::utils::Json Class Reference
nta::utils::Json Class Reference
#include <Json.h>
Classes
class iterator
struct JsonToken
Used for tokenizing strings before parsing them into Json objects.
union JsonToken.__unnamed__
class SetBeginEndKey
Key unlocking the set_{begin,end}() "private" functions of class Json::iterator.
Public Member Functions
Json ()
Json (crstring str)
Json (const char *str)
Json (JsonNum num)
Json (double num)
Json (int num)
Json (JsonObject obj)
Json (JsonArray arr)
Json (bool b)
Json (const std::initializer_list< Json > &data)
Json (const Json &other)
Json (Json &&other)
~Json ()
JsonValueType get_type () const
bool is_string () const
bool is_number () const
bool is_object () const
bool is_array () const
bool is_bool () const
bool is_null () const
std::string as_string () const
JsonNum as_number () const
uint64_t as_uint () const
int64_t as_int () const
double as_float () const
double as_double () const
JsonObject as_object () const
JsonArray as_array () const
bool as_bool () const
std::size_t size () const
bool is_empty () const
bool resize (std::size_t size)
bool push_back (const Json &val)
Json & front ()
Returns first element if this is an array.
Json & back ()
Returns last element if this is an array.
Json & merge (const Json &other)
std::string dump (std::size_t indent=0, std::size_t offset=0) const
operator std::string () const
operator JsonNum () const
operator uint64_t () const
operator int64_t () const
operator int () const
operator float () const
operator double () const
operator JsonObject () const
operator JsonArray () const
operator bool () const
Json & operator= (const Json &other)
Json & operator= (Json &&other)
bool operator== (const Json &other) const
bool operator!= (const Json &other) const
bool operator== (const std::string &other) const
bool operator!= (const std::string &other) const
bool operator== (const char *other) const
bool operator!= (const char *other) const
bool operator== (const JsonNum &other) const
bool operator!= (const JsonNum &other) const
bool operator== (const int &other) const
bool operator!= (const int &other) const
bool operator== (const JsonObject &other) const
bool operator!= (const JsonObject &other) const
bool operator== (const JsonArray &other) const
bool operator!= (const JsonArray &other) const
bool operator== (const bool &other) const
bool operator!= (const bool &other) const
Json & operator[] (crstring key)
When m_type == NONE, first converts this into an Object.
Json & operator[] (crstring key) const
Json & operator[] (const char *key)
Json & operator[] (const char *key) const
Json & operator[] (std::size_t idx)
When m_type == NONE, first converts this into an Array.
Json & operator[] (std::size_t idx) const
Json & operator[] (int idx)
Json & operator[] (int idx) const
iterator< 0 > begin ()
iterator< 1 > cbegin () const
iterator< 0 > end ()
iterator< 1 > cend () const
Static Public Member Functions
static Json string (crstring str)
static Json string (const char *str)
static Json number (JsonNum num)
static Json object (JsonObject obj)
static Json array (JsonArray arr)
static Json boolean (bool boolean)
static Json null ()
static Json parse (crstring json)
Parses Json value from a string.
static Json from_file (crstring path)
Private Types
enum JsonTokenType { SYMBOL, NUMTKN }
Private Member Functions
Json (JsonValueType type)
Static Private Member Functions
static bool lex_string (std::string &str, JsonToken &ret)
Attempts to retreive a string token from the beginning of str.
static bool lex_number (std::string &str, JsonToken &ret)
Attempts to retreive a number token from the beginning of str.
static bool lex_bool (std::string &str, JsonToken &ret)
Attempts to retreive a boolean token from the beginning of str.
static bool lex_null (std::string &str, JsonToken &ret)
Attempts to retreive a null token from the beginning of str.
static std::queue< JsonToken > tokenize (std::string curr)
Converts curr into a stream of tokens.
static Json parse_tokens (std::queue< JsonToken > &tokens)
Converts stream of tokens into a Json value.
Private Attributes
JsonValueType m_type
union {
char * m_str
JsonNum m_num
JsonObject * m_obj
JsonArray * m_arr
bool m_bool
};
Detailed Description
Todo:
Make as_* functions safer and more versatile
An arbitrary Json value (see tests/utils/json_tests.cpp for example usage)
Definition at line 95 of file Json.h.
Class Documentation
nta::utils::Json::JsonToken.__unnamed__
union nta::utils::Json::JsonToken.__unnamed__
Definition at line 260 of file Json.h.
Class Members
JsonNum num
char * str
Member Enumeration Documentation
JsonTokenType
enum nta::utils::Json::JsonTokenType private
Enumerator
SYMBOL
NUMTKN
Definition at line 221 of file Json.h.
Constructor & Destructor Documentation
Json() [1/13]
nta::utils::Json::Json (JsonValueType type) inline private
Definition at line 266 of file Json.h.
Json() [2/13]
nta::utils::Json::Json () inline
Definition at line 291 of file Json.h.
Json() [3/13]
nta::utils::Json::Json (crstring str) inline
Definition at line 292 of file Json.h.
Json() [4/13]
nta::utils::Json::Json (const char * str) inline
Definition at line 293 of file Json.h.
Json() [5/13]
nta::utils::Json::Json (JsonNum num) inline
Definition at line 294 of file Json.h.
Json() [6/13]
nta::utils::Json::Json (double num) inline
Definition at line 295 of file Json.h.
Json() [7/13]
nta::utils::Json::Json (int num) inline
Definition at line 296 of file Json.h.
Json() [8/13]
nta::utils::Json::Json (JsonObject obj) inline
Definition at line 297 of file Json.h.
Json() [9/13]
nta::utils::Json::Json (JsonArray arr) inline
Definition at line 298 of file Json.h.
Json() [10/13]
nta::utils::Json::Json (bool b) inline
Definition at line 299 of file Json.h.
Json() [11/13]
nta::utils::Json::Json (const std::initializer_list< Json > & data)
Definition at line 9 of file Json.cpp.
Json() [12/13]
nta::utils::Json::Json (const Json & other)
Definition at line 25 of file Json.cpp.
Json() [13/13]
nta::utils::Json::Json (Json && other)
Definition at line 28 of file Json.cpp.
~Json()
nta::utils::Json::~Json ()
Definition at line 77 of file Json.cpp.
Member Function Documentation
array()
static Json nta::utils::Json::array (JsonArray arr) inline static
Definition at line 325 of file Json.h.
Referenced by operator==().
as_array()
JsonArray nta::utils::Json::as_array () const inline
Definition at line 356 of file Json.h.
as_bool()
bool nta::utils::Json::as_bool () const
Definition at line 177 of file Json.cpp.
as_double()
double nta::utils::Json::as_double () const inline
Definition at line 354 of file Json.h.
as_float()
double nta::utils::Json::as_float () const inline
Definition at line 353 of file Json.h.
as_int()
int64_t nta::utils::Json::as_int () const inline
Definition at line 352 of file Json.h.
as_number()
JsonNum nta::utils::Json::as_number () const
Definition at line 170 of file Json.cpp.
as_object()
JsonObject nta::utils::Json::as_object () const inline
Definition at line 355 of file Json.h.
as_string()
std::string nta::utils::Json::as_string () const
Definition at line 161 of file Json.cpp.
Referenced by dump(), and parse_tokens().
as_uint()
uint64_t nta::utils::Json::as_uint () const inline
Definition at line 351 of file Json.h.
back()
Json & nta::utils::Json::back ()
Returns last element if this is an array.
Definition at line 142 of file Json.cpp.
begin()
iterator<0> nta::utils::Json::begin () inline
Definition at line 424 of file Json.h.
Referenced by merge(), and operator=().
boolean()
static Json nta::utils::Json::boolean (bool boolean) inline static
Definition at line 330 of file Json.h.
Referenced by operator==(), and parse_tokens().
cbegin()
iterator<1> nta::utils::Json::cbegin () const inline
Definition at line 429 of file Json.h.
Referenced by dump().
cend()
iterator<1> nta::utils::Json::cend () const inline
Definition at line 439 of file Json.h.
Referenced by dump().
dump()
std::string nta::utils::Json::dump (std::size_t indent = 0, std::size_t offset = 0) const
Returns a string representation of the value
Note: never set second parameter
Todo:
Clean up code
Definition at line 185 of file Json.cpp.
end()
iterator<0> nta::utils::Json::end () inline
Definition at line 434 of file Json.h.
Referenced by lex_number(), merge(), and operator=().
from_file()
Json nta::utils::Json::from_file (crstring path) static
Definition at line 353 of file Json.cpp.
front()
Json & nta::utils::Json::front ()
Returns first element if this is an array.
Definition at line 135 of file Json.cpp.
get_type()
JsonValueType nta::utils::Json::get_type () const inline
Definition at line 341 of file Json.h.
is_array()
bool nta::utils::Json::is_array () const inline
Definition at line 345 of file Json.h.
is_bool()
bool nta::utils::Json::is_bool () const inline
Definition at line 346 of file Json.h.
is_empty()
bool nta::utils::Json::is_empty () const inline
Definition at line 360 of file Json.h.
Referenced by dump().
is_null()
bool nta::utils::Json::is_null () const inline
Definition at line 347 of file Json.h.
is_number()
bool nta::utils::Json::is_number () const inline
Definition at line 343 of file Json.h.
is_object()
bool nta::utils::Json::is_object () const inline
Definition at line 344 of file Json.h.
Referenced by Json().
is_string()
bool nta::utils::Json::is_string () const inline
Definition at line 342 of file Json.h.
Referenced by parse_tokens().
lex_bool()
bool nta::utils::Json::lex_bool (std::string & str, JsonToken & ret) static private
Attempts to retreive a boolean token from the beginning of str.
Definition at line 254 of file Json.cpp.
Referenced by tokenize().
lex_null()
bool nta::utils::Json::lex_null (std::string & str, JsonToken & ret) static private
Attempts to retreive a null token from the beginning of str.
Definition at line 268 of file Json.cpp.
Referenced by tokenize().
lex_number()
bool nta::utils::Json::lex_number (std::string & str, JsonToken & ret) static private
Attempts to retreive a number token from the beginning of str.
Definition at line 230 of file Json.cpp.
Referenced by tokenize().
lex_string()
bool nta::utils::Json::lex_string (std::string & str, JsonToken & ret) static private
Attempts to retreive a string token from the beginning of str.
Definition at line 217 of file Json.cpp.
Referenced by tokenize().
merge()
Json & nta::utils::Json::merge (const Json & other)
Adds everything stored in other into this
Returns this
Definition at line 149 of file Json.cpp.
null()
static Json nta::utils::Json::null () inline static
Definition at line 335 of file Json.h.
Referenced by parse(), and parse_tokens().
number()
static Json nta::utils::Json::number (JsonNum num) inline static
Definition at line 315 of file Json.h.
Referenced by operator==(), and parse_tokens().
object()
static Json nta::utils::Json::object (JsonObject obj) inline static
Definition at line 320 of file Json.h.
Referenced by operator==().
operator bool()
nta::utils::Json::operator bool () const inline
Definition at line 392 of file Json.h.
operator double()
nta::utils::Json::operator double () const inline
Definition at line 389 of file Json.h.
operator float()
nta::utils::Json::operator float () const inline
Definition at line 388 of file Json.h.
operator int()
nta::utils::Json::operator int () const inline
Definition at line 387 of file Json.h.
operator int64_t()
nta::utils::Json::operator int64_t () const inline
Definition at line 386 of file Json.h.
operator JsonArray()
nta::utils::Json::operator JsonArray () const inline
Definition at line 391 of file Json.h.
operator JsonNum()
nta::utils::Json::operator JsonNum () const inline
Definition at line 384 of file Json.h.
operator JsonObject()
nta::utils::Json::operator JsonObject () const inline
Definition at line 390 of file Json.h.
operator std::string()
nta::utils::Json::operator std::string () const inline
Definition at line 383 of file Json.h.
operator uint64_t()
nta::utils::Json::operator uint64_t () const inline
Definition at line 385 of file Json.h.
operator!=() [1/8]
bool nta::utils::Json::operator!= (const Json & other) const inline
Definition at line 397 of file Json.h.
operator!=() [2/8]
bool nta::utils::Json::operator!= (const std::string & other) const inline
Definition at line 399 of file Json.h.
operator!=() [3/8]
bool nta::utils::Json::operator!= (const char * other) const inline
Definition at line 401 of file Json.h.
operator!=() [4/8]
bool nta::utils::Json::operator!= (const JsonNum & other) const inline
Definition at line 403 of file Json.h.
operator!=() [5/8]
bool nta::utils::Json::operator!= (const int & other) const inline
Definition at line 405 of file Json.h.
operator!=() [6/8]
bool nta::utils::Json::operator!= (const JsonObject & other) const inline
Definition at line 407 of file Json.h.
operator!=() [7/8]
bool nta::utils::Json::operator!= (const JsonArray & other) const inline
Definition at line 409 of file Json.h.
operator!=() [8/8]
bool nta::utils::Json::operator!= (const bool & other) const inline
Definition at line 411 of file Json.h.
operator=() [1/2]
Json & nta::utils::Json::operator= (const Json & other)
Definition at line 31 of file Json.cpp.
Referenced by Json().
operator=() [2/2]
Json & nta::utils::Json::operator= (Json && other)
Definition at line 52 of file Json.cpp.
operator==() [1/8]
bool nta::utils::Json::operator== (const Json & other) const
Definition at line 358 of file Json.cpp.
operator==() [2/8]
bool nta::utils::Json::operator== (const std::string & other) const inline
Definition at line 398 of file Json.h.
operator==() [3/8]
bool nta::utils::Json::operator== (const char * other) const inline
Definition at line 400 of file Json.h.
operator==() [4/8]
bool nta::utils::Json::operator== (const JsonNum & other) const inline
Definition at line 402 of file Json.h.
operator==() [5/8]
bool nta::utils::Json::operator== (const int & other) const inline
Definition at line 404 of file Json.h.
operator==() [6/8]
bool nta::utils::Json::operator== (const JsonObject & other) const inline
Definition at line 406 of file Json.h.
operator==() [7/8]
bool nta::utils::Json::operator== (const JsonArray & other) const inline
Definition at line 408 of file Json.h.
operator==() [8/8]
bool nta::utils::Json::operator== (const bool & other) const inline
Definition at line 410 of file Json.h.
operator[]() [1/8]
Json & nta::utils::Json::operator[] (crstring key)
When m_type == NONE, first converts this into an Object.
Todo:
Signal error if m_type != OBJECT
Definition at line 84 of file Json.cpp.
operator[]() [2/8]
Json & nta::utils::Json::operator[] (crstring key) const
Todo:
Signal error if m_type != OBJECT
Definition at line 92 of file Json.cpp.
operator[]() [3/8]
Json& nta::utils::Json::operator[] (const char * key) inline
Definition at line 416 of file Json.h.
Referenced by operator[]().
operator[]() [4/8]
Json& nta::utils::Json::operator[] (const char * key) const inline
Definition at line 417 of file Json.h.
Referenced by operator[]().
operator[]() [5/8]
Json & nta::utils::Json::operator[] (std::size_t idx)
When m_type == NONE, first converts this into an Array.
Todo:
Signal error if m_type != ARRAY
Todo:
Signal error if idx is out of bounds
Definition at line 96 of file Json.cpp.
operator[]() [6/8]
Json & nta::utils::Json::operator[] (std::size_t idx) const
Todo:
Signal error if m_type != ARRAY
Todo:
Signal error if idx is out of bounds
Definition at line 105 of file Json.cpp.
operator[]() [7/8]
Json& nta::utils::Json::operator[] (int idx) inline
Definition at line 421 of file Json.h.
Referenced by operator[]().
operator[]() [8/8]
Json& nta::utils::Json::operator[] (int idx) const inline
Definition at line 422 of file Json.h.
Referenced by operator[]().
parse()
Json nta::utils::Json::parse (crstring json) static
Parses Json value from a string.
Definition at line 346 of file Json.cpp.
Referenced by from_file().
parse_tokens()
Json nta::utils::Json::parse_tokens (std::queue< JsonToken > & tokens) static private
Converts stream of tokens into a Json value.
Definition at line 305 of file Json.cpp.
Referenced by parse().
push_back()
bool nta::utils::Json::push_back (const Json & val)
Returns false if m_type != ARRAY (or NONE)
If m_type == NONE, converts this into an ARRAY
Definition at line 127 of file Json.cpp.
Referenced by parse_tokens().
resize()
bool nta::utils::Json::resize (std::size_t size)
Returns false if m_type is not NONE or ARRAY
If m_type == NONE, converts this into an ARRAY
Definition at line 117 of file Json.cpp.
size()
std::size_t nta::utils::Json::size () const
Definition at line 110 of file Json.cpp.
string() [1/2]
static Json nta::utils::Json::string (crstring str) inline static
Definition at line 305 of file Json.h.
Referenced by operator==(), and parse_tokens().
string() [2/2]
static Json nta::utils::Json::string (const char * str) inline static
Definition at line 310 of file Json.h.
tokenize()
std::queue< Json::JsonToken > nta::utils::Json::tokenize (std::string curr) static private
Converts curr into a stream of tokens.
Todo:
Error cleanly
Definition at line 277 of file Json.cpp.
Referenced by parse().
Member Data Documentation
@9
union { ... }
m_type
JsonValueType nta::utils::Json::m_type private
Definition at line 282 of file Json.h.
Referenced by as_bool(), as_number(), as_string(), back(), dump(), front(), Json(), merge(), operator=(), operator==(), operator[](), push_back(), resize(), size(), and ~Json().
The documentation for this class was generated from the following files:
include/nta/Json.h
src/Json.cpp