jubilant-funicular: nta::SpriteSheet Struct Reference
nta::SpriteSheet Struct Reference
Multiple sprites (each the same size) in one texture.
#include <Animation2D.h>
Public Member Functions
SpriteSheet ()
SpriteSheet (const GLTexture &tex, crivec2 dims)
SpriteSheet (crstring file_path, crivec2 dims)
SpriteSheet (crstring file_path, int num_cols)
glm::vec4 get_uv (std::size_t index) const
glm::vec4 get_flipped_uv (std::size_t index) const
Like get_uv except it flips the sprite horizontally.
glm::vec2 get_frame_dims () const
Returns the dimensions of one sprite in this sheet.
Public Attributes
GLTexture tex
The texture holding all the sprites.
union {
glm::ivec2 dims
struct {
int num_rows
int num_cols
}
};
The dimensions of the sheat (rows x cols)
Detailed Description
Multiple sprites (each the same size) in one texture.
Definition at line 8 of file Animation2D.h.
Constructor & Destructor Documentation
SpriteSheet() [1/4]
nta::SpriteSheet::SpriteSheet () inline
Definition at line 9 of file Animation2D.h.
Referenced by SpriteSheet().
SpriteSheet() [2/4]
nta::SpriteSheet::SpriteSheet (const GLTexture & tex, crivec2 dims) inline
Definition at line 13 of file Animation2D.h.
SpriteSheet() [3/4]
nta::SpriteSheet::SpriteSheet (crstring file_path, crivec2 dims)
Definition at line 9 of file Animation2D.cpp.
SpriteSheet() [4/4]
nta::SpriteSheet::SpriteSheet (crstring file_path, int num_cols) inline
Definition at line 16 of file Animation2D.h.
Member Function Documentation
get_flipped_uv()
glm::vec4 nta::SpriteSheet::get_flipped_uv (std::size_t index) const inline
Like get_uv except it flips the sprite horizontally.
Definition at line 29 of file Animation2D.h.
Referenced by nta::Animation2D::Animation2D(), and nta::Animation2D::get_flipped_uv().
get_frame_dims()
glm::vec2 nta::SpriteSheet::get_frame_dims () const inline
Returns the dimensions of one sprite in this sheet.
Definition at line 36 of file Animation2D.h.
Referenced by nta::Animation2D::Animation2D(), and nta::Animation2D::get_frame_dims().
get_uv()
glm::vec4 nta::SpriteSheet::get_uv (std::size_t index) const inline
Gets UV-coordinates of specific sprite in the sheet
The topleft sprite is index 0 and indices increase moving to the right
Definition at line 21 of file Animation2D.h.
Referenced by nta::Animation2D::Animation2D(), get_flipped_uv(), and nta::Animation2D::get_uv().
Member Data Documentation
@1
union { ... }
The dimensions of the sheat (rows x cols)
tex
GLTexture nta::SpriteSheet::tex
The texture holding all the sprites.
Definition at line 40 of file Animation2D.h.
Referenced by get_frame_dims(), nta::Animation2D::get_tex_id(), and SpriteSheet().
The documentation for this struct was generated from the following files:
include/nta/Animation2D.h
src/Animation2D.cpp